### PR TITLE
Backport doc updates from `master` into `release-0.15.x`

### PR DESCRIPTION
**Pull request by bfritz**
Not sure this is a good idea.  Publishing PR to solicit feedback.

Backports most changes in `docs/src/hugo` from `master` into the `release-0.15.x` branch.  Intent is:
1. Avoid flashbacks on http4s.org when Travis publishes to `gh-pages` from `release-0.15.x`.
2. Reduce unnecessary differences between `release-0.15.x` and `master`, e.g. to simplify merges.

-- -- --

Applied with:

    $ git diff origin/release-0.15.x..origin/master -- docs/src/hugo | patch -p1
    $ git checkout docs/src/hugo/config.toml
    $ git add --all

Changes include:

    $ git log --reverse --no-merges --pretty=format:"%h  %ad  %<(19)%an %s" --date=short \
      origin/release-0.15.x..origin/master -- docs/src/hugo

    874ad2b43  2016-12-27  Ross A. Baker       Fix GitHub link
    ebc348429  2016-12-27  Ross A. Baker       Move CNAME into hugo static directory
    4605c8f15  2016-12-27  Ross A. Baker       Master docs should be on v0.16
    82066cdc1  2016-12-28  Darren Gibson       Update adopters.md
    b7071971a  2017-01-04  Brad Fritz          Fix Markdown links on community page
    76bcdd8b0  2017-01-12  Jan Vincent Liwanag Fix scalaz version for 0.14.11 / 0.14.11a
    b0d1ac797  2017-01-25  Ross A. Baker       List 0.16 snapshots, including cats
    a41f4d0f8  2017-02-21  Brad Fritz          Update version table to 0.15.5
    dd551db68  2017-02-23  Timo Schmid         Update adopters.md
    96a7de5d3  2017-02-22  Brad Fritz          Fix link from community page to to contributors' guide
    383bb0745  2017-02-22  Brad Fritz          Move website `<nav>` element under `<body>`
    9bd947b0f  2017-02-26  Brad Fritz          Move script tags for jQuery and Bootstrap to bottom of page
    3dc34be51  2017-02-26  Brad Fritz          Correct Twitter link in menu bar
    d4692ce6b  2017-02-22  Brad Fritz          Introduce Documentation menu in top navigation bar
    bb361133a  2017-02-26  Brad Fritz          Move "Versions" menu item under "Documentation"
    89aa4234d  2017-03-03  Ross A. Baker       What else can I foul up this evening?
    471e52591  2017-03-24  Ross A. Baker       Statement on future versions
    040907b8d  2017-03-24  Ross A. Baker       Links and grammar fixes to roadmap statement
    fc31c0ae7  2017-03-26  Ross A. Baker       Mention shims and harmony for Scalaz users in the 0.17+ world
    5639b0a8c  2017-03-26  Ross A. Baker       Update versions in nav dropdown
    0b145cf4c  2017-03-27  Bjørn Madsen        Update formatting of versions in text

### CODE REVIEW

**Comment by rossabaker** [comment]
I think backporting changes to menus, layouts, etc. is a good and necessary thing, given the current structure.  That it's necessary is why it's a bad structure.

Backporting common _content_, like the versions page, I'm indifferent to.  Though maybe it's useful for the generation of any common menus on the site page.  Which points to the first paragraph.

The fundamental problem here is the branching strategy that makes sense for the code and the `v${major}.${minor}` directories of the site are not sensible for docs/src/hugo.

Alternatives to ponder:

1. Create a `hugo` branch.  Main builds publish tuts to `hugo` branch as markdown, Travis publishes `hugo` branch to `gh-pages`.  That way, all content is always regenerated from a single copy of the common area.  Makes it hard to preview the entire site.

2. Go back to jekyll, publish selectively to `gh-pages` branch, let GitHub render that.  Similar to the above, with the additional drawback of being jekyll.

3. Make docs/src/hugo a git submodule.  Introduces the complication of git submodules.  Would not refresh older versions of the docs if we changed templates.

4. To hell with it: we maintain one version of the site.  Not great during the scalaz to cats transition.

5. To a different hell with it: we maintain versioned sites with no common area.  But some important information _is_ common, like versions.

**Comment by bfritz** [comment]
Might be an interesting experiment to register our `gh-pages` branch as a submodule at `docs/target/site`*.  Versioned content (scaladoc, tuts) would be routed to an appropriate `v${major}.${minor}` subdirectory (as currently happens).  That gets us away from a site-per-branch and to a single site in gh-pages for all branches.  There's some precedent in [this repo](https://github.com/shiftyp/submodule-gh-pages-example).

\* Not sure if it would be `site`, `site-stage`, or `hugo`...but one of 'em.

**Comment by rossabaker** [comment]
Experimentation can be done in a fork.  You won't get the CNAME for it, but gh-pages will render it as a project page and see how it feels.

**Comment by bfritz** [comment]
Yep.  On my radar.  No promises though...still digging out from a few days away.

**Comment by bfritz** [comment]
Probably little value in these backports.  If we're still publishing shared site content from the `release-*` branches, that should be fixed separately.  When working on #972, it might make sense to try the `gh-pages` submodule hack [described above](https://github.com/http4s/http4s/pull/1067#issuecomment-290293769).

**Pull request closed without merging**
