### PR TITLE
Add a lenient flag in constructors for blaze-client

### PR DESCRIPTION
**Pull request by clayrat**
This just adds some constructors and convenience functions for https://github.com/http4s/blaze/pull/32

### CODE REVIEW

**Comment by rossabaker** [comment]
Blocked by http4s/blaze#32 and/or http4s/blaze#36, but not forgotten.

**Comment by clayrat** [comment]
Now that https://github.com/http4s/blaze/pull/36 is merged, is this good enough? :)

**Comment by bryce-anderson** [comment]
I believe this needs a blaze release to work, which I believe can happen pretty soon.

Another concern: do we need a default lenient client? The same could be asked for the non-lenient client. At a minimum I think they should be `lazy`.

**Comment by bryce-anderson** [comment]
@clayrat, feel free to bump the blaze dependency to 0.12.0-SNAPSHOT: I don't think we'll do a blaze release until something bigger happens or http4s is going to do a minor release.

**Comment by rossabaker** [comment]
#542 added this.

**Pull request closed without merging**
