### PR TITLE
Fix scala-steward.conf syntax

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
I think this is why Tomcat appeared in #5983.

**Review by armanbilge — APPROVED** [review]
We need a CI validator for this ...

**Comment by rossabaker** [comment]
It's HOCON.  An sbt plugin around Typesafe Config would be plausible.  I set up an Emacs linter based on pyhocon, but it's a different implementation, and we wouldn't want Python in our CI.

**Comment by rossabaker** [comment]
You could go deeper with a semantic parser, but then you'd need a @scala-steward library.

**Comment by armanbilge** [comment]
Yeah, an sbt plugin could be nice. HOCON is just JSON so you could define in sbt and have it generated by sbt-gh-actions and it doesn't need to be human-editable.

**Comment by fthomas** [comment]
> You could go deeper with a semantic linter, but then you'd need a @scala-steward library.

This already exists: https://repo1.maven.org/maven2/org/scala-steward/scala-steward-core_2.13/0.13.0/. It is probably not too hard to write a scala-cli script that uses the above JAR to parse and decode `.scala-steward.conf` as part of the CI.

@danicheg (who is still waiting for an answer from me) proposed another solution to this problem in https://github.com/scala-steward-org/scala-steward/pull/2446.

**Comment by danicheg** [comment]
Argh. Shame on me with that 😞  I am itching to fix that in some way.

**Pull request merged**
