### PR TITLE
Release v1.0.0-M31

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
GitHub decided to pull these release notes starting on 0.23.9, so our automation kind of sucked on this one.  I did my best.

**Comment by armanbilge** [comment]
Oh yeah, I think that's the state-of-the-art for pre-releases. It always starts over from the last stable release and ignores all previous pre-releases in between. I wonder if that's configurable.

**Comment by armanbilge** [comment]
Every time we cut a 1.0 milestone, we could label all the merged PRs up to that point with some "merged" label that we exclude from the release notes. Stoopid.

**Review by armanbilge — APPROVED** [review]

**Comment by rossabaker** [comment]
It might be better next time, because this included some that predate the label.  Let's see how bad M32 is before we panic.

**Comment by armanbilge** [comment]
I've done lots of pre-releases lately (sbt-typelevel and feral) and this is how it's worked for those.

**Comment by rossabaker** [comment]
I tried to be smarter than it by not checking the prerelease box, but, nope.

**Comment by rossabaker** [comment]
We could make mergify tag these as series/1.0, I guess.

**Comment by armanbilge** [comment]
We'd have to go back and un-pre-release all the previous pre-releases as well for that to work I think. Apparently pre-releases don't really count for announcing stuff.

**Comment by armanbilge** [comment]
> We could make mergify tag these as series/1.0, I guess.

I'm not sure that would solve the problem, since I think it still would include `series/1.0` PRs from previous pre-releases. That's why we need a way of marking PRs after we make a release.

**Comment by rossabaker** [comment]
Oh, hell.  You're right.

**Pull request merged**
