### PR TITLE
Fix http4s/http4s#485

### PR DESCRIPTION
**Pull request by hvesalai**

### CODE REVIEW

**Comment by bryce-anderson** [comment]
I'd like to see the `requireClose` be predicated on writing a complete body in addition to resulting in a `Failure`.

Also, would that test be easy to include in the PR or would it be a big pain?

**Comment by hvesalai** [comment]
I tested by adding a service into the ExampleServices and I figured you woudn't like me to push that.

**Comment by hvesalai** [comment]
I was also looking at how to make a real test case, but didn't feel confident enough with the test framework to write it.

**Comment by rossabaker** [comment]
If it's a useful example for end users, additions to ExampleServices are welcome.  If it's awkward to test in an automated fashion, but is tested manually, that's mostly what the "science experiments" are for.  Don't be shy about adding to either one.

**Comment by hvesalai** [comment]
@rossabaker pushed the ExampleService changes to #487

**Comment by hvesalai** [comment]
@bryce-anderson how about if we get rid of `requireClose` completely and change the definition of `writeEnd` to

```scala
  /** Write the ending chunk and, in chunked encoding, a trailer to the wire.
    * If a request is cancelled, or the stream is closed this method should
    * return a failed Future with Cancelled as the exception. Otherwise it should 
    * return a boolean indicating if the writer requires the connection to be closed
    *
    * @param chunk BodyChunk to write to wire
    * @return a future letting you know when its safe to continue or close the connection
    */

protected def writeEnd(chunk: ByteVector): Future[Boolean]
```

**Comment by bryce-anderson** [comment]
@hvesalai, without looking too deeply into the repercussions that seems like a great idea.

**Comment by hvesalai** [comment]
@bryce-anderson pull request updated (replaced commits)

**Comment by bryce-anderson** [comment]
:+1:  LGTM. I think this is a great solution to the `requireClose()` concern: the fewer methods the better.

I'll wait a few hours to merge this just in case anybody else wants to look it it. If anybody with merge rights likes it, feel free to merge it for me.

Once again, thanks @hvesalai for another great PR.

**Comment by rossabaker** [comment]
:+1:, this is smart.

**Pull request merged**
