### PR TITLE
Fix sbt new docs for Windows

### LINKED ISSUE #1169: g8 command documentation issue for Windows in Quick Start section of tutorial
The command given in Quick Start to clone from the g8 template works as is on Linux, but to get it to work in Windows I have to replace the two arguments "-sbt-version 0.13.13" given in the tutorial with a single argument "-sbt-version0.13.13" (omitting the space between what are separate arguments in Linux).

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Fixes #1169 

If you could confirm that this is the correct command. @brinklec

### CODE REVIEW

**Comment by brinklec** [comment]
I have not previously worked with pull requests, so it’s quite possible I am missing something elementary.

I checked the Getting Started page of the online tutorial both for the 0.15 version referenced here, and for the 0.17 version I have been using.  No addition to the tutorial language describing the argument difference required to clone the template for Windows appears in either.  Naively was expecting to see some new wording, at least in the 0.15 version.  Perhaps I am going about this all wrong for what you ask?

                With apologies,
                                Chris Brinkley

**Comment by ChristopherDavenport** [comment]
Nope just the code until it gets merged, then it will make it to the page.

Here are the line changes 

```sbt
  // Linux/Mac
  $ sbt -sbt-version 0.13.13 new http4s/http4s.g8		  $ sbt -sbt-version 0.13.13 new http4s/http4s.g8
  // Windows
  $ sbt -sbt-version0.13.13 new http4s/http4s.g8
```

**Comment by brinklec** [comment]
Thanks, that looks correct.  Here is the successful result of pasting your updated Windows command to my console:

c:\scala>sbt -sbt-version0.13.13 new http4s/http4s.g8
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support wa
s removed in 8.0
[info] Set current project to scala (in build file:/C:/scala/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed
in 0.14.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
name [http4s quickstart]:

--Chris

By the way, do you know why it gives the above SLF4J no-binding-found warnings?  I see these all the time.

**Comment by ChristopherDavenport** [comment]
Updated SBT Version As Suggested. When this passes CI we should be good to go.

**Comment by rossabaker** [comment]
I'm going to try to hook up a profiler to the tests sometime this week.  Failure is not related to this.

**Pull request merged**
