### PR TITLE
Update compatible dependencies on 0.21.x

### PR DESCRIPTION
**Pull request by rossabaker**
* ~~boopickle-1.3.2 (supersedes #3419)~~
* json4s-3.6.8
* log4cats-1.1.1 (supersedes #3418)
* metrics-4.1.7 
* okhttp-4.6.0
* scalatags-0.9.1
* specs2-4.9.4
* Adds filters so dependencyUpdates runs clean

### CODE REVIEW

**Comment by rossabaker** [comment]
We have a [real problem in boopickle](https://github.com/http4s/http4s/runs/678905617#step:11:57). This looks like what happens when a library builds on a later JDK than 8 and then runs on 8, but curiously it's not affecting the 2.13.2/1.8 build.

@cquiroz, I think you've been involved on that project. Do you know what happened here?

**Comment by cquiroz** [comment]
It looks like the build was done with another jdk. There  are a few troubles on scala.js as well
There is a PR to help standardize the build but it is awaiting review

**Comment by rossabaker** [comment]
Okay. I think 1.3.2 was a cursed release. Let's back that out and move forward with the rest.

**Comment by rossabaker** [comment]
Smaller than the one that was already approved, so merging to reduce clutter.

**Pull request merged**
