### PR TITLE
Add sbt alias to run all tests everywhere

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes https://github.com/http4s/http4s/issues/5236. @rossabaker can you try locally? Although you will need a ton of stuff installed (Node, Firefox, Chrome, geckodriver, chromedriver).

### CODE REVIEW

**Comment by rossabaker** [comment]
I would like to identify all those things and get them in the nix-shell so they're there on all my machines and for any other nix folks who happen along.  I don't even know what two of them are, but I'll chip away at it.

**Comment by rossabaker** [comment]
Would this be a good time to spin off the browser modules into their own repo?  Since they're not being maintained in upstream branches, it seems that those could get a head start on The Great Schism.

**Comment by armanbilge** [comment]
Yep. This is what I was saying earlier today in https://github.com/http4s/http4s/issues/5230#issuecomment-923063605.

**Comment by rossabaker** [comment]
Ah, I don't think I fully understood what that meant yet.  Preparing this release is the first time I've had to get all this machinery running locally, so I'm only gradually beginning to understand it.  I think that would make a lot of sense.  It'll be the first thing that has a different release cycle than 1.0, but it'll give us some runtime getting used to those problems before the modules that are widely in production hit it.  I think it will be good for everything.

**Comment by armanbilge** [comment]
As I'm learning how you do things here I think so too, the dom modules are a sore thumb in the main repo. Daniel was ecstatic when we moved a lot of the browser testing in cats-effect to scala-js-macrotask-executor although we couldn't completely purge it.

**Comment by rossabaker** [comment]
What's an appropriate name? http4s-browser?  http4s-dom?  Do all of these modules belong in their own?

**Comment by armanbilge** [comment]
I'd say `http4s-dom`. These modules can all go together.

**Comment by rossabaker** [comment]
http4s-dom exists now.

**Comment by armanbilge** [comment]
Thanks. Give me a couple hours and hopefully I'll have a PR to yank it out of main 👍

**Comment by armanbilge** [comment]
Superseded by #5241.

**Pull request closed without merging**
