### PR TITLE
Scala 2.12 support

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
Currently blocked on scalaz-stream support for RC2.

Am told some dependencies don't exist for scalaz-7.1, hence the Travis exclusion.

/cc @larsrh, who has been asking about this.

**Comment by bryce-anderson** [comment]
I didn't see changes for blaze in there, but its only dependency is log4s so it should be good to go.

**Comment by rossabaker** [comment]
I think I got stopped cold by scalaz-stream and didn't see what else was missing, but good point.

**Comment by rossabaker** [comment]
This is going to require incompatible versions of several libraries.  Retargeting master.

**Comment by rossabaker** [comment]
@larsrh: If you just need a subset of modules, I might be able to make this happen on the 0.14 release series.  Otherwise, proper support is going to be based off master in #742.

**Comment by larsrh** [comment]
@rossabaker Coursier requires `http4s-blazeserver` and `http4s-dsl`.

**Comment by rossabaker** [comment]
Okay, I think I can get it this far now, but it will mean introducing selective cross builds.

**Comment by larsrh** [comment]
Don't sweat it, it's not urgent. As far as I understand @alexarchambault has introduced a selective cross build in coursier itself, so that the HTTP component only builds with 2.11.

**Comment by rossabaker** [comment]
In that case, I think we'll introduce it in 0.15, and try to get 0.15 out the door soon.

**Pull request closed without merging**
