### PR TITLE
Convert to sbt-microsites

### PR DESCRIPTION
**Pull request by rossabaker**
Pros:
- Get a consistent look and feel with other Typelevel projects
- Simplified build
- DRY up readme and contributing guide, which are meaningful both on site and GitHub

Cons:
- microsites doesn't support versioned sites yet
- Jekyll metadata on readme and contributing guide on GitHub

### CODE REVIEW

**Comment by rossabaker** [comment]
I can live without the versioned sites.  It complicated things, scaladoc archives are published in Maven Central, and our docs aren't that mature yet anyway.  This is something I'm more likely to lose sleep over in a version 2.x.

**Comment by reactormonk** [comment]
How difficult would it be to add custom link expanders? Then we could do `/#org.http4s.EntityEncoder` and care about adding versioned docs later.

**Comment by dbousamra** [comment]
Is there a way to see the microsite up and running?

**Comment by rossabaker** [comment]
I don't know how to write custom expanders, though it's probably possible with a jekyll module.  If we just do `../api/#org.http4s.EntityEncoder` now, it should just work though, right?

It can be seen up and running with the directions in doc/README.md.

**Comment by reactormonk** [comment]
If the version and docs/api are switched, yes.

**Comment by rossabaker** [comment]
Instructions to preview it are in docs/README.md

**Comment by rossabaker** [comment]
Needs the favicon and the logo back.  I still want to build an outline for future docs.  But I think this is a little more presentable than what we previously had.  I'd like to consider rolling this out tomorrow with a couple more fixes and then announcing our 0.15 release.

Comments?

**Comment by rossabaker** [comment]
We also can't customize layouts yet.

**Comment by rossabaker** [comment]
See also #782.  I think I prefer hugo to jekyll, which sbt-microsites forces on us.

**Comment by rossabaker** [comment]
Closing in favor of #782

**Pull request closed without merging**
