### PR TITLE
Port to cats and fs2

### LINKED ISSUE #390: The future: Scalaz, Cats, both, or neither?
## Ground rules

Scalaz and Cats provide a lot of overlapping functionality that is useful to our library.  Each has a both a devoted following and strong detractors.  We are not here to discuss history or politics, but to transparently decide the way forward for this project.
## The present

Currently, we are a unabashedly a Scalaz library.  We get this transitive dependency from scalaz-stream, so we might as well use it.  
## The looming change

Soon, [scalaz-stream will be decoupled](https://github.com/scalaz/scalaz-stream#issues/321).  The approach taken there is to not depend on either Scalaz or Cats, and redefine its own foundational type classes (e.g., Monad) as necessary.

Once we depend on this version of scalaz-stream, tentatively to be branded 0.9, the Scalaz decision is no longer made for us.
### Decouple core from either library

Pros:
- Follows streams' philosophy that "The ecosystem should not pick a winner." 
- Imposes no new dependencies on us beyond streams.
- Does not bifurcate our community.

Cons:
- Forces us to settle for inferior types (e.g., `scala.Either` vs. `scalaz.\/`) or reinvent them.
- Other similarly principled libraries (e.g., doobie, remotely) will need similar reinventions, and without using a library, provide a worse interop experience.
- Instances could be supplied by http4s-scalaz and/or http4s-cats integration modules, but would no longer conveniently appear in companion objects.

Short term impact:
- We should move all direct Scalaz dependencies to a support module or delete them.
### Build on Scalaz

Pros:
- No additional breaking changes
- Matches current state of doobie and remotely.  This is no guarantee those projects don't change.

Cons:
- Gives second-class status to Cats projects.
- Scalaz is already discussing an incompatible version 8.  That's basically a whole new library.

Short term impact:
- None
### Build on Cats

Pros:
- Cats has a rapidly growing community.
- Our existing maintainers contribute more to Cats than Scalaz.

Cons:
- Less mature than Scalaz, further pushing out our timeline for a long-term support API.
- Gives second-class status to Scalaz projects, which are presently more numerous.

Short term impact:
- Keep building on Scalaz, as long as the concept is or is expected to appear in Cats.  Some API will change, but the concepts are the same.
- <ins>Consider migrating instance layout to match Cats conventions</ins>.
### Cross-build

Pros:
- http4s is positioned well if either or both libraries continue on strong.

Cons:
- Maintaining cross-build stretches thin development team even thinner.
- Some who have tried cross-building advise that this way madness lies.
- Depending how we do it, restricts us to the intersection of functionality supported by Scalaz and Cats.

Short term impact:
- None

### PR DESCRIPTION
**Pull request by rossabaker**
The tasks are now broken down on the [fs2-cats project](https://github.com/http4s/http4s/projects/3).  This is a team effort, so please see that board and comment on any tickets you're interested in contributing to.

### CODE REVIEW

**Comment by rossabaker** [comment]
I'm going to need a jawn-fs2 to go with jawn-streamz.

**Comment by aeons** [comment]
So if I wanted to look at jawn-fs, I would start with the code in rossabaker/jawn-fs2 right? That looks to be a renamed repository with scalaz stream code in it currently?

**Comment by rossabaker** [comment]
@aeons That's exactly right.  I renamed the repo but got sidetracked before I did the work.  Do you want to give it a try?

**Comment by aeons** [comment]
Yes, I'll give it a go :)

**Comment by rossabaker** [comment]
Thanks to @aeons, we are unblocked on argonaut, circe, and json4s.  If anyone would like to adopt one or all, please speak up.

**Comment by aeons** [comment]
I added some PRs for circe and json4s. For argonaut, there's a version for cats, that is at version 6.2-M3. Would that be acceptable to use here?

**Comment by utaal** [comment]
I'm taking a look at blaze-server, got it to compile but currently failing because blaze-core calls `.array` on `ByteBuffer`, which is an "optional method" and not available for read-only buffers. I'm trying to write a new `Chunk` implementation that wraps a `ByteBuffer` instead of an `Array[Byte]`. I'm not familiar with the codebase, so this may go nowhere, I'll make sure to let you know if I'm completely stuck.

**Comment by agustafson** [comment]
Hi, I've added a PR for metrics: https://github.com/http4s/http4s/pull/837. Lemme know if it looks alright.

**Comment by rossabaker** [comment]
Old PR checklist is broken down into [a GitHub project](https://github.com/http4s/http4s/projects/3) for lingering work.  We're now publishing off the [cats branch](https://github.com/http4s/http4s/tree/cats).  I think this meta-PR has run its course.

**Pull request closed without merging**
