### PR TITLE
Update to munit 1.0.0-M6

### PR DESCRIPTION
**Pull request by armanbilge**
At this point it is quite stable and brings many improvements we could benefit from, such as async resource fixtures (thanks to @danicheg for working on that in munit core :)

### CODE REVIEW

**Review by danicheg — APPROVED** [review]
It's fine with me to adopt the new MUnit version if we would benefit from it.

**Comment by rossabaker** [comment]
This is a published dependency, via laws.  The laws are underdeveloped, rarely depended on, and would not typically be used in applications, so it's not tragic.  But this was a breaking change in a patch, and now production depends on a milestone.

**Comment by armanbilge** [comment]
Sorry, I was completely unaware of that. Why do our laws depend on munit? Typically laws depend on Discipline and not a specific test framework.

**Comment by rossabaker** [comment]
Good question.  Looks like `LawAdapter`.

**Comment by armanbilge** [comment]
Hmm. At a glance I think the Right:tm: thing to do there would have been to use the Cats Effect testkit. Not ruling out that effectful laws are tricky.

We can fix this on 1.x.

**Pull request merged**
