### PR TITLE
Make `WSClient` and friends public

### PR DESCRIPTION
**Pull request by armanbilge**
We now have implementations ready in:
- https://github.com/http4s/http4s-dom/pull/93
- https://github.com/http4s/http4s-jdk-http-client/pull/571

### CODE REVIEW

**Comment by rossabaker** [comment]
Needs the MiMa exemptions, but :+1:.

**Comment by armanbilge** [comment]
Those seem less than ideal. Like they could all-too-easily filter legit issues due to future changes :(

**Review by rossabaker — APPROVED** [review]
I don't think there's much that can be done about the broad exemptions, other than to start MiMaing against 0.23.11, which is also not ideal.

**Comment by armanbilge** [comment]
> start MiMaing against 0.23.11, which is also not ideal.

That's even more dangerous, because MiMa automatically ignore package-private stuff. So if something was public in 0.23.0 and then made package-private in 0.23.1, unless we specifically compare against 0.23.0 we could delete that method without getting any warnings.

But you are right that MiMa exemptions should be tied to specific versions e.g. these filters here should only apply when comparing to artifacts before 0.23.11. From 0.23.11 on there should be a clean slate. I do have some imagination of doing something about this at some point 😆

**Pull request merged**
