### PR TITLE
Update scaladoc links to 2.12 format

### PR DESCRIPTION
**Pull request by aeons**

### CODE REVIEW

**Comment by bfritz** [comment]
I think there's one more in `docs/src/main/tut/json.md` in the last line of the file.

**Comment by aeons** [comment]
Yes, that's another pattern that I didn't notice :)

**Comment by aeons** [comment]
Hmm, so that last link points to a method that returns a `scalaz.concurrent.Task` in 0.15 and 0.16, but an `fs2.Task` in 0.17. So this will have to be updated there as well.

**Comment by ChristopherDavenport** [comment]
Thats the fun of the merge train :train: :train2:

**Pull request merged**
