### PR TITLE
Topic/location parser

### PR DESCRIPTION
**Pull request by bryce-anderson**
We were missing a few parsers. This should be all of them, but it might be a good idea for someone else to double check.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
I'd appreciate a review on this when someone gets a chance. It should be pretty straight forward.

**Comment by rossabaker** [comment]
I've wondered periodically whether it wouldn't be helpful to move the parsers into the companion objects, though still package protected.  Seems like a better grouping of code.

**Comment by bryce-anderson** [comment]
That might be a good idea, but I think the Header.scala file is pretty congested and difficult to read as it is and could use a cleanup.

**Comment by rossabaker** [comment]
In retrospect, I wonder whether headers should have been a package.

**Pull request merged**
