### PR TITLE
Adding ipython notebook extension

### PR DESCRIPTION
**Pull request by dmvieira**

### CODE REVIEW

**Comment by aeons** [comment]
Hi, the `MimeDB.scala` file is automatically generated from data in https://github.com/jshttp/mime-db

**Comment by dmvieira** [comment]
@aeons , but it should not be maintained as code? What's the process to make this file?

**Comment by rossabaker** [comment]
There are [instructions here](https://github.com/http4s/http4s/tree/063287b0bc18e402a362dfe8c4826c803314c23c/mimedb-generator). We periodically run that and submit the result as a PR.

It will only add the one you want if it's in the IANA registry.  I don't think we have a way to add custom ones, so if it's not in that registry, we should figure that out here.

**Comment by dmvieira** [comment]
Ok, I'm solving this in another [issue](https://github.com/jshttp/mime-db/issues/176) and then we back here

**Pull request closed without merging**
