### PR TITLE
Merge `series/0.23` into `main`

### PR DESCRIPTION
**Pull request by danicheg**
As a matter of fact, the `main` hasn't been published for almost six months. If nobody minds, I'd like to draft a ~~release~~ (Arman won't like this) to unlock the use of CE-3.5.x in downstream libraries.

### CODE REVIEW

**Comment by armanbilge** [comment]
> I'd like to draft a ~release~ (Arman won't like this)

Why is that? 😂

**Comment by danicheg** [comment]
> Why is that? 😂

_release_ badly combines with `main`, you know... 😄

**Comment by armanbilge** [comment]
Oh, actually, I have one annoying thing to point out ...

In our changelog we say:

> Maintenance branches are merged before each new release. This change log is ordered chronologically, so each release contains all changes described below it.

However, we currently have some changes in 0.23 branch that have not yet been released.

https://github.com/http4s/http4s/compare/v0.23.22...series/0.23

So if we merge all of those changes into main, and do a release of main, it will actually include changes that will not be in the changelog, because they are supposed to be mentioned in an 0.23 changelog for a release that hasn't happened yet.

It's my fault since I've been doing many of the 0.23 releases and being lazy about doing 1.x releases, but probably the best way to do this is to release them at the same time, so that the changelogs are properly synchronized. So this means we need an 0.23.23 release first.

Alternatively, we could merge 0.23.22 into main, and not the extra commits that happened after that release.

Alternatively, we could say we don't care :)

**Comment by danicheg** [comment]
@armanbilge so... are you suggesting publishing `main` as it currently is and after that merging this PR?

**Comment by armanbilge** [comment]
No, we also can't release main as-is, because it is missing changes that are in 0.23.22.

We also can't release main if we merge this PR, because then it will have changes that have not yet been released in 0.23.

To remedy this situation, I'm suggesting either:

1. We merge the 0.23.22 tag into main, and release that. Then we can merge this PR with the remaining changes.

2. We release 0.23.23, then merge this PR, and release main.

Both of these options ensures that the releases from both branches are properly synchronized.

**Pull request closed without merging**
