### PR TITLE
Default redactHeadersWhen to include any header with "token"

### LINKED ISSUE #6104: Change Server and Client Logger default redactHeadersWhen to include any header with "token"
As the title says. For example for Server Logger the apply would be:
```scala
def apply[F[_]: Async](
    logHeaders: Boolean,
    logBody: Boolean,
    redactHeadersWhen: CIString => Boolean = (name: String) => Headers.SensitiveHeaders.contains(name) || name.toString.toLowerCase.contains("token"),
    logAction: Option[String => F[Unit]] = None,
)
```

Or even better create a
```scala
def defaultRedactHeadersWhen(name: CIString): Boolean =
    Headers.SensitiveHeaders.contains(name) || name.toString.toLowerCase.contains("token")
```
and then
```scala
def apply[F[_]: Async](
    logHeaders: Boolean,
    logBody: Boolean,
    redactHeadersWhen: CIString => Boolean = defaultRedactHeadersWhen,
    logAction: Option[String => F[Unit]] = None,
 )
```
I can make a PR.

### PR DESCRIPTION
**Pull request by Lasering**
Fixes #6104

### CODE REVIEW

**Review by ChristopherDavenport — APPROVED** [review]

**Comment by ChristopherDavenport** [comment]
Do we want to target this to 0.22 so we can forward it?

**Review by danicheg — COMMENTED** [review]
Since it's possible to configure which headers need to be redacted on the user side, I think it's not good to change the default behavior. Other users (who are happy with the current behavior) will need to do changes. So it seems odd a bit. But if the majority are ok with these changes, I won't make waves.

**Review by rossabaker — APPROVED** [review]
I don't generally like semantic changes that don't surface themselves via the compiler, but this is a more secure default.  I am in favor.

**Review by bplommer — APPROVED** [review]

**Comment by armanbilge** [comment]
Is it just me or seems like this should be retargeted to 0.23?

**Comment by armanbilge** [comment]
@Lasering I see you 👍 https://github.com/http4s/http4s/pull/6186#issuecomment-1222503758 ... if you don't mind re-targeting this PR at series/0.23, I will merge it and it can land in the next release :)

**Comment by Lasering** [comment]
@armanbilge I'm so sorry. I've never re-targeted a PR, and since my commits were on the main branch of my repo (which was out-of-date and not in sync with series/0.23) I thought the easiest way has to delete the main branch of my repo and push a new clean branch of series/0.23 with my commit on top. But as soon as I deleted my main branch on the upstream Github closed this PR and now it doesn't allow me to edit it to change the base branch. So I had to create a new PR. Next time I'll simply force push to the main of my repo.

**Comment by armanbilge** [comment]
@Lasering it's not a problem at all :) thanks for retargeting!

**Pull request closed without merging**
