### PR TITLE
Replace use of topic with Queue in websocket example

### PR DESCRIPTION
**Pull request by jedesah**
Topic feels like an overkill to implement an echo server. It's confusing for a new user who can't help but wonder why the use of topic is required.

### CODE REVIEW

**Comment by jedesah** [comment]
But then the question arises whether the current API for implementing a websocket endpoint is really the best we can come up with if the user is required to use a `Queue` in order to implement a simple echo server. `Queue` is generally considered something you want to avoid using if possible and is there principally to interface with callback based APIs.

I am trying to reason if `Exchange` brings anything to the table over `Process[Task, WebSocketFrame] => Process[Task, WebSocketFrame]`. Implementing an echo server or pretty much anything I can think of right now sure seems more straightforward with the last.

This is what I have in mind:

    case req@ GET -> Root / "wsecho" => WS { in =>
      in.collect{
        case Text(msg, _) => Text("You sent the server: " + msg)
      }
    }

which would involve a change from:

    def WS(exchange: Exchange[WebSocketFrame, WebSocketFrame], status: Task[Response]): Task[Response]

to:

    def WS(handler: Process[Task, WebSocketFrame] => Process[Task, WebSocketFrame], status: Task[Response]): Task[Response]

Thoughts?

**Comment by rossabaker** [comment]
:+1: on the original change.  Thinking on the signature change.

**Comment by rossabaker** [comment]
The second cliched example of websockets, after an echoserv, is a chatserv.  I'd like to consider how the proposed signature changes https://github.com/http4s/http4s_demo/blob/b8b4781aa904ec65a37f029cfb6e1adc7118837a/src/main/scala/org/http4s/example/Routes.scala#L33-L47

**Comment by bryce-anderson** [comment]
:+1: to the PR.

**Comment by bryce-anderson** [comment]
I'm open to the signature change. Maybe we can break that out into a separate issue for debate? I agree with @rossabaker, we need to test a few use cases before getting to serious.

**Pull request merged**
