### PR TITLE
Scala-3.0.0-RC1 -> Scala 3.0.0-RC2

### PR DESCRIPTION
**Pull request by rossabaker**
We've never successfully published for two Scala 3 versions, and I don't have the time or emotional bandwidth to frustrate myself trying again.  Onward to RC2.

Missing dependencies:

* [x] case-insensitive (https://github.com/typelevel/case-insensitive/pull/135)
* [x] cats-parse (https://github.com/typelevel/cats-parse/pull/190)
* [x] fs2
* [x] ip4s (2.0.0 is cursed; waiting on 2.0.1)
* [x] log4s
* [x] vault (https://github.com/typelevel/vault/pull/220)
* [x] blaze
* [x] log4cats (https://github.com/typelevel/log4cats/pull/418)
* [x] jawn-fs2
* [x] jawn
* [x] scala-xml (#4680)
* [x] keypool
* [x] circe

Nice if they're ready, but not blockers:

* [ ] play-json (https://github.com/playframework/play-json/pull/590)
* [ ] scalatags (has never published)
* [ ] twirl (has never published)
* [ ] boopickle (doesn't even compile)

### CODE REVIEW

**Comment by rossabaker** [comment]
Most of these are pretty easy to do, if anyone wants a Good First Issue on some other project:

1. Find the project on GitHub
2. If it's a cats-effect project, there are likely two branches.  Find the branch with cats-effect-2.
3. Some project support one version of Scala 3.  Some support two.  Replace the oldest with 3.0.0-RC2.
4. Run `reload` and  `++3.0.0-RC2 update`.  If anything's missing, bump it to the latest.  cats (2.5.0) and cats-effect (2.4.1) will be common.
5. Run `githubWorkflowGenerate`.  If that's not there, grep around for the version number in the CI and update.
6. Mention this ticket on the PR for visibility
7. If you get stuck, ask on http4s-dev for help.  We're familiar with all of these projects.

**Comment by rossabaker** [comment]
ip4s-2.0.0 has a hygiene issue that breaks on Scala 2.12.

**Comment by VlachJosef** [comment]
Thanks @rossabaker for clear instructions, it was really easy to follow.

**Comment by rossabaker** [comment]
Alright, core is done. That opens up the next tier. play and circe are coming, too.

**Comment by lorandszakacs** [comment]
log4cats is published for 3.0.0-RC2, `1.2.2`, and `2.0.1`

**Comment by rossabaker** [comment]
jawn-fs2 is syncing, and then I think the next wave will appear. I think that will be just play-json, which @VlachJosef took care of, and circe, which I see just got a bunch of dependencies merged this morning.  scalatags and twirl and boopickle are already excluded, and I think everything else is Java or Kotlin?

**Pull request merged**
