### PR TITLE
StaticFile.fromFile — handle empty file

### LINKED ISSUE #429: StaticFile.fromFile with empty file throws exception
e.g.

```scala
scala> val f = java.io.File.createTempFile("empty", null)
f: java.io.File = /var/folders/29/7vjbbx9d1jx1l5s_7cvkx4x80000gn/T/empty5040506928266187844.tmp

scala> org.http4s.StaticFile.fromFile(f)
java.lang.IllegalArgumentException: requirement failed: start: 0, end: 0, buffsize: 10240
	at scala.Predef$.require(Predef.scala:233)
	at org.http4s.StaticFile$.fromFile(StaticFile.scala:72)
	at org.http4s.StaticFile$.fromFile(StaticFile.scala:65)
	at org.http4s.StaticFile$.fromFile(StaticFile.scala:61)
…
```

### PR DESCRIPTION
**Pull request by drostron**
resolves #429

### CODE REVIEW

**Comment by bryce-anderson** [comment]
:+1: This looks good to me. It would be good to have a second review considering the very imperative nature of that section of code, but barring objections I'll merge this tonight.

**Comment by kryptt** [comment]
The question: "who would want to serve an empty static file?" bugs me though...

**Comment by drostron** [comment]
It at least shouldn't throw an exception resulting in a 500 right?

**Comment by kryptt** [comment]
Well, for me, the idea is you catch these things early... if it was dynamic content, sure, you should be able to send out empty bodies, but StaticFile isn't for dynamically generated contents. Personally, getting a 500 because I have an empty static file somewhere is something I would like as I am developing and doesn't really bother me. 

And a very strong argument could be made against using StaticFile for dynamically generated content, you could just wrap the file in a process, etc. there is no need to read E-Tags, or any other file metadata if the content is supposed to be fresh anyways...

I mean, I understand your position, when I was working on this file I was tempted to lax the constraint myself. I could go either way, just wanted to offer the counter argument for consideration...

**Comment by bryce-anderson** [comment]
So is there objection to merging this? While they seem pointless in this
context a zero length file is a thing.

I'm inclined to merge this.

**Pull request merged**
