### PR TITLE
Codereview changes

### PR DESCRIPTION
**Pull request by hvesalai**

### CODE REVIEW

**Comment by bryce-anderson** [comment]
:+1:  from me. 
The changes to the writer are defiantly a good change.
I'm not sure about the performance difference between the string vs char encoding but I doubt its much of a difference and this seems better on the eyes so lets go with it.

I'll leave this up for a bit in case someone else wants to offer comments.

Thanks @hvesalai for the code review and PR!

**Comment by rossabaker** [comment]
:+1: 

Any reason this can't go onto 0.11.3?  Except for privates, which we ignore, it looks bincompat.

**Comment by hvesalai** [comment]
Added a new commit to the pull-request to remove the support for "Idenitity" Transfer-Encoding. There is no such thing.

**Comment by rossabaker** [comment]
The identity encoding surprised me.  It turns out it was there, but was [removed in errata](http://skrb.org/ietf/http_errata.html#identity).

**Comment by rossabaker** [comment]
16d71030c6b2bd04785493fc38ad9c3c9234db6b was cherry-picked into 0.11.3.  The rest merged as originally targeted.

**Pull request merged**
