### PR TITLE
Get logo in navbar and favicon

### PR DESCRIPTION
**Pull request by rossabaker**
I am not a Front End Person™, but it works for me.

### CODE REVIEW

**Comment by aeons** [comment]
That is a very large favicon.

Maybe generating a smaller one from the svg with something like http://realfavicongenerator.net/ ?

**Comment by refried** [comment]
Does having a big favico cause a problem?  eg does it not scale properly?  I figured detailed icons for hidpi scenarios was the way of the future!

**Comment by rossabaker** [comment]
There are six sizes in that favicon.ico.  I tried several svg-to-ico translators, and this is the first that made one that worked at all in my browser (OSX+Chrome).  I couldn't find a simple guide to the favicon.ico format, so I _guess_ it's right?

**Comment by rossabaker** [comment]
Merging, but interested in reports of where it goes wrong.  The easiest way to test this is to land it!

**Comment by refried** [comment]
👍

**Pull request merged**
