### PR TITLE
Update Retry-After to follow the coding conventions

### PR DESCRIPTION
**Pull request by cquiroz**
Small update to `Retry-After` to follow the conventions, removing the use of `FiniteDuration` for `Long` instead

### CODE REVIEW

**Comment by cquiroz** [comment]
Do you mean by the existence of sub-seconds on `Instant`

**Comment by rossabaker** [comment]
Yes, exactly.  Just like the existence of subseconds on `Duration`.

**Comment by rossabaker** [comment]
This is affected by #1287

**Comment by rossabaker** [comment]
When #1287 gets approved, I'll backport this on top of that.

**Comment by rossabaker** [comment]
I'm just folding this into #1287.

**Pull request closed without merging**
