### PR TITLE
Fixed laws-check in RefererSpec.

### PR DESCRIPTION
**Pull request by heksesang**

### CODE REVIEW

**Comment by aeons** [comment]
Looks like it needs an import to build.

**Comment by rossabaker** [comment]
We discussed on Gitter, and I didn't take time to look at Travis. 😬

**Comment by rossabaker** [comment]
This is actually kind of tricky.  It needs an `Arbitrary[Referer]` (which I went ahead an added), which comes from an `Arbitrary[Uri]`, which doesn't round trip, as noted in https://github.com/http4s/http4s/issues/1651.  Now it should compile but the test is going to fail until we fix that underlying issue with the Uri.

**Comment by armanbilge** [comment]
Fork is gone.

**Pull request closed without merging**
