### PR TITLE
add load-test module

### PR DESCRIPTION
**Pull request by julien-truffaut**
load test can be run with:
```
sbt
project load-test
gatling:testOnly org.http4s.load.DemoSimulation
```

html report is output at load-test/target/gatling

### CODE REVIEW

**Comment by bryce-anderson** [comment]
This appears to be loading the demo? I expect that to change to a local server in the future. The demo is running on an EC2 micro instance so the performance will be very stochastic based on the other processes running on the physical hardware.

**Comment by julien-truffaut** [comment]
yes it just sending a get request to the index of the demo. We can change the url target and add more sophisticated cases like url form, json, etc but I just wanted to show the pattern.

**Comment by bryce-anderson** [comment]
Wonderful. I'm excited to get this in place. As a side note (related only
by the need to spin up servers), we've been talking about it for a while,
but we also need to start spinning up live servers for testing purposes too
to avoid issues like PR #224. I suspect there will be a bit of overlap with
your work here.

**Comment by bryce-anderson** [comment]
Where does this PR stand? I would hate for good work to get stale.

**Comment by julien-truffaut** [comment]
Basically this PR simply add the basic architecture for load testing but we will have to write more complex scenario to be useful. The main issue is that we need some demo to test against it.

**Comment by bryce-anderson** [comment]
Does that need to be in this PR? If so, we should get it done so this can get merged. If not, we should merge this and open a new ticket for 'More intense and diverse load test routes' or something like it. That would be a really good 'help wanted' issue that someone could use to get familiar with http4s while making a good contribution.

**Comment by julien-truffaut** [comment]
I would prefer to merge this PR and then create another ticket as you suggested. I wrote a few gatling scenario so I am ready to help but I am pretty busy atm

**Comment by bryce-anderson** [comment]
Alright, lets do that. @rossabaker: object soon if you don't want this merged. I'll likely take care of it this afternoon.

**Pull request merged**
