### PR TITLE
Cookies on Request

### PR DESCRIPTION
**Pull request by cquiroz**
This PR contains methods to easily add `Cookies` to `Request` isomorphic to the ones on `Response`

I thought about adding documentation but couldn't find a good place.

### CODE REVIEW

**Comment by cquiroz** [comment]
It is interesting that travis fails in one specific scala/scalaz combination but the error is on building the docs:

```
[error] (run-main-6) java.lang.Exception: Tut execution failed.
java.lang.Exception: Tut execution failed.
	at tut.TutMain$$anonfun$runl$2$$anonfun$apply$10.apply(Tut.scala:107)
	at tut.TutMain$$anonfun$runl$2$$anonfun$apply$10.apply(Tut.scala:105)
	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
```

Any ideas?

**Comment by rossabaker** [comment]
tut only runs on that one combination to generate the site.

The error is a 403, which GitHub uses to rate limit.  This is a cause of intermittent build failures.  We should look into replacing that tut with an API that's predictable.  Perhaps launch our own server in the tut.

**Comment by cquiroz** [comment]
So restarting the travis build may fix it? Could you try that?

**Comment by rossabaker** [comment]
I did, and we're still in the GitHub naughty bin.  I opened #817 for a fix for that.

**Comment by rossabaker** [comment]
I guess this is binary compatible and could go out in v0.15 to get it in your hands sooner.  I'll do the cherry pick dance.

**Comment by rossabaker** [comment]
Cherry-picked and remastered.

**Pull request closed without merging**
