### PR TITLE
Forward port QueryParam codec instances from 0.16 master

### PR DESCRIPTION
**Pull request by tpolecat**
- instances and tests from #1301 
- doc fix from #1303 
- remove method deprecated in #1301

### CODE REVIEW

**Comment by tpolecat** [comment]
I have no sense of your merge strategy for any of this. There are a lot of versions flying around. This isn't a ton of work so I can do it again later if needed. 

If this is the grand unification branch I'm not clear on what 0.18.x is … do I need to pull these commits forward?

**Comment by rossabaker** [comment]
release-0.16.x -> master -> release-0.18.x.  The second of those will be easy, because it's all cats.  We usually just silently do that, and PR the tricky ones.

I think we have the pieces we need here.  I normally wait for a second sign-off, but this was pretty uncontroversial on 0.16.  I'm just going to do it.

**Comment by tpolecat** [comment]
Muy bien.

**Comment by rossabaker** [comment]
Oh, well, one comment: I don't like to be too aggressive about removing deprecation, because I'm continually surprised how old people upgrade from, and because they're effectively typesafe migration guides.  I tend to purge deprecation when it becomes hard to drag around, and not after some arbitrary number of releases.  I'd argue for reverting 66acc4a.

**Comment by tpolecat** [comment]
As you wish.

**Pull request merged**
