### PR TITLE
Retry request without cleaning body

### LINKED ISSUE #1999: Client's Retry with empty body
I found strange code, is this bug or feature?
Why new attempt occurs with empty body in case of failure?

https://github.com/http4s/http4s/blob/9655331c743ca91326c94bd98730f2a3f382415a/client/src/main/scala/org/http4s/client/middleware/Retry.scala#L62

### PR DESCRIPTION
**Pull request by maxkorolev**
fix #1999

### CODE REVIEW

**Comment by jcranky** [comment]
Would this deserve a test?

**Comment by rossabaker** [comment]
:+1: to the fix.

:+1: to a test.  @maxkorolev, would you be able to add that?  If not, someone else can pick it up.  Thanks!

**Comment by maxkorolev** [comment]
I didn't get how to fix such build failure, it doesn't depend on my commits.
It seems like regular failure for these tests, I see a lot of Boom exceptions all over the place

**Comment by rossabaker** [comment]
We test some error handling cases, and we haven't muted the loggers in tests, so we end up with some stack traces during a successful run.

The build error is [here](https://travis-ci.org/http4s/http4s/jobs/417131452#L4982).  We enforce scalafmt, so running `test:scalafmt` will make it pass.  `sbt ci` will run all the tests the build runs, but take longer and requires a hugo installation for the docs.

**Comment by maxkorolev** [comment]
Done)

**Comment by rossabaker** [comment]
I like the change, but I'd still like a test.  If @maxkorolev doesn't have time, I'd be happy to write one and append it to this PR.

**Comment by maxkorolev** [comment]
Hm, what kind of new tests do you want me to write? Maybe add some effects to request?
That would be great if you wrote one) Thank you

**Comment by jmcardon** [comment]
:+1: to a test

**Comment by rossabaker** [comment]
I wish scalafmt on compile weren't prohibitively slow.

**Pull request merged**
