### PR TITLE
Close some resources in tests

### PR DESCRIPTION
**Pull request by danicheg**
A minor thing, most for fixing warnings from linter in the $IDE. 
Introduced in this PR `AutoCloseableResource.resource` perhaps should be in the JVM module for the `0.23` series. I'll port it in case of merging this PR.

### CODE REVIEW

**Comment by armanbilge** [comment]
This looks very similar to `Resource.fromAutoCloseable`: https://typelevel.org/cats-effect/api/2.x/cats/effect/Resource$.html#fromAutoCloseable[F[_],A%3C:AutoCloseable](acquire:F[A])(implicitF:cats.effect.Sync[F]):cats.effect.Resource[F,A]

**Comment by danicheg** [comment]
@armanbilge yep. By and large for cases not dealing with `F[_]` and CE `Resourse`. I've strived to don't refactor tests much, keeping their initial semantic.

**Comment by armanbilge** [comment]
Thanks for explaining. IMHO I think it would be more idiomatic to make use of `Resource.fromAutoCloseable` and `ResourceFixture` from munit-cats-effect. But, whatever works :)

**Review by rossabaker — APPROVED** [review]
I'm not sure what the ResourceFixture looks like in these untracked effects.  Open to that as a subsequent refactor, but this looks good.

**Comment by armanbilge** [comment]
I'm pretty sure `ResourceFixture` works the same for any kind of test, since it's wiring CE `Resource` with munit's existing fixture system (which doesn't know anything about CE).

**Comment by danicheg** [comment]
@armanbilge using `ResourceFixture` or CE `Resource` is looking promising. Besides, it would mean solid refactoring of tests, which I've tried to get around. And I agree with Ross, that one may do this subsequently. I left a comment about it for hereafter investigators.

**Review by armanbilge — APPROVED** [review]

**Pull request merged**
