### PR TITLE
Merge 0.23.18 -> main

### PR DESCRIPTION
**Pull request by rossabaker**
My strategy of hoping someone else would do the nasty Ember merge has failed.  I want to keep 1.0 at parity with 0.23.

### CODE REVIEW

**Comment by rossabaker** [comment]
The Ember Encoder in particular needs a review on this one.

**Comment by rossabaker** [comment]
I don't know what keeps marking codecov as offtopic.  Do we want it or not?  I don't really care either way.

**Comment by armanbilge** [comment]
> I don't know what keeps marking codecov as offtopic.

Oh that's me doing that 😛 I thought we decided no coverage for PRs? Anyway I feel like big status comments get in the way.

Prefixing a branch with `pr/` e.g .`pr/merge-0.23.18` would prevent the double CI job (and the coverage comment).

**Review by armanbilge — APPROVED** [review]
Looked through ember since I think a lot of that was my work on 0.23. Seems fine, but also leaning on CI here 😅

**Pull request merged**
