### PR TITLE
Upgrade to circe-0.3.0.

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by bryce-anderson** [comment]
circe-0.3.0 should pull shapeless-2.2.5 in with it, which is fine but out of step with shapeless-2.1.0 pulled in by parboiled2-2.1.0 we are explicitly depending on. It looks like parboiled2-2.1.1 depends on shapeless-2.2.5 so maybe we should bump it too.

**Comment by rossabaker** [comment]
parboiled2-2.1.1 is not yet published for 2.10, which is the one whose shapeless dependency causes pain.  I'll bump the explicit shapeless, and if sirthias/parboiled2#160 gets addressed, then we can upgrade that, too.

**Comment by bryce-anderson** [comment]
Bummer. I just looked at the repo tags and assumed. We all know what they
say about assume...

**Comment by bryce-anderson** [comment]
Is this ready? It looks good to me unless you want to wait and see what happens on the parboiled2 issue.

**Comment by rossabaker** [comment]
shapeless-2.3 is in RC status now, so I suspect we'll be doing this dance soon again anyway.  Merging as is.

**Pull request merged**
