### PR TITLE
Permit recycling of requests with bodies.

### PR DESCRIPTION
**Pull request by rossabaker**
For fear of hitting a stale connection after consuming part of the body, we made no attempt to recycle requests with bodies. With this change, we can verifying the connection health by writing the header before consuming any portion of the body.

### CODE REVIEW

**Comment by rossabaker** [comment]
This is #467, retargeted for v0.11.2.

**Comment by bryce-anderson** [comment]
This looks good to me. Perhaps we should make a few of the client tests flush to make sure it doesn't break in the future?

**Comment by rossabaker** [comment]
Yeah.  I hadn't thought about how to explicity test it, but flipping a few of those falses to trues should protect us from total catastrophe.

**Comment by bryce-anderson** [comment]
:+1: 
@rossabaker, do the honors if you're happy with it.

**Pull request merged**
