### PR TITLE
Add documentation for creating a server

### PR DESCRIPTION
**Pull request by agustafson**

### CODE REVIEW

**Comment by joescii** [comment]
I'm not far enough along with *http4s* to appreciate the content you've added, tbh. 

For me, the biggest difficult I experienced was finding [`ServerApp`](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/ServerApp.scala). I would like to see a snippet of that on the getting started. I'll gladly open another PR for it.

**Comment by rossabaker** [comment]
Thanks for the contribution!  This is helpful.

One comment: `HttpService` comes with an `orElse`.  Instead of introducing `PartialFunction`, would it be better to remain in the realm of `HttpService` through the tut?

**Comment by agustafson** [comment]
Yep @joescii I agree that ServerApp needs better docs and it was included in this PR. I'll break it out under its own heading to highlight it though.
That's a good shout @rossabaker - I'll update the PR to use HttpService instead.

**Comment by agustafson** [comment]
Updated to use `HttpService` instead of `PartialFunction` @rossabaker, and have added separate heading for using `ServerApp`

**Comment by joescii** [comment]
Nice! I like the separate section for `ServerApp`. I glossed right over it the first time. 👍

**Comment by rossabaker** [comment]
Looks good to me.  Thank you so much!

**Comment by agustafson** [comment]
No worries @rossabaker. It's a great client and server so hopefully more docs will make it more approachable for people 😀

**Comment by rossabaker** [comment]
And now that I've hit the big green button, I really should have merged this into release-0.14.x so both docs could benefit.  Oops.

**Pull request merged**
