### PR TITLE
Release v0.21.32

### PR DESCRIPTION
**Pull request by rossabaker**
It pays the bills.

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Are we going to need to adjust the build to get CI release working?

**Comment by rossabaker** [comment]
Oh, crap, probably.  We just need to set the hostname to S01, right?

**Comment by armanbilge** [comment]
Yeah we need to set `sonatypeCredentialHost := "s01.oss.sonatype.org"` for all the projects (`ThisBuild` doesn't work) so it would be good to plop that in the auto-plugin.

Does 0.21 have scalafixes in here? We might butt heads with https://github.com/http4s/http4s/issues/6032.

**Comment by armanbilge** [comment]
Yeesh, it seems it does. So we could also copy-paste the stuff from https://github.com/typelevel/sbt-typelevel/pull/150 as well....

**Comment by rossabaker** [comment]
I think that credential host needed to be on the root project because of the bundling.

**Comment by armanbilge** [comment]
Oops, yes it does. That's why I suggested the auto-plugin, since it would do that automatically.

**Comment by armanbilge** [comment]
Actually sbt-sonatype 3.9.11 was just released with my fix.

**Comment by rossabaker** [comment]
I tried putting it there, and it didn't trigger.  I guess I'll publish this one manually, and can clean up in case there's another 0.21.  Hopefully not, but.

**Pull request merged**
