### PR TITLE
Add `EntityDecoder[EventStream]`

### PR DESCRIPTION
**Pull request by armanbilge**
All the pieces were already here, including a test, so not sure why this wasn't already exposed.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
I thought there was a reason, but I didn't document it and don't remember it.

**Comment by armanbilge** [comment]
@rossabaker I found some discussion on this in https://github.com/http4s/http4s/issues/619, I still need to digest it but does anything there jog your memory?

**Comment by rossabaker** [comment]
I guess it was having a decoder that produced the prehistoric equivalent of `F[Stream[F, Event]]` was distasteful?  You probably want to `Stream.eval` the decoded result from this?

**Comment by armanbilge** [comment]
Or [`Stream.force`](https://github.com/typelevel/fs2/blob/ff9d758ae61cb19ad4d6f5cde4d0b236efab8157/core/shared/src/main/scala/fs2/Stream.scala#L3499) maybe? I did notice that, and it's slightly awkward, but I can't see why it's that big a deal.

In theory we could add a special syntax for it roundabouts here:
https://github.com/http4s/http4s/blob/e94c9d48fec00758d70afa59107408463d89e818/core/shared/src/main/scala/org/http4s/Media.scala#L67

e.g.
```scala
final def asStream[A](implicit F: MonadThrow[F], decoder: EntityDecoder[F, Stream[F, A]]): Stream[F, A] =
  Stream.force(as[A])
```

Otherwise not really sure what we could do about it.

**Comment by armanbilge** [comment]
> I thought there was a reason, but I didn't document it and don't remember it.

Well, we figured out why 😕 
- https://github.com/http4s/http4s/issues/6694

**Pull request merged**
