### PR TITLE
Use sbt-coursier and cache its dependencies

### PR DESCRIPTION
**Pull request by rossabaker**
Cuts our build times by about 150 seconds per cross build.

### CODE REVIEW

**Comment by refried** [comment]
Cool. :+1:

**Comment by bryce-anderson** [comment]
Looks good to me, though I've not seen coursier. What does it do better than the stock dependency resolver?

**Comment by rossabaker** [comment]
https://github.com/alexarchambault/coursier#why

tl;dr it drastically cuts the time of `sbt update`, which is especially great when you're switching branches and reloading the build.

**Comment by rossabaker** [comment]
And not a reason we should use it, but in a neat bit of symmetry, [it uses us](https://github.com/alexarchambault/coursier/search?utf8=%E2%9C%93&q=http4s).

**Comment by refried** [comment]
Very sad halfway through a flight when SBT decides to evict your SNAPSHOTs :-/

**Comment by bryce-anderson** [comment]
Wait, it uses http4s-blaze?!? I'm totally sold.

**Comment by rossabaker** [comment]
I'm not entirely sure what it's used for yet, but it made me smile to find it. :)

**Pull request merged**
