### PR TITLE
Unify json4s modules with an implicit JsonMethods parameter.

### PR DESCRIPTION
**Pull request by rossabaker**
This reduces the surface area of our integration and cleans up
duplicate code that's about to get bigger.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
So the current chatter in #http4s suggests we are going to be dropping json4s-native and just using json4s-jackson. If that is the case, I think this PR might be moot.

Besides that little wrinkle, I don't know how I feel about this PR. It reduces package complexity but we are starting to get a rabbit hole with regard to what implicits need to be in scope for things to compile.

__Bottom line:__ I'm thinking we should just support json4s-jackson.

**Comment by rossabaker** [comment]
An alternative, should we continue to support both, would be a protected
JsonMethods member and *gasp* inheritance.  But I'm leaning toward just
dropping the native.

**Comment by rossabaker** [comment]
Before I pull the trigger, let's put this one on ice and see whether there's community outrage at json4s/json4s#199.

**Comment by rossabaker** [comment]
It appears there may be interest in maintaining json4s-native upstream.  I scratched the DRY itch on #175.  I'm going to withdraw this one.

**Pull request closed without merging**
