### PR TITLE
Add Hash and BoundedEnumerable instances for HttpVersion

### PR DESCRIPTION
**Pull request by ammarc**
For https://github.com/http4s/http4s/issues/3869

Test had to be adapted in order to fix the following compile error:
```
ambiguous implicit values:
 both value http4sHttpOrderForVersion in object HttpVersion of type cats.Order[org.http4s.HttpVersion]
 and value http4sHttpHashForVersion in object HttpVersion of type cats.Hash[org.http4s.HttpVersion]
 match expected type cats.kernel.Eq[org.http4s.HttpVersion]
  checkAll("HttpVersion", OrderTests[HttpVersion].order)
```

Do let me know if there's a better way to fix this.

### CODE REVIEW

**Comment by rossabaker** [comment]
Thanks for volunteering!

The problem is that `Hash` and `Order` both extend `Eq`, so now we have two implicit `Eq` instances at the same priority, when we want exactly one.  I didn't think about this until now.  The problem we're having in the tests will also happen downstream, so we ought to fix this.

One way around it is to make one instance that has all the Cats instances.  Case-insensitive has an [example](https://github.com/typelevel/case-insensitive/blob/1e256d6d96a6812c437149c58e02b12ab96ce018/core/src/main/scala/org/typelevel/ci/CIString.scala#L71).  If you copie and paste from that to get all the methods, this can't be a `Monoid`, but it could be a `BoundedEnumerable` instead of a `LowerBounded`.

We would need to remove the `implicit` keyword from the existing instances, and should add a `@deprecated` annotation.  This is all binary compatible, so the deprecation version could be "0.21.12" and we need to target series/0.21.

Whew, that turned into a lot.  If not all of that makes sense, please ask! :smile:

**Comment by ammarc** [comment]
Thanks for the explanation, Ross.

Why do we need to add `BoundedEnumerable`? Don't we only need `Order`, `Hash` and `Show`?

**Comment by ammarc** [comment]
> we need to target series/0.21
Do you mean I need to make this PR to `http4s:series/0.21` iso. `http4s:main`?

**Review by rossabaker — COMMENTED** [review]
Nicely done.  One more thing.  Whenever we add an instance, we like to check its laws.  So in `HttpVersionSpec`, we should add:

```scala
  checkAll("HttpVersion", HashTests[HttpVersion].hash)
  checkAll("HttpVersion", BoundedEnumerableTests[HttpVersion].boundedEnumerable)
```

And with that, you should see a failing test on `BoundedEnumerable`.  1.0, 1.1, and 2.0 are the common ones, but there are actually 100 valid ones.

I know this is more than you signed up for, and really appreciate the work on this!

**Review by rossabaker — APPROVED** [review]
Great work!

**Comment by rossabaker** [comment]
CI didn't run due to #3916, but I verified everything locally.

**Pull request merged**
