### PR TITLE
WIP Don't merge. Scala.js compilation

### PR DESCRIPTION
**Pull request by cquiroz**
I'm reopening this track though we are still a bit far away from getting a version that would link (It compiles though). This effectively reopens #1412 

Some things needed to get it to work:
- [x] Merge #1770 
- [ ] Remove reflection from headers #1143 
- [x] Bring scala-js#3267 to fix parboiled issues
- [x] Implement any missing api on the scala.js side
- [x] Apparently there is a missing method on `java.time`

Once this is complete we can do the actual client. Perhaps [RosHTTP](https://github.com/hmil/RosHTTP) is a good starting point

/cc @oyvindberg @bpholt

### CODE REVIEW

**Comment by oyvindberg** [comment]
Yes yes, awesome, we still need to make this happen! :)

AFAIR i had a handful of smaller tasks in my branch which we should still do as prep work for this, including removing reflection, fixing a few failing tests, documenting platform differences, and so on. I'll try to document this somewhere. Do you think we could open a github project for this so we can create some issues for it?

Meanwhile i have been rebasing my branch at https://github.com/oyvindberg/http4s , though it's a month old now again, pff. At least it links, so you can run the tests there.

About the client, it's an interesting question we should discuss! :) First of all, perhaps RosHTTP is perfect. I haven't tried it, but will make sure to have a look a bit later.

The way I have thought about it so far is that I'm not sure that it necessarily makes sense to have exactly the same API for jvm/js, and even frontend/backend js. As long as you end up with a `Client`, we can share the interesting code from there on.

To that end i started to sketch a solution based on `fetch`, where the user provides their own native/polyfilled instance of fetch, and we take it from there. Feel free to have a look at the `fetch-client` folder in my repo, though be advised that it's far from done. For that very reason I'm also not very committed to that approach.

**Comment by cquiroz** [comment]
Could you make PRs to this PR with your bits to start patching the missing bits? In particular, I think you had fixed the `parboiled` issues, or does it require a `scala.js` update?

I'll do the same with #1170 
I want to suggest that whenever we do a patch that needs an update on `master` like for #1170 we squash the commit into one and mark it in the commit message, e.g. `Remove: ..` So we know that commit should be removed at some moment

about the client, I suggested `RosHTTP` as it's the only one I've seen with `scala.js` support but your solution based on `fetch` seems as good.

**Comment by rossabaker** [comment]
What problems is parboiled causing?

**Comment by cquiroz** [comment]
@oyvindberg  I took some of the code in your branch to incorporate it into the PR

**Comment by cquiroz** [comment]
This is now rebased onto master, it compiles fine but the tests (which at some moment ran) cannot link in .js anymore

There is quite a bit of work still for this, being the most critical the use of reflection (in HttpHeaderParser) issue

**Comment by rossabaker** [comment]
Accomplished via #4938

**Pull request closed without merging**
