### PR TITLE
Port to scalaz-7.2.

### LINKED ISSUE #499: Scalaz: 7.1, 7.2, or both?
functional-streams-for-scala/fs2#519 may soon be bringing us a Scalaz 7.2 port of scalaz-stream.  This is a moot point after fs2, but we've had questions about this on Gitter.

Options for us:
1) Stay the course on Scalaz 7.1 until fs2 is released and we've resolved #390.
2) Upgrade to Scalaz 7.2 and leave 7.1 behind.
3) Branch and support both versions of Scalaz.

The third is palatable to me only if Travis CI can carry most of the work.  I don't have a strong opinion on the first two options, though different outcomes to #390 would tilt my opinion one direction or the other.

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #499.

The changes to NonEmptyList answer a question that I'm not sure
any of us had.  We subsume the original `NonEmptyList`, based on
`scala.List`, and add a few more methods I always wished it had.

Known issues:
- [x] specs2 for scalaz-7.2 doesn't work with scalaz-stream-0.8a.
- [x] specs2 for scalaz-7.2 uses incompatible scalacheck from scalaz-scalacheck-binding.
- [x] argonaut has no scalaz-7.2 release yet.

### CODE REVIEW

**Comment by rossabaker** [comment]
This is obviously broken in its current state, but I wanted to get feedback on the approach to the NonEmptyList problem, which is the big change necessary in this port.

**Comment by bryce-anderson** [comment]
So the take-home here is that we copy the `NonEmptyList` from scalaz 7.1 to the http4s package? Fair enough: I like it better than switching everything to `IList`.

**Comment by rossabaker** [comment]
Yes.  7.1's `NonEmptyList` was in line with our philosophy: safe, expressive types without straying from the standard library where the standard library is adequate.  Downgrading to `List` is a loss of safety and expressivity, and scalaz 7.2's `NonEmptyList` required quite a bit of syntax to get anything done.  We were all happy 7.1 `NonEmptyList` users.

`cats.data.NonEmptyList` and `dogs.Nel` are both worth a look in the future, but not as long as we're tied to Scalaz.

**Comment by rossabaker** [comment]
I had to drop argonaut support.  To get it back, we need:
* An argonaut_2.10-6.2-SNAPSHOT.
* An updated jawn-argonaut based on 6.2.

**Comment by refried** [comment]
It’s a shame they binary-changed NonEmptyList, given that it was lawful, instead of adding a new NonEmptyIList or something.  (Don’t mind me. :))

**Comment by rossabaker** [comment]
I agree.  I get why people are excited about IList, but it would have been preferable to be excited about it under a new name.  Alas.

**Comment by rossabaker** [comment]
There is still a lot of deprecatia on this branch, but I'm backing off fixing that with so many other PRs in flight.  I do intend to clean those up once this lands.

**Comment by rossabaker** [comment]
We need a jawn-argonaut to get this across the finish line.  I've opened a discussion at non/jawn#49.

**Comment by rossabaker** [comment]
That jawn-argonaut is small enough, we can make our own until one exists upstream.

**Comment by bryce-anderson** [comment]
Is this in a 'merge-me' state? It looks good to me but its been a bit since I reviewed most of it so I'd suggest waiting for one more :+1: before merging. If needed I can take a fresh look later.

For me scalaz-7.2 is a downer but I don't see the community forking 7.1 and keeping it stable (that would be lame for an entirely different set of reasons...) so this feels like the only real option other than stagnating, at least for the time being.

**Comment by rossabaker** [comment]
It's ready. The headline is the introduction of our own NEL. The new bit is the temporary jawn argonaut facade.

We might label this as 0.14, in case people are already tied to 0.13. In that case, I'd want to release 0.13 soon. I don't want to maintain two.

**Comment by bryce-anderson** [comment]
That doesn't seem like a bad idea to do a 0.13.0 release, merge this and release 0.14.0 soon after.

**Comment by rossabaker** [comment]
Pushed as 0.14.x, which will become master after 0.13.x is released.

**Pull request closed without merging**
