### PR TITLE
The build refactor begins

### PR DESCRIPTION
**Pull request by rossabaker**
* Use sbt-rig.  We'll be able to release directly from Travis by tagging (#806).
* Make scalaz-7.2 the default, so `makeSite` works out of the box.
* Gets examples and tuts fully on Scalaz 7.2. (#829)
* Add `validate` alias to run tests, build the tuts, and run MiMa.
* Add compatibility layer for 7.1 so we don't have to opt out of warnings to build 7.2.
* Update our developers list to contain all new committers.

### CODE REVIEW

**Comment by rossabaker** [comment]
I realize that this is going to cause an unholy merge into the cats branch.  The code has already been made to work on cats, and the strategy will be "keep what's on cats" basically everywhere but parboiled2.  I will bear the pain.

**Comment by cquiroz** [comment]
Would you include scala.js preparation work in this work, perhaps it makes sense to do it later once this pr is ready

**Comment by rossabaker** [comment]
I think scala.js work would follow this.  It'll give us a cleaner foundation to start that work on.

**Comment by cquiroz** [comment]
Nice, so now scalaz 7.2 is the default and 7.1 legacy? I wonder if the compatibility layer can include `cats`

**Comment by rossabaker** [comment]
The only way to bury cats with this technique would be through type aliases, which would affect docs and compiler errors.  This trick only works because the imports don't change.

**Pull request merged**
