### PR TITLE
Make trailing slash insignificant in service prefixes on servlet containers.

### LINKED ISSUE #215: JettyBuilder gives 404 where BlazeBuilder gives 200?
With http4s 0.6.0 and rho 0.3.0, given:
```
import org.http4s.rho._
import org.http4s.server.jetty.JettyBuilder
 
object Main extends App {
  val rhoService = new RhoService {
    GET / "incident" / 'incidentNum |>> { id: String => Ok(s"Incident $id: Joe did it.") }
  }
 
  JettyBuilder
    .mountService(rhoService.toService)
    .bindLocal(8080)
    .start
    .run
}
```

`$ curl http://localhost:8080/incident/3`
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /incident/3. Reason:
<pre>    Not Found</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

Replacing JettyBuilder with BlazeBuilder:
`Incident 3: Joe did it.`

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #215..

### CODE REVIEW

**Comment by refried** [comment]
:+1:

**Comment by bryce-anderson** [comment]
:+1:

**Comment by rossabaker** [comment]
Now that I've gone and pointed this at master, should I have targeted a bugfix release?

**Comment by bryce-anderson** [comment]
I've merged this into the ```topic/0.6.2``` branch in prep for a bugfix release.

**Pull request closed without merging**
