### PR TITLE
Remove some unneeded schedulers

### PR DESCRIPTION
**Pull request by aeons**
`Stream` doesn't have `awakeEvery` directly, until https://github.com/functional-streams-for-scala/fs2/issues/1100

### CODE REVIEW

**Comment by aeons** [comment]
Is the failing test here wrong?

```scala
"clean up resources of the loser" in {
  val clean = new AtomicBoolean(false)
  val service = HttpService[IO] {
    case _ =>
      for {
        resp <- IO.sleep(2.seconds) *> NoContent()
        _ <- IO(clean.set(true))
      } yield resp
  }
  val timeoutService = Timeout(1.millis)(service)
  checkStatus(timeoutService.orNotFound(Request[IO]()), InternalServerError)
  // Give the losing response enough time to finish
  clean.get must beTrue.eventually
}
```

Using the new cancelability of cats effect, the losing side should be cancelled, right? So any cleanup should be captured in something else, like a stream.

**Comment by rossabaker** [comment]
Yeah, we can do better now by making that response trigger the flag on cancelation and be sure that gets called. That would be true on 0.18, even.

**Comment by aeons** [comment]
I'll retarget 0.18 and take a stab at improving tests.

**Comment by rossabaker** [comment]
Much of this breaks bincompat with different implicit parameters, so the whole thing can't be retargeted to release-0.18.x.  But I think the test can be improved in 0.18.x.  I should have done that when I redid the timeout middleware.

**Comment by aeons** [comment]
I'll close this and reopen in two different PRs.

**Pull request closed without merging**
