### PR TITLE
Make code slightly more readable

### PR DESCRIPTION
**Pull request by jcranky**
Sorry for such PR, but I was having a hard time reading that code... :)

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Ugh, I  mean I guess scalafmt doesn't like it, so you'll have to play around to make it readable within acceptable scalafmt. Sorry. :(

**Comment by jcranky** [comment]
@ChristopherDavenport :'( I'll have a look if this is easily fixable

**Comment by rossabaker** [comment]
You can turn scalafmt off for a section, but this is a weird place to do it.

Conjecture: if a function requires newlines, maybe it's doing too much.

**Comment by jcranky** [comment]
> Conjecture: if a function requires newlines, maybe it's doing too much.

Good point, I'll consider a different strategy :)

**Comment by jcranky** [comment]
closing in favor of https://github.com/http4s/http4s/pull/1696

**Pull request closed without merging**
