### PR TITLE
[WIP] add backends doc page

### PR DESCRIPTION
**Pull request by Daenyth**
Ref #3011

This is a WIP PR - I will be rebasing it as I go

Anyone watching, feel free to comment/commit/PR-to-this-branch additional lines/details

This is handy: https://www.tablesgenerator.com/markdown_tables

### CODE REVIEW

**Comment by rossabaker** [comment]
Nice.  This page is long overdue.

I might split up client and server, as we could start to talk about more attributes for each.  Things like client proxy support, HTTP/2 support, constraints required. #3276 is already starting this process.  I'm afraid the table would get too wide if we cram client and server together.

**Review by rossabaker — APPROVED** [review]
Is there a good reason not to integrate this and continue to iterate on it?  Incomplete but correct docs are better than no docs.

**Comment by Daenyth** [comment]
@rossabaker Merge, I'd say. I don't have a ton of time to keep going, and having *something* will make it easier for the community to perform drive-by contributions

**Comment by rossabaker** [comment]
All of this is true in 0.21, so I'm going to do the cherry-pick dance.

**Comment by rossabaker** [comment]
Cherry-picked. And I learned how to add co-authors in magit! :tada:

**Comment by LeifW** [comment]
Things like `:white_check_mark:` look nice on the GitHub markdown, but they're not rendered on the actual site: 
https://http4s.org/v1.0/integrations/
Also, my understanding was that Blaze was non-blocking?

**Pull request closed without merging**
