### PR TITLE
Remove deprecated `CSRF.SHA1ByteLen`

### PR DESCRIPTION
**Pull request by danicheg**
That's a too old thing, so let's clean up.

### CODE REVIEW

**Comment by armanbilge** [comment]
Mild 👎 no matter how old or deprecated, it's not nice to break bincompat on a stable branch IMO. I guess a source-breaking package-private could be ok.

**Comment by danicheg** [comment]
@armanbilge I tend to agree with your objection in the general case, but I believe that `val` is totally unused. It doesn't hold any functionality. Consequently, I really don't see evil in this clean-up. But the decision of accepting PR is up to you 👍🏻

**Comment by rossabaker** [comment]
We probably should have cleaned this one up before 0.22 or 0.23, but I'd leave it for main.

**Comment by danicheg** [comment]
Ok then, I'll reopen this with targeting to main.

**Pull request closed without merging**
