### PR TITLE
Internalize parboiled2 to decouple from shapeless

### PR DESCRIPTION
**Pull request by rossabaker**
Internalizes an implementation of parboiled2, along with a minimal hlist implementation to support it, to replace our parboiled2 dependency.  This significantly reduces our dependency footprint and will allow http4s users to bring their own version of shapeless.

### CODE REVIEW

**Comment by rossabaker** [comment]
I would like to make the types `private[http4s]`, but I got hit with a bunch of fussy errors about things that shouldn't be open to extension no longer being extensible.  It may be worth another try.

**Comment by rossabaker** [comment]
Well, it compiled for me locally. 😿

**Comment by ChristopherDavenport** [comment]
Looks good on 2.11 and 2.12 just a 403 forbidden error from Github from Tut. What are we thinking about 2.10?

**Comment by rossabaker** [comment]
Build failure is #817.

**Comment by rossabaker** [comment]
[SI-9490](https://issues.scala-lang.org/browse/SI-9490) is making it very difficult to make this package private and have the compiler enforce that it is used only internally.  We might be able to do it if we disable `-Xlint` in this project.  Worth it?

**Comment by bryce-anderson** [comment]
Pains me to fork parboiled2 here. What do you anticipate the maintenance burden will be in the future? In my minds eye it should be minimal so long as macros don't change, but once they do its going to be a huge PITA.

**Comment by rossabaker** [comment]
Parboiled2 isn't changing very fast.  I tried macrocompat for 2.10, but the macros weren't written in a friendly way.  I can imagine this hurting for 2.13, but I imagine by that point we'll have dropped 2.10 and we can start over by copying in the latest parboiled source tree.

This PR made me sad, but dependencies are one of the biggest complaints we get, and these are two that are easy to do without.  And we'd have company in [akka-http](https://github.com/akka/akka-http/commits/master/akka-parsing).

**Comment by rossabaker** [comment]
It was pretty much a straight repackaging.  If anything is going to break, I anticipate it's on 2.10, where we combined fragments of an old release with the latest.  This combination is not tested across the parboiled2 community, but it survives scalac and our test suite, so I'm hopeful.

**Pull request merged**
