### PR TITLE
Support HEAD requests as specified in #395

### PR DESCRIPTION
**Pull request by hvesalai**

### CODE REVIEW

**Comment by hvesalai** [comment]
(also tested this by adding a service to ExampleServices, but didn't want to push that change)

**Comment by bryce-anderson** [comment]
I believe this will fail to write the `Transfer-Encoding` header on a HEAD request. See [here](https://github.com/hvesalai/http4s/blob/fix395/blaze-core/src/main/scala/org/http4s/blaze/Http1Stage.scala#L244) for where its filtered out when writing the headers.

**Comment by hvesalai** [comment]
Regarding Transfer-Encoding: true. Do you think it needs to be written?

**Comment by hvesalai** [comment]
(if so, then we need to be sure not to write it for HTTP/1.0 requests)

**Comment by bryce-anderson** [comment]
I believe we need to send the response prelude _exactly_ as it would be for a GET request and just forget about the body. That means the transfer-encoding header should probably be there as well.

As far as HTTP/1.0 requests, I don't exactly know the behavior we should enforce: I'd have to read the spec(s) again.

As an aside, some people are intimidated by HTTP2 spec but through its culling of corner cases I find it much easier to deal with than the years of hacks that is HTTP1.X.

**Comment by rossabaker** [comment]
[The spec says](https://tools.ietf.org/html/rfc7231#section-4.3.2)

>  The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted.

Transfer-Encoding is a [payload header field](https://tools.ietf.org/html/rfc7231#section-3.3).  That said, I don't see a good justification to strip them, even though it's permitted.

**Comment by hvesalai** [comment]
So but still we have to decide:
- if we send the header explicitly set by the service
- if we send the same header that we would have autogenerated

**Comment by bryce-anderson** [comment]
Since it appears not to matter so much I'd suggest sending any explicitly
set headers but not bothering to try and figure out what it would have been
generated.

**Comment by rossabaker** [comment]
:+1:

**Comment by rossabaker** [comment]
This is actually binary compatible.  Any objections to this going out with 0.11.3?

**Comment by bryce-anderson** [comment]
:+1: 

@rossabaker, feel free to merge this once you find out where its headed.

**Comment by rossabaker** [comment]
Cherry-picked into 0.11.3.

**Comment by hvesalai** [comment]
@rossabaker you didn't merge this into master?

**Comment by rossabaker** [comment]
It's on 0.11.3 now.  I was then going to merge it into master with the release commit, and then we got one more change to put in the release, and then I got distracted by work.  I will get this sorted out this evening.

**Pull request closed without merging**
