### PR TITLE
Ember Entity Encoding No ContentLength or TransferEncoding on NoEntityAllowed status'

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
This previously would have encoded as chunked encoding, and then had a single empty buffer flush which is unnecessary for these.

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1: The workflow needs regeneration. Probably inherited from the CVE fork that didn't run on CI.

**Comment by rossabaker** [comment]
I think this is fit for 0.21?

**Comment by ChristopherDavenport** [comment]
Yes I it can be retargeted it branched of 0.21

**Comment by rossabaker** [comment]
Picked into 0.21 as 31850ff.

**Pull request closed without merging**
