### PR TITLE
kind-projector has moved to typelevel org

### PR DESCRIPTION
**Pull request by SethTisue**
perhaps there is some other in-flight PR with this change, but
regardless, it would helpful for the Scala community build to have
just this change land on master

### CODE REVIEW

**Comment by aeons** [comment]
It looks like that version isn't released for 2.13.0-M5, which fails our build.

**Comment by rossabaker** [comment]
This is included in #2493, which is likely to be stuck a while longer (the checklist there is just the first wave).  We could branch on Scala version.

**Comment by SethTisue** [comment]
> We could branch on Scala version

okay I'll do that

**Comment by rossabaker** [comment]
I think ddc304a will be sufficient for @SethTisue to unfork us in the community build.

**Pull request merged**
