### PR TITLE
Headers docs

### PR DESCRIPTION
**Pull request by cquiroz**
I had this sitting for a while. This adds a bit of documentation for headers and cookies as well as missing tests for some of the methods described:

Some questions:
* Should I add the equivalent on the client side?
* Should there be documentation on custom headers?
* There is a test broken but apparently it is on the base branch. Is that going to be fixed?

Hope this is useful

### CODE REVIEW

**Comment by rossabaker** [comment]
I just ripped the base branch out from underneath you, but you or I can rebase this onto #802 when it's time to merge.

**Comment by rossabaker** [comment]
It may be worth noting that headers work the same way on requests and responses, client and server side.

Documentation on custom headers would be good, but it kind of sucks making them right now.  That's an experience I'd like to improve, but there are dragons.  I'd certainly welcome documentation on the status quo.

Which test is broken?  I see an intermittent Travis issue with tut, which I'm rerunning now.

**Comment by rossabaker** [comment]
I pulled this onto a tmp branch, because I don't see the problem.  I won't be awake to see it finish, but, let's see how https://travis-ci.org/http4s/http4s/builds/185981192 goes.

**Comment by cquiroz** [comment]
There is an error with the docs:

```
[tut] *** Error reported at /home/travis/build/http4s/http4s/docs/src/hugo/content/service.md:160
// <console>:33: error: object shutdownNow is not a member of package org.http4s.server
//        server.shutdownNow()
```

It only happens in scala 2.11.8 and scalaz 7.2.7

**Comment by rossabaker** [comment]
We call it blazeServer in one of the other tuts to avoid a conflict with the package.  It's curious that I can't reproduce this locally, however.

**Comment by rossabaker** [comment]
Got this passing on #802.  The villain was the server in streaming.md.

**Comment by cquiroz** [comment]
👍

**Pull request closed without merging**
