### PR TITLE
Tweak badges in the readme

### PR DESCRIPTION
**Pull request by danicheg**
Two proposals:
1. if the actual 'main' branch is `series/0.23` then we should refer to the right CI build status
2. let's promote the latest major release version

### CODE REVIEW

**Comment by armanbilge** [comment]
WDYT about a scaladex badge instead of a maven central badge?

[http4s-core Scala version support](https://index.scala-lang.org/http4s/http4s/http4s-core)

**Comment by danicheg** [comment]
@armanbilge I have no preference between badges 😆 Feel free to change it within that branch if you like that one more.

**Comment by danicheg** [comment]
@armanbilge btw there is a difference between them. With the maven central one - the title is 'maven-central', with the scaladex one - the title is the name of the particular module 'http4s-core'.

**Review by armanbilge — APPROVED** [review]
Yeah, I think the Maven one is more configurable. Scaladex doesn't have the `?versionPrefix=0.23` option.

**Pull request merged**
