### PR TITLE
Bye-bye dropwizard, prometheus

### PR DESCRIPTION
**Pull request by armanbilge**
Now found at:
- https://github.com/http4s/http4s-dropwizard-metrics
- https://github.com/http4s/http4s-prometheus-metrics

Including documentation at:
- https://http4s.github.io/http4s-dropwizard-metrics/
- https://http4s.github.io/http4s-prometheus-metrics/

### CODE REVIEW

**Comment by armanbilge** [comment]
Crap, dropwizard is used in a blaze example. We can't easily move the example to the dropwizard repo since it needs the example service.
https://github.com/http4s/http4s/blob/34aff6c87c60d44a27a58930b917710da5c3716d/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala#L36-L40

**Comment by rossabaker** [comment]
Our examples were way too coupled anyway.  I don't mind throwing a trivial example in dropwizard and deleting this.

**Comment by armanbilge** [comment]
Ok, and I really took you at your word at trivial 😉 

We have:
- https://http4s.github.io/http4s-dropwizard-metrics/
- https://github.com/http4s/http4s-dropwizard-metrics/pull/2

**Review by rossabaker — APPROVED** [review]
:+1:

**Pull request merged**
