### PR TITLE
Add Order And Hash Instance For Charset

### PR DESCRIPTION
**Pull request by isomarcte**

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
We can cherry-pick this to series/0.21.  (If you're not making breaking changes, always target series/0.21.)  Could throw in a `Hash` instance for extra credit, but it'll need to be in the same value as the `Order` to avoid competing `Eq`s.  See #3902 for an example of that.

**Comment by isomarcte** [comment]
@rossabaker oh sorry about that. I had meant to target series/0.21, but I guess I wasn't paying attention yesterday. I'll get that fixed and add the `Hash` instance.

**Comment by rossabaker** [comment]
Needs a scalafmt, but otherwise looks good.

**Comment by isomarcte** [comment]
@rossabaker updated.

**Review by rossabaker — APPROVED** [review]
:+1: Thanks!

**Pull request merged**
