### PR TITLE
FS2 0.10: Standardise on ExecutionContext

### PR DESCRIPTION
**Pull request by aeons**
I've changed all the remaining places that ExecutorService was used to be ExecutionContext.

There are still some ExecutorServices around to create some pools for different things.

There are some comments on no using a default pool for servers and clients, but I haven't changed anything wrt. those.

### CODE REVIEW

**Comment by rossabaker** [comment]
How hard would it be to do this on master?  It would have to be converted to a `Strategy` in some places, but steer people toward doing the right thing now.

**Comment by aeons** [comment]
I'll take a look

**Comment by aeons** [comment]
Merged in #1243

**Comment by ChristopherDavenport** [comment]
:tada:

**Pull request closed without merging**
