### PR TITLE
Alter StaticFile.fromURL so it doesn't rely on StaticFile.fromFile. 

### PR DESCRIPTION
**Pull request by kryptt**
See issue #232

### CODE REVIEW

**Comment by rossabaker** [comment]
The return looks a little funky to me, but the logic is sound. 

Magic number 4096 is appearing in a bunch of places and should be centralized, but that can be a separate issue.

**Comment by kryptt** [comment]
yeah, basically I just tried to  keep the style similar to what was bellow (fromFile has the same return which could be avoided)

**Comment by bryce-anderson** [comment]
My concern with working with streams is that they will block. It shouldn't be a big deal but I don't know. I'd like to hear other opinions on that.

On the flip side, there is no way to deal with resources in a jar without using streams. The only alternative I can think of is having a block and nonblocking version so people can make an educated choice.

Note that there is already a ```DefaultBufferSize``` constant defined at the top of the object.

**Comment by rossabaker** [comment]
Off an SSD, I don't think blocking will be a significant issue.  Off Ye Olde NFS Mount, it could be awful.  I expect the former to be much more frequent than the latter.  For people for whom file serving becomes a huge itch, they'll probably have nginx in front of us anyway.

As far as I'm concerned, working is more important than the style issue or the blocking issue, so :+1:.  I would like us to make a subsequent pass to clean up the return statements, and we could explore the idea of switching on the scheme to go non-blocking where available.

Thanks,
Ross

**Comment by kryptt** [comment]
Actually, I think separating the URL and File paths is a positive step.
This IS StaticFile, so JARs are probably in memory, and we can just update the File path to use NIO...

**Comment by bryce-anderson** [comment]
Just to clarify for myself, @kryptt, are you suggesting we have something to the effect of ```StaticResource``` in addition to ```StaticFile```?

**Comment by kryptt** [comment]
No, just the fact that fromURL no longer calls fromFile.

**Comment by bryce-anderson** [comment]
This PR looks good to me. Sounds like the plan is that StaticFile might get
another pass later to look at keeping things async when possible, but that
isn't urgent.
If this is finished, I'm for merging it.

Thanks for the nice PR @kryptt.

**Comment by kryptt** [comment]
Its finished. :)

**Pull request merged**
