### PR TITLE
Release v0.20.12

### PR DESCRIPTION
**Pull request by rossabaker**
Contains cherry-pick of #2922 and a conservative set of upgrades.

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks like this went ahead and released on its own?

**Comment by rossabaker** [comment]
Yeah, why would the publish stage run on [this build](https://travis-ci.org/http4s/http4s/jobs/605322581)?

**Comment by mi-char** [comment]
Hi @rossabaker. I don't see changes from #2922 in the `series/0.20` branch nor the `master` branch.

**Comment by rossabaker** [comment]
It appears you're right.  Let me figure out what happened and I will try again ASAP.

**Comment by rossabaker** [comment]
Sorry about that. I tried to do too much at once. #2949 will fix this.

**Pull request merged**
