### PR TITLE
Encode query keys.

### LINKED ISSUE #510: Query#render does not url-encode keys
The `Query#render` method does not url-encode keys when converting to a string, which can lead to invalid characters in rendered `Uri`s.

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #510.

### CODE REVIEW

**Comment by rossabaker** [comment]
We had a nice property check for it, but a poor generator.  Simplified the generator to create more challenging query strings, and also added an explicit test for good measure.

**Comment by bryce-anderson** [comment]
Looks like we need to add `?` and `/` to the list of unreserved characters when encoding the query: http://tools.ietf.org/html/rfc3986#section-3.4.

**Comment by rossabaker** [comment]
Yep.  I just read that and was contemplating the fallout.

**Comment by refried** [comment]
I'm nervous about https://github.com/http4s/http4s/issues/492 which is used here too.  (I lament that I haven't solved it.)  I think it's important to be clear about exactly what aspect of url-encoding `urlEncode` is supposed to be doing, and then be sure to only use it in the right contexts.  Is it meant to encode:
* query parameter keys and/or values?  (i.e. do encode '=')
* full query strings? (don't encode '=')
* full URIs? (can a path have a '/' escaped in it?)
* other things I've never even heard of?

**Comment by rossabaker** [comment]
Linking to Spring invites ridicule in the Scala community, but I still haven't had the Enterprise Java Developer fully beaten out of me, and [they have put a lot of thought into this](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java#L480-L627).  Observe how [their encoder](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/util/UriUtils.html) is several methods, depending on what component is being encoded.

**Comment by rossabaker** [comment]
I think 37fbafd addresses #510 in a binary compatible and standards-compliant way, but I agree that this is closely related to #492, and we can and should do better for 0.13.

**Comment by refried** [comment]
Good call! I like that.

[Here's](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/util/UriUtils.java) their `UriUtils`, which calls out to the `HierarchicalUriComponents` you linked.

**Comment by refried** [comment]
*nod* I'm not trying to hold up this PR.

**Comment by rossabaker** [comment]
Ugh, I thought this targeted 0.12.1.  Cherry-picking, too.

**Pull request merged**
