### PR TITLE
Migrate InstrumentedHandler to Scala

### PR DESCRIPTION
**Pull request by jonoabroad**
It's a direct port from Java, so not pretty.

There is little idiomatic Scala, let me know if you want less `null` and more nice.

### CODE REVIEW

**Comment by rossabaker** [comment]
I'd say more nice or more package protected, and would lean toward the latter.  I can live with the nulls, but I'd like to hide our shame from public API.

**Comment by jonoabroad** [comment]
I could update the var null to be  :

`private lazy val requests:Timer = registry.timer(registryName(prefix,
"requests")) `

If we define `prefix` to be  `private lazy val prefix = _prefix.fold(
registryName(getHandler().getClass(), name) )(p => registryName(p, name))`

where `_prefix` is the case class val.

It would be nice to know where and when name is set.

**Comment by rossabaker** [comment]
Looks like it can be called optionally before the lifecycle method `doStart` is invoked.

**Comment by rossabaker** [comment]
:+1:

**Pull request merged**
