### PR TITLE
Merge from 0.22

### PR DESCRIPTION
**Pull request by rossabaker**
This one's pretty trivial.  It will let us start with the release notes.

### CODE REVIEW

**Comment by rossabaker** [comment]
Good news: this labeling works out great.  If we would invest in putting module labels on certain dependencies and when paths change, the release notes would just about write themselves.

**Comment by rossabaker** [comment]
~~I have run afoul of https://github.com/mxschmitt/action-tmate/issues/1 trying to debug that test.  This is holding back 0.23.8, unless we don't think this is new (or newly worse).~~

**Comment by armanbilge** [comment]
/shrug we always have blaze flakes. This one seemed esp. odd because it only seems to happen on Scala 3 (has it been observed anywhere else?). I don't think we need to hold back for it.

**Comment by rossabaker** [comment]
I was excited to have a way to finally debug them in the environment in which they fail.  It was fun for the 24 hours it lasted.

**Comment by rossabaker** [comment]
Excuse the force-pushes.  I got my branches tangled from pushing tmate to my fork.

**Comment by rossabaker** [comment]
If I'm on the GHA page before the backdoor step starts, _and_ run it late enough in the build that all the checks have already run, I get the connect string ... sometimes.  If I make it the main build, nope.

**Comment by rossabaker** [comment]
Yeah, I don't have a lot of confidence this one is going to pass on release.

**Comment by armanbilge** [comment]
In other news, I see `ClientTimeoutSuite` has now failed on 2.13.8 as well. So it's not a Scala 3 thing ...

**Comment by rossabaker** [comment]
I had a build that actually gave me the tmate connect string, but I canceled it in the hopes of getting this working.  I'm trying again. 🤞🍀

**Comment by rossabaker** [comment]
I'm ssh'ed into the build and struggling to make it fail.  The test was improved by @RafalSumislawski in https://github.com/http4s/http4s/commit/5422da2bdceb0c12e9c7c9d83d8fc6d4a3bbdd71.

Each test gets its own `TickWheelExecutor`, so I don't think that's what's blocked.  The test failure looks like nothing triggered a timeout within the client, so the test itself gives up after 5 seconds.  I think something else is blocking somewhere, and this test is the victim.  I'm just having trouble identifying it from this slow ssh session into the action.

**Comment by armanbilge** [comment]
Another random idea I had is whether you can trigger a CE fiber dump and if it would have any helpful information. Unfortunately they're not easily accessible in test suites, but there should be an mbean registered. This also assumes that you are using a vanilla `IORuntime` which I'm not sure if this is the case.

**Comment by rossabaker** [comment]
I see four threads wedged in this when the test is running:

```
        at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:24)
        at cats.effect.std.Dispatcher$$anon$2.unsafeRunSync(Dispatcher.scala:188)
        at org.http4s.client.scaffold.RoutesToHandlerAdapter.onRequestStart(RoutesToNettyAdapter.scala:79)
        at org.http4s.client.scaffold.HandlersToNettyAdapter.channelRead0(HandlersToNettyAdapter.scala:70)
        at org.http4s.client.scaffold.HandlersToNettyAdapter.channelRead0(HandlersToNettyAdapter.scala:55)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

Also an ember thread stuck at the same time:

```
        at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:24)
        at cats.effect.std.Dispatcher$$anon$2.unsafeRunSync(Dispatcher.scala:188)
        at org.http4s.ember.server.EmberServerWebSocketSuite$$anon$3.onClose(EmberServerWebSocketSuite.scala:112)
        at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:663)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:552)
```

**Comment by armanbilge** [comment]
Which threads in particular? What are their thread ids?

**Comment by rossabaker** [comment]
I'm running `watch` with a `grep -C` and it's ephemeral, but trying to grep smarter.  All I have are terminal tools here.

**Comment by rossabaker** [comment]
Ember is leaving one of these behind, but I don't think it's the problem:

```
"WebSocketConnectReadThread-647" #647 daemon prio=5 os_prio=0 tid=0x00007fd8a5ab1800 nid=0x3c7c waiting on condition [0x00007fd83dde0000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000650f3f6b0> (a scala.concurrent.impl.CompletionLatch)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:207)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.Await$$$Lambda$11588/456053273.apply(Unknown Source)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.Await$.result(package.scala:124)
        at cats.effect.std.DispatcherPlatform.unsafeRunTimed(DispatcherPlatform.scala:60)
        at cats.effect.std.DispatcherPlatform.unsafeRunTimed$(DispatcherPlatform.scala:24)
        at cats.effect.std.Dispatcher$$anon$2.unsafeRunTimed(Dispatcher.scala:188)
        at cats.effect.std.DispatcherPlatform.unsafeRunSync(DispatcherPlatform.scala:51)
        at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:24)
        at cats.effect.std.Dispatcher$$anon$2.unsafeRunSync(Dispatcher.scala:188)
        at org.http4s.ember.server.EmberServerWebSocketSuite$$anon$3.onClose(EmberServerWebSocketSuite.scala:112)
        at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:663)
        at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:552)
        - locked <0x0000000650f3f808> (a org.java_websocket.WebSocketImpl)
        at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:607)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:518)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by armanbilge** [comment]
Huh. It looks to me like that daemon thread is blocked waiting for a fiber to complete. But it's not clear whether that fiber is only semantically blocked, or blocking another thread elsewhere.

**Comment by rossabaker** [comment]
I can sit here all day long on this machine and run `sbt 'project rootJVM' ++3.1.0 test` and not see a failure.  Am I missing something that CI is doing?

**Comment by armanbilge** [comment]
>  Am I missing something that CI is doing?

I don't think so :(

**Comment by rossabaker** [comment]
The job that's failing is compiling the code in the same SBT run as the tests.  That's the only substantial difference I can find.  I don't know why it should be relevant.

**Comment by armanbilge** [comment]
Oh, right. sbt has some limits on parallelism, so if there's code compiling while test suites are also running it might run less of them in parallel than when the code is already compiled. Not sure if that makes a difference.

**Comment by rossabaker** [comment]
I can see tests running with the build, but still can't make it fail.

**Comment by rossabaker** [comment]
I'm merging this.  It doesn't touch code, and it's holding up 0.23.

**Pull request merged**
