### PR TITLE
Allow to customize flags for file decoders

### PR DESCRIPTION
**Pull request by armanbilge**
E.g. to append to an existing file.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
Some day I'll make up my mind how I feel about overloads, but I like the functionality and I don't have a better name for the new ones.

**Comment by armanbilge** [comment]
Yeah, I went through the same thought process on this one. At least it's not default args 🙃

**Review by danicheg — APPROVED** [review]
I like pure overloads but hate them powered with default arguments. There are none of them here, so that is greenlit from me 👍🏻

**Comment by rossabaker** [comment]
My only hesitation with this style of overload in general is that they are a nuisance for partial application.  This breaks source compatibility.  But I doubt very many people are using it that way here.

**Pull request merged**
