### PR TITLE
The Service arrow returns.

### PR DESCRIPTION
**Pull request by rossabaker**
This is a possibly controversial extension of #332.  See discussion at the end of that ticket.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Why is this controversial?

**Comment by rossabaker** [comment]
1. It's a dumber, non-standard Kleisli.  It's (unmeasured) more efficient being specialized on Task, but it as yet offers no additional functionality.

2. Extra functionality could come in the form of an `orElse` and `or`, which would be great for `PartialService` and the current design of the examples.  But that can't be done generally without an `Empty` typeclass, which we'd have to provide ourselves.  It has appeared as an [alleycat](https://github.com/non/alleycats/blob/master/core/src/main/scala/alleycats/Empty.scala), but does not exist in Scalaz.

**Comment by kryptt** [comment]
I think going from Task[Option[_]] to Task[_] has proven itself. 

1. I wonder what the efficiency gains from not using Kleisli are?

2. How about issuing a pull request to [scalaz-contrib](https://github.com/typelevel/scalaz-contrib)?

**Comment by rossabaker** [comment]
I think we can mitigate the cost of the wrapper -- `Service` or `Kleisli` -- by creating a direct reference to `.run` in the backend.  By that point, there is no further composition.  In this regard, either wrapper should be as fast as a pure function.

That leaves the cost of going through `Task` instances in Kleisli vs. direct to the `Task` in `Service`, which would only manifest when composing middleware stacks.

To get a benchmark on this, I'd have to also get this compiling under `Kleisli`.  Is anybody leaning one way or the other, performance be damned, or do we need a bake-off?

**Comment by rossabaker** [comment]
Kleisli is not an [earth-shattering difference](https://github.com/http4s/http4s/commit/7c4d7ed006c444f5834bb40389de460ebfa499f7) in terms of code.

**Comment by rossabaker** [comment]
To provide a poor benchmark, as I don't have convenient access to a second server to write a gatling test:

I wrapped our example service in `AutoSlash` and `ChunkAggregator`.  This gets us a `flatMap` and a `map` through type classes on the Kleisli side.

* Service: 67974 rps
* Kleisli: 68188 rps

A specialized `Service` is theoretically faster, but I can't prove it.  I think it boils down to using a well known and more general type vs. a non-syntactic `or` / `orElse` if we an find a decent `Empty`.

**Comment by rossabaker** [comment]
Meant to update this pull request with Kleisli, but I updated the old one.  That change has been met warmly here and in Gitter, so I guess this PR has served its purpose.  The action is back on #332.

**Pull request closed without merging**
