### PR TITLE
Ember Use in Docs Over Blaze

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Working on the g8 template now

### CODE REVIEW

**Review by RaasAhsan — APPROVED** [review]

**Review by rossabaker — APPROVED** [review]
:+1: on green

**Comment by rossabaker** [comment]
Talked it over a bit, and the strategy is to document Ember alongside Blaze in 0.21, and make it the default in 0.22.

This should achieve the latter, so retargeting.

**Comment by rossabaker** [comment]
This hung our docs build.  Some backend didn't shut down somewhere.

**Comment by rossabaker** [comment]
It looks like this one is already going south in client.md.  It would be great to get this one landed, because the g8 template is already cut over.

**Comment by armanbilge** [comment]
Didn't make it into the 0.22 docs, but superseded by https://github.com/http4s/http4s/pull/5970 in the 0.23 docs.

**Pull request closed without merging**
