### PR TITLE
Recyle more connections

### LINKED ISSUE #4872: Inconsistent connection recycling when raising an error
We recently moved from using `async-http-client` to using `blaze-client` and saw a increase in latency.
It turned out to be because we would sometimes raise an error inside `client.run(req).use()`, like so:

```scala
for {
  req <- GET.apply(uri = Uri.unsafeFromString("http://example.com"))
  _ <- client.run(req).use { resp =>
    resp.bodyText.compile.string.flatMap { res =>
      IO.raiseError(new Exception(s"Unexpected Response: $res"))
    }
  }
} yield ()
```

In this case `async-http-client` recycles the connection back into the pool to be re-used on the next request, 
however `blaze-client` behaves differently and will invalidate the connection and not return it to the pool.

TBH, I'm not sure which way is the intended behaviour (I can see arguments for both), however I think it would make sense for it to be consistent across clients.

## Example

I've put a self contained example together here: https://github.com/theon/http4s-error-recycle-connections
It runs two requests that raise an error to see if the second request re-uses the same connection as the first request
Here's the logs from running that same code for AHC and Blaze

### AHC

Request 1 Creates a new connection and then adds it to the pool:
```
2021-05-23 21:55:51,712 [http4s-async-http-client-worker-1] [DEBUG] org.asynchttpclient.netty.channel.NettyConnectListener Using new Channel '[id: 0x01fd2b9c, L:/192.168.1.245:64968 - R:example.com/93.184.216.34:80]' for 'GET' to '/'
...
2021-05-23 21:55:52,073 [http4s-async-http-client-worker-1] [DEBUG] org.asynchttpclient.netty.channel.ChannelManager Adding key: http://example.com:80 for channel [id: 0x01fd2b9c, L:/192.168.1.245:64968 - R:example.com/93.184.216.34:80]
```

Request 2 Reuses the connection and then puts it back in the pool:
```
2021-05-23 21:55:52,188 [ioapp-compute-4] [DEBUG] org.asynchttpclient.netty.request.NettyRequestSender Using pooled Channel '[id: 0x01fd2b9c, L:/192.168.1.245:64968 - R:example.com/93.184.216.34:80]' for 'GET' to 'http://example.com'
2021-05-23 21:55:52,188 [ioapp-compute-4] [DEBUG] org.asynchttpclient.netty.request.NettyRequestSender Using open Channel [id: 0x01fd2b9c, L:/192.168.1.245:64968 - R:example.com/93.184.216.34:80] for GET '/'
...
2021-05-23 21:55:52,286 [http4s-async-http-client-worker-1] [DEBUG] org.asynchttpclient.netty.channel.ChannelManager Adding key: http://example.com:80 for channel [id: 0x01fd2b9c, L:/192.168.1.245:64968 - R:example.com/93.184.216.34:80]
```

## Blaze

Request 1 Creates a new connection and then invalidates it:
```
2021-05-23 21:55:55,376 [ioapp-compute-5] [DEBUG] org.http4s.client.PoolManager Requesting connection for http://example.com: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2021-05-23 21:55:55,381 [ioapp-compute-5] [DEBUG] org.http4s.client.PoolManager Active connection not found for http://example.com. Creating new one. curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
...
2021-05-23 21:55:55,613 [scala-execution-context-global-137] [DEBUG] org.http4s.client.PoolManager Invalidated connection for http://example.com, no pending requests. Shrinking pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

Request 2 Finds no connection in the pool, creates a new connection and then invalidates it:
```
2021-05-23 21:55:55,614 [ioapp-compute-2] [DEBUG] org.http4s.client.PoolManager Requesting connection for http://example.com: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2021-05-23 21:55:55,614 [ioapp-compute-2] [DEBUG] org.http4s.client.PoolManager Active connection not found for http://example.com. Creating new one. curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
...
2021-05-23 21:55:55,792 [scala-execution-context-global-137] [DEBUG] org.http4s.client.PoolManager Invalidated connection for http://example.com, no pending requests. Shrinking pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

## Workarounds

We have several options to workaround for the meantime:

Move our `raiseError`s outside of `use`:
```scala
for {
  req <- GET.apply(uri = Uri.unsafeFromString("http://example.com"))
  res <- client.run(req).use { resp =>
    resp.bodyText.compile.string
  }
  _ <- IO.raiseError(new Exception(s"Unexpected Response: $res"))
} yield ()
```

We can also use `expect` rather than `run` + `use`. Either way we see the following with blaze for these workarounds showing the connection now return to the pool:

```
2021-05-23 22:05:57,237 [scala-execution-context-global-138] [DEBUG] org.http4s.client.PoolManager Returning idle connection to pool for http://example.com: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

### PR DESCRIPTION
**Pull request by RafalSumislawski**
Fixes #4872. This PR depend on #4831

After this change blaze-client will attempt to recycle connections if response header was successfully received, regardless of the result of processing of the response. Receiving response header doesn't guarantee that the connection is in a good shape. For example the response body may have not been fully transmitted and consumed. But the state of the connection  is supposed to be checked with a call to `Http1Connection#isRecyclable` made by `PoolManager`.

### CODE REVIEW

**Comment by rossabaker** [comment]
Oops, this should squeeze into 0.21.25.  I merged it in the browser and hope I don't regret it.

**Comment by rossabaker** [comment]
Bad merge and I'm sleepy.  Will try again tomorrow unless someone fixes it first.

**Comment by RafalSumislawski** [comment]
I will fix the merge

**Comment by rossabaker** [comment]
Thanks!  Sorry for breaking it in my haste.

**Pull request merged**
