### PR TITLE
migration examples to ce3

### PR DESCRIPTION
**Pull request by yanns**
Partially fix https://github.com/http4s/http4s/issues/4093

Ember examples are missing as ember is not migrated to ce3 yet (https://github.com/http4s/http4s/issues/4085 https://github.com/http4s/http4s/issues/4086)

I could not start the blaze examples:
```
[info] running (fork) com.example.http4s.blaze.ClientExample
[info] -Xbootclasspath/p is no longer a supported option.
[error] Error: Could not create the Java Virtual Machine.
[error] Error: A fatal exception has occurred. Program will exit.
```
I don't know if this is a known issue.

### CODE REVIEW

**Comment by yanns** [comment]
Still an overseen warning to fix:
```
[error] /home/runner/work/http4s/http4s/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala:72:9: object Queue in package concurrent is deprecated (since 3.0.0): Use cats.effect.std.Queue instead
[error]         Queue
[error]         ^
[error] one error found
```

**Comment by rossabaker** [comment]
That parameter is for ALPN support, which isn't necessary after Java 8 and probably should be filtered accordingly.  But we test on newer JDK, so I'm not sure why you'd be hitting that.  Which JDK did you hit that error on?

If you disable AlpnBootPlugin, that should go away... but so will HTTP/2 support.

**Review by rossabaker — APPROVED** [review]
:+1: for incremental progress.  I don't mind splitting this across PRs.

**Comment by yanns** [comment]
> That parameter is for ALPN support, which isn't necessary after Java 8 and probably should be filtered accordingly. But we test on newer JDK, so I'm not sure why you'd be hitting that. Which JDK did you hit that error on?

```
$ javac -version
javac 15.0.1

$ java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```


> If you disable AlpnBootPlugin, that should go away... but so will HTTP/2 support.

Thanks, I've tried that, and the examples are working:
```
 lazy val examplesBlaze = exampleProject("examples-blaze")
-  .enablePlugins(AlpnBootPlugin)
   .settings(Revolver.settings)
```

**Comment by rossabaker** [comment]
Oh, and it's in `run / javaOptions`, which is why CI doesn't catch it.  We can fix it in the org plugin, and it'll work here, for upstream blaze, and for anything else that needs it for HTTP/2 support.

**Pull request merged**
