### PR TITLE
Wip/parsers on keys

### PR DESCRIPTION
**Pull request by bryce-anderson**
__This is not complete: do not merge.__

This PR  moves the ```Header``` parsers from a central location and onto their respective ```HeaderKey```s.

Notable changes
* ```Raw``` headers will attempt to cache their parsed representations in a different manner than before
* The central collection of parsers is removed
* ```Header``` equality is changed. No longer can a ```Raw``` header be compared with its parsed form and equate.
* Equality of ```Headers``` will also be destroyed for the reasons above and becomes more like a sequence. Removal of non-recurring headers is no longer possible because it cannot parse a ```Raw``` header to determine if its a singleton or recurring header.

Comments needed before I continue on this. There is quite a bit of polish left to do before merging but I'm not interested in sinking the time if we don't want to go this direction.

### CODE REVIEW

**Comment by rossabaker** [comment]
I wonder about `Headers` continuing to be `IterableLike` once `Header` loses its (awkward) attempts to implement equality.  In addition to remove, methods like filter and contains start to have surprising results.  I think perhaps we've moved the point of abuse from equality to the collection.

**Comment by bryce-anderson** [comment]
Yes, ```Headers``` will be hurt pretty badly. I have yet to actually dig into it: it was one of the things I decided to differ on until we decided if we like it, but maybe it would have been good to see how it looks. Its pretty obvious its going to feel more like a set of extension methods than what it is now.

I'm not totally sold that this is the way to go. It gives us an obvious structure with which to allow and even foster a users custom parsers, but it feels very costly. I wonder if making our 'super parser' allow adding new parsers would be just as good. Its not 'pure', but I don't see how it wouldn't let us keep the niceties we have now.

**Comment by rossabaker** [comment]
Methods that depend on equality could take an `Equal` instance, to let users tune their own level of surprise.  `Headers` would then present a familiar interface, though no longer as a standard `Iterable`.

I'm not entirely satisfied by the status quo or anything on this ticket.  Just brainstorming.

**Comment by bryce-anderson** [comment]
I'm not sure how an ```Equal``` instance helps us in this situation. The equals would need to know about parsers etc if it wants to do what we do now, which is very unlikely and will probably just fall to the greatest common denominator of case class equality. At that point I think functions that take a lambda resulting in a Boolean or whatever is appropriate for the function, eg ```find``` and friends on regular collections.

**Comment by bryce-anderson** [comment]
I'm beginning to think this is an issue that will take some time to solve. I say we kick this can down the road to the next release.

**Comment by rossabaker** [comment]
:+1:

**Comment by bryce-anderson** [comment]
I've posted a branch that allows one to add more parsers to the registry. 
https://github.com/http4s/http4s/tree/topic/HttpHeaderParser

Any suggestions? If its promising I'll close this PR and open a new one for that branch.

**Comment by bryce-anderson** [comment]
Closed in favor of #287.

**Pull request closed without merging**
