### PR TITLE
Smite `Seq` in `Message#multiParams`, `Uri#multiParams`, `Query#multiParams`

### PR DESCRIPTION
**Pull request by danicheg**
Addresses the #1695.
This might be very controversial. So share what you think.

### CODE REVIEW

**Comment by hamnis** [comment]
Since we are targeting > 2.12 we can use Vector instead of List.
That has better performance characteristics even for small collections after the changes in 2.13

**Comment by danicheg** [comment]
> That has better performance characteristics even for small collections after the changes in 2.13

@hamnis Can you please share some links to the benchmark or where this is declared? I've attempted to find it multiple times and didn't succeed every time. Though I believed for sequence collections of <100 elems size `List` is about the same perf as `Vector`. At least for sure, I remember a small discussion with @RafalSumislawski on Twitter about it :)

**Comment by hamnis** [comment]
One is here:

https://august.nagro.us/list-vs-vector.html

official docs:

https://docs.scala-lang.org/overviews/collections-2.13/performance-characteristics.html

**Comment by armanbilge** [comment]
So IIUC:
1. Internally we are already using `List`, since you only had to change signatures.
2. The signature changes are all in covariant positions (i.e., we are giving the user a `List`, not asking for one).

If both those things are true, then actually we can even make this change compatibly in `series/0.23` if we wanted, since we are not breaking any contract.

**Comment by danicheg** [comment]
@armanbilge I'm 100% sure this change should go in 1.0. Since users can expect in their code that returning type is exactly `Seq`. So we can break it very easily. Hence even if MiMa will allow us to do this change in 0.23, it's still not binary-compatible.

**Comment by armanbilge** [comment]
> Since users can expect in their code that returning type is exactly `Seq`

A `List` is a `Seq` :)

> Hence even if MiMa will allow us to do this change in 0.23, it's still not binary-compatible.

It is binary-compatible :) binary-compatibility is about the signatures as represented in the bytecode. Indeed, if you inspect the bytecode you will find that it is unchanged, due to type erasure of generics.

**Comment by danicheg** [comment]
@armanbilge Hmm, tend to agree with you. I just was worried about using `scala.collection.Seq` within `Message` in 2.12 (not immutable one as we do almost everywhere when using `Seq`). So it seems because we already use `List` in internals, we can't hurt users somehow.

**Comment by armanbilge** [comment]
FWIW I'm not advocating we make this change in `series/0.23` ... just saying we could, if we wanted to, since it is actually compatible. So I think this is not such a controversial change for 1.0 at all.

Changing to `Vector` would be more controversial IMHO.

**Review by armanbilge — APPROVED** [review]

**Comment by rossabaker** [comment]
Did those Vector improvements apply to 2.13?  The benchmarks were run on 3.1.1.  The last time I baked off `List` and `Vector`, `List` was a winner on traversals.

There was [this 2018 argument for Chain](https://typelevel.org/blog/2018/09/04/chain-replacing-the-list-monoid.html), but I don't imagine we use it semigroupally enough to justify the exotic Cats type.

**Comment by armanbilge** [comment]
Yes, the Scala 2.13 standard lib is shared with Scala 3. So the `Vector` benchmark should apply to both.

**Comment by danicheg** [comment]
So, with the power vested in me, I merge this. If someone wants to bring `Vector` somewhere, I believe we can do this iteratively.

**Pull request merged**
