### PR TITLE
Scala 2.13.6

### PR DESCRIPTION
**Pull request by aeons**
Bumps `kind-projector` via `sbt-spiewak` via `sbt-http4s-org` which allows us to upgrade scala to 2.13.6.

Also allows us to drop `sbt-dotty`

Closes #4839

### CODE REVIEW

**Comment by aeons** [comment]
This of course depends on 0.8.0 of sbt-http4s-org being on maven central.

**Comment by rossabaker** [comment]
Broken on #4828.  [Possibly relevant change](https://github.com/AdoptOpenJDK/openjdk-jdk/commit/e5866aa7560e1a6077a90a5902ec61de76922440)?

**Comment by rossabaker** [comment]
This could also refresh the mergify config.

**Comment by aeons** [comment]
That change is definitely it. That byte in the header is the only difference. 

However I disabled the failing test on jvm 16. Not sure why that didn't work

**Comment by rossabaker** [comment]
Because that was main (now series/0.23) and this is series/0.22.

**Comment by aeons** [comment]
Gah

**Comment by aeons** [comment]
I rewrote the gzip test to check the inflated bytes instead of the deflated ones, so it doesn't depend on fs2 and jvm agreeing on what OS we are supposed to be running on.

**Pull request merged**
