### PR TITLE
Issue/368

### PR DESCRIPTION
**Pull request by bryce-anderson**

### CODE REVIEW

**Comment by rossabaker** [comment]
When this came up last night, either @dcsobral had an objection, or I misunderstood.  I'd like to hear his take.

**Comment by dcsobral** [comment]
This is how I expected it to work, as far as I can see.

**Comment by bryce-anderson** [comment]
@rossabaker, with the input from @dcsobral is this good to merge?

As an aside, I believe the gitter discussion mentioned that the `pathPrefix` could be replaced with a `UriTranslation`, although I believe there was also some objection to that. I don't mind that change or any others that seem appropriate. I haven't actually been used these static content service helpers (yet) so I'm not 100% aware of the rough edges. I expect these helpers to evolve quite a bit in the (probably near) future so if there is something worth changing/adding/removing, any input would be helpful.

**Comment by rossabaker** [comment]
What is the use case of `pathPrefix` as opposed to consuming it with the prefix middleware?

**Comment by dcsobral** [comment]
To me, `pathPrefix` is equivalent to:

    case GET -> pathPrefix =>

Something that is inherent to the application, such as serving jQuery files at `/static/js`.

On the other hand, the stuff changing `pathInfo` (`URITranslation` or the mount point) are either composition tools (such as saying all services for A will be served at `/a`, the file server being one of them) or external configuration, such as a configuration file saying the prefix to all routes will be `/prefix`.

So if I have `/app/tools/static/js/angular.min.js`, that might be broken down as:

```
.mountService(Router.service, conf.prefix) // for conf.prefix == "/app"
...
// Router
val service = URITranslation("/clients")(Clients.service)
  .URITranslation("/tools")(Tools.service)
...
// Tools
val service = resourceService(Config(angularPath, "/static/js")
...
```

**Comment by bryce-anderson** [comment]
@dcsobral, I didn't mean to imply that we would remove that functionality, but perhaps just use the current tools such as `UriTranslation` to implement it. On the other hand, its already working (after this gets merged) so if its not broke, don't fix it.

Another things that may or may not get addressed is the DRYness of the different static content services.

At any rate, I think this is good to merge.

**Pull request merged**
