### PR TITLE
Simplify Service Worker API and make safe(r)

### PR DESCRIPTION
**Pull request by armanbilge**
My second stab at this after wrestling with similar design questions in [typelevel/feral](https://github.com/feral). Simplifies the API to a single self-contained method that suspends in `SyncIO`.

Fun fact: Service Workers are not only built-in proxy servers for the browser, but also the API adopted by Cloudflare's serverless edge workers.

### CODE REVIEW

**Comment by japgolly** [comment]
Just wanna say I think it's funny that you're got a `typelevel/feral`. Can I upload my kids?

**Comment by armanbilge** [comment]
Another one I'd love to see on Monday's release train. Pairs nicely with #5101 as part of a new-and-improved DOM API.

**Comment by rossabaker** [comment]
I am highly unqualified to review this, but I'll be the reviewer of last resort before the 1.0.0-M27 release.

**Comment by armanbilge** [comment]
@ChristopherDavenport said he's 👍 when green, which we are modulo some flaky JVM tests.

**Review by ChristopherDavenport — APPROVED** [review]

**Pull request merged**
