### PR TITLE
Deprecate `as` for `withContext`

### PR DESCRIPTION
**Pull request by rossabaker**
Surprise: https://github.com/lampepfl/dotty/issues/9829.

### CODE REVIEW

**Comment by hamnis** [comment]
not really a fan of `authedAs`. 
`contextAs` might be more general.
or just `context`

**Comment by rossabaker** [comment]
I wondered about `ContextRequest`.  The code is for `AuthedRequest`, so I stuck to something along those lines.  It could be more general, at some loss of readability.

`withContext`?  Additionally `withAuth`?  Readability is good, aliases are bad.

**Comment by rossabaker** [comment]
I don't love it, but want to get unblocked.

**Review by m-sp — APPROVED** [review]
mima seems to complain, otherwise lgtm

**Comment by rossabaker** [comment]
Dreary. Should we just roll this out in 0.22? There's no urgent need to purge `as`. It just won't work on Dotty.

**Comment by rossabaker** [comment]
Changing the base branch wasn't enough. Going to rebase.

**Comment by rossabaker** [comment]
Wait, is this [allowed again anyway](https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html#drop-as-in-patterns)?

**Comment by rossabaker** [comment]
This no longer appears to be necessary as of M3.

**Pull request closed without merging**
