### PR TITLE
MergeTrain release-0.15 -> 0.16

### PR DESCRIPTION
**Pull request by ChristopherDavenport**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
I'm working on a test as we speak. I will likely do PR's with Tests for the Apps once completed.

**Comment by ChristopherDavenport** [comment]
```
The command "bash bin/travis" exited with 1.
bin/travis: line 50:  2556 Terminated              sleep "$1"
```

**Comment by rossabaker** [comment]
Why is `bin/travis` running twice?  It succeeded once.

**Comment by bfritz** [comment]
Not sure, but that's the same thing I saw in #1097 .

**Comment by rossabaker** [comment]
I'd say it's happened at least once before, because I saw a build fail when the end said travis exited with 0.  I probably failed to notice that it exited with 1 on a prior run.

**Pull request merged**
