### PR TITLE
Merge `series/0.23` into `main`

### PR DESCRIPTION
**Pull request by danicheg**
There were a couple of files affected by merge conflicts. If I'm not wrong, these all changes belong to @armanbilge work. It'd be much appreciated if you'd reviewed this. 🙇🏻‍♂️

### CODE REVIEW

**Comment by armanbilge** [comment]
What were the merge conflicts, related to logging? I already solved some of those conflicts in https://github.com/http4s/http4s/pull/6645, specifically https://github.com/http4s/http4s/pull/6645/commits/a67269d7725dbad6278c0a9ba845414ca132fa2f.

**Comment by danicheg** [comment]
> related to logging? 

Yeah, logging and refactoring of the client test suite.

**Comment by armanbilge** [comment]
Ah right, the client suite would be because of the munit changes. I will check those.

**Review by armanbilge — APPROVED** [review]
Thanks! I looked at client tests which looks fine and skimmed everything else. I'm reworking logging on `main` in my other PR anyway.

**Pull request merged**
