### PR TITLE
rewrite AuthenticationSpec with munit

### PR DESCRIPTION
**Pull request by yanns**
follow-up of https://github.com/http4s/http4s/pull/4173

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
:+1: on green

**Comment by yanns** [comment]
The test `org.http4s.client.blaze.Http1ClientStageSuite` is flaky.

**Comment by rossabaker** [comment]
https://github.com/http4s/http4s/issues/4196 to discuss that one.  I think we invalidated an assumption and made a new flaky test.

**Comment by rossabaker** [comment]
We're trying to keep the tests as similar as we can across the active branches.  I'm going to see if I can cherry-pick this one back to 0.21, or failing that, 0.22, before merging.

**Comment by rossabaker** [comment]
That flaky test has been addressed in #4213.

**Pull request closed without merging**
