### PR TITLE
Added a copy of vault to proceed with CE3 upgrade

### PR DESCRIPTION
**Pull request by domaspoliakas**
As per the title

### CODE REVIEW

**Comment by domaspoliakas** [comment]
Running 2.12 tests with adopt 1.8 worked locally, so I'm not sure what's going on with ci there

**Comment by hamnis** [comment]
Server is not compiling, has that been converted to CE3 yet?

**Comment by domaspoliakas** [comment]
The PR for that seems to be open still. It's commented out in the module list in `build.sbt`, should it not get ignored when running CI?

**Comment by domaspoliakas** [comment]
It looks like someone re-ran CI and now it's good 🎊 

The DSL compiles and tests successfully in this as well without any changes to the source; should I uncomment it while I'm here, or leave it for a different PR?

**Comment by hamnis** [comment]
Maybe that should be its own PR.

**Review by hamnis — APPROVED** [review]

**Comment by hamnis** [comment]
perhaps a different take on this might be: https://eed3si9n.com/hot-source-dependencies-using-sbt-sriracha

**Comment by domaspoliakas** [comment]
I think I have one reservation to pursuing that strategy (provided I understood it correctly, which I may not have). Ultimately whether we copy the source or setup a source dependency, someone will have to go back and clean it up to just use a binary dependency again once vault has a version with ce3 published. And the benefit of using the source dependency is that the cleanup work would be trivial, whereas the copy method will involve cleaning up the classes too. However, because there are so few files involved in the copying, it might take overall less time to do the copying and cleaning up the files, than fiddling with source dependencies to get them right.

I'm no library maintainer however, so if you think that the source dependency path is the right way to go I'd be happy to get that working.

**Comment by rossabaker** [comment]
I think source dependencies are the right approach in theory, but I haven't had particularly good luck with them in practice, and this one is small enough for this crude approach to work.  Let's roll with this.

**Pull request merged**
