### PR TITLE
Upgrade to Scala 2.13.4 and 2.12.13

### PR DESCRIPTION
**Pull request by rossabaker**
Includes scalafix-0.9.25.   We were blocked with 0.9.24.

### CODE REVIEW

**Comment by rossabaker** [comment]
This version of scalafix is only for Scala 2.12.13, so throw that in, too.

**Comment by rossabaker** [comment]
Blocked by https://github.com/scalameta/mdoc/pull/445.

**Comment by m-sp** [comment]
If I understand the release notes for 2.12 correctly you can now delete https://github.com/http4s/http4s/blob/main/core/src/main/scala-2.12/scala/annotation/nowarn.scala

**Comment by rossabaker** [comment]
It's going to break MiMa if we clean that annotation up here, but we can do it in 0.22.

**Pull request merged**
