### PR TITLE
Support delimited encoders of streams of encodeable types.

### PR DESCRIPTION
**Pull request by rossabaker**
We can't provide a general `EntityEncoder[Process[Task, A]]` from `EntityEncoder[A]`, because we don't know anything about how to join a general `A` encoding.  But some formats have a natural monoid-like encoding.  For example, a stream of JSON values can be wrapped in a JSON array.

This provides an explicit helper for creating delimited entity encoders from simple entity encoders, and
provides them for our JSON libraries.

### CODE REVIEW

**Comment by rossabaker** [comment]
This scratches an itch, but doesn't feel quite right yet.  Suggestions welcome, and I won't hold up 0.10 over it, as much as I wanted to.

**Comment by bryce-anderson** [comment]
I don't see anything wrong with this PR, but also agree that it feels a bit 'funny'.

I don't care one way or the other if it gets merged not before we release 0.10.0. I'd like to get that out today barring any disasters.

**Comment by rossabaker** [comment]
I think my discomfort here is related to my discomfort with the current state of content negotation (i.e., we don't), and that's not a problem I'm prepared to hold up 0.10.x for.  Let's let this sit here and discuss, and proceed with the release.

**Comment by kryptt** [comment]
Does having
```scala
trait DelimitedEntityEncoder[A, Format] extends EntityEncoder[Process[Task, A]]
```
sound any better?

**Comment by rossabaker** [comment]
Is `EntityEncoder` maybe a specialization of a two-parameter encoder?

`type Encoder[A, B] = A => Task[B] // uh-oh, this is starting to look like another Kleisli`

1. Define `Encoder[Json, Entity]`
2. Define `Encoder[Process[Task, Json], Entity]`
3. Define `Encoder[A, Json]`
4. Compose our way to `Encoder[Process[Task, A], Entity]`

**Comment by kryptt** [comment]
I like it.

As a side note, it should be possible to stream json objects where the delimiters are (`{`, `,`, `}`) instead of (`[`, `,`, `]`). 

`Encoder[Process[Task, JsonAssoc], Entity]`
`Encoder[(JsonField, A), JsonAssoc]`
So it seems like it will allow us to compose to `Encoder[Process[Task, (JsonField, A), Entity]` here as well.

**Comment by rossabaker** [comment]
`EntityEncoder` is more than a `Kleisli`, so I think the last couple comments are nonsense.  Does anyone want to revive the original idea?

**Pull request closed without merging**
