### PR TITLE
Make client DSL more similar to server DSL

### PR DESCRIPTION
**Pull request by rossabaker**
* `Http4sClientDsl[F]` is like `Http4sClientDsl[F]`
* Create `io` object that extends `Http4sClientDsl[IO]`, like http4s-dsl has
* Don't extend `Http4sClientDsl[IO]` from client package, like http4s-dsl doesn't.

This is still not quite harmonious: http4s-dsl imports the status codes, whereas client doesn't.

### CODE REVIEW

**Comment by rossabaker** [comment]
As for whether this is even the right package, questions for which I have no answers:

- Are we continuing to assume that everyone who is creating requests is using the client?
- Are we continuing to assume that no second DSL will emerge for clients, as rho has for servers?

Discuss.

**Comment by aeons** [comment]
Should it maybe be moved to `org.https.client.dsl.io` as in the server dsl? (which is not in the server package, I know)

**Comment by rossabaker** [comment]
What's the preferred way to avoid a conflict with the io package? `Http4sDslIO`?

It only hurts if we import `dsl._`, not `dsl.io._`, right?  Is there any reason to import `dsl._` anymore?

**Comment by ChristopherDavenport** [comment]
I don't think you ever need dsl._ anymore. Only a specific import or io._

**Comment by rossabaker** [comment]
Given that, are we okay with the name?

I like `client.dsl._`, which makes me start to wonder about `server.dsl._`. 🤔

**Comment by rossabaker** [comment]
I refamiliarized myself with the build failure.  Last week was a long time ago for my old brain.  Yes, I think @aeons's suggestion on the package name resolves @ChristopherDavenport and Travis' concerns on the circe clash.

**Comment by ChristopherDavenport** [comment]
You appeased the test gods, but not the tut gods

**Pull request merged**
