### PR TITLE
added Ordering instance to QValue Class

### PR DESCRIPTION
**Pull request by san-coding**
Contributing to issue #5017 

added `Ordering` instance to `QValue` class

### CODE REVIEW

**Comment by san-coding** [comment]
@rossabaker @isomarcte , please review this, thanks

**Comment by san-coding** [comment]
what other classes require `Ordering` instance

**Comment by rossabaker** [comment]
`Ordering` can be implicitly derived from both `Ordered` and `cats.kernel.Order`.  I like doing these from the `Ordered`, because I'd like `Ordered` to go away.  But when there's already a `cats.kernel.Order`, those provide this, and are here to stay.

I think we should focus on providing missing `cats.kernel.Order` instances rather than continue with more of these.  Or identify more missing non-Order instances to learn more about type classes.  I'll start looking for some of these.

**Comment by san-coding** [comment]
> `Ordering` can be implicitly derived from both `Ordered` and `cats.kernel.Order`. I like doing these from the `Ordered`, because I'd like `Ordered` to go away. But when there's already a `cats.kernel.Order`, those provide this, and are here to stay.
> 
> I think we should focus on providing missing `cats.kernel.Order` instances rather than continue with more of these. Or identify more missing non-Order instances to learn more about type classes. I'll start looking for some of these.

Ohh alright, so I think we need not add it to `HttpVersion` ?
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/HttpVersion.scala#L30-L32

**Comment by san-coding** [comment]
### What about `Headers.scala`
https://github.com/http4s/http4s/blob/a942a83e2b88bafc644fc9916fd1979eb951ced8/core/shared/src/main/scala/org/http4s/Headers.scala#L26

**Comment by rossabaker** [comment]
I am not sure what an `Order` for `Headers` would be.  I can think of a few options, and if I can think of a few, perhaps none of them are appropriate.  I'll open a new ticket and tag you.

**Pull request merged**
