### PR TITLE
Propose API changes

### PR DESCRIPTION
**Pull request by tomasherman**

### CODE REVIEW

**Comment by hamnis** [comment]
Test failures are genuine, :+1: on fix

**Comment by tomasherman** [comment]
> Test failures are genuine, 👍 on fix

sure, working on it right now :)

**Comment by tomasherman** [comment]
not sure why `CI / Scala 2.12.10, Java adopt@1.8 (pull_request)` is failing at formatting stage

**Comment by tomasherman** [comment]
the failing test `org.http4s.client.asynchttpclient.AsyncHttpClientSpec` passes locally (using xcompilation `+testOnly`)

**Comment by hamnis** [comment]
from the formatting job. `PrometheusServerMetricsSpec.scala isn't formatted properly!`

try using `sbt scalafmtAll`

**Comment by tomasherman** [comment]
ah, i was only doing `scalafmt`

**Comment by tomasherman** [comment]
guys is this going to be merged? or should i do something?

**Comment by tomasherman** [comment]
Heh, no worries I understand. I wonder if maybe Middleware could follow
their own lifecycles. Thinking about extracting this into a 3rd party
module for faster improvements. Any thoughts on that?

**Comment by rossabaker** [comment]
We've discussed splitting the repo up along module boundaries, but I haven't considered going all the way to the middleware level.  I'm also aggressively backporting whatever is compatible, but that doesn't help you on this one.

I'd like to start publishing milestones off master for users who can accomodate more churn, which might scratch your itch.  Otherwise, a third-party module for the 0.21 lifecycle is probably the fastest way to start using this.

**Pull request merged**
