### PR TITLE
Bryce issue 436

### PR DESCRIPTION
**Pull request by bryce-anderson**
This PR is more or less a small refinement on the PR (#443) that @jedesah has offered up for issue #436. 

#### Similarities
* Both attempt to provide a way to choose if an `EntityDecoder` will make a YOLO attempt to decode a message or if they will require knowledge of the `content-type`. 
* Both are based on work by @jedesah: this PR shares the first two commits of #443.

#### Differences
* They differ in that this PR makes strictness a boolean flag on the `decode` method of `EntityDecoder` while #443 adds another method.
* In this PR an `EntityDecoder` that accepts `*/*` will decode a message that doesn't contain a `content-type` header.

### CODE REVIEW

**Comment by rossabaker** [comment]
Making strictness a property of decode feels right to me, but I'd like to hear from @jedesah.  The two of you have thought about this much more deeply than I.

**Comment by jedesah** [comment]
I don't have any strong feelings either way. I will try and find the time tonight to review this PR and then hopefully we can merge it.

**Comment by jedesah** [comment]
LGTM. I think this is a clear improvement over my PR! I look forward to getting rid of the dozen lines of code that simulates this behavior in Quasar with a single boolean! :smile:

**Comment by kryptt** [comment]
:+1: from my brief glance of this

**Comment by bryce-anderson** [comment]
Awesome, thanks for the review @kryptt and especially thanks to @jedesah for getting the ball rolling as well as writing the bulk of this PR. I'll delay merging this this evening in case someone wants to object.

**Comment by refried** [comment]
I think I understand now. :+1:

**Pull request merged**
