### PR TITLE
Cats parse 0.3.0

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Ready when it comes out.

### CODE REVIEW

**Comment by rossabaker** [comment]
This will need a scalafmt.

**Review by rossabaker — DISMISSED** [review]
Did you have to tweak this manually, or did the Scalafix do it all? Either way, after the scalafmt, this just worked. Tremendous work.

**Comment by rossabaker** [comment]
Almost:

```
[info] Set-Cookie parser should
[error]   ! parse a set cookie (432 ms)
[error]    org.http4s.ParseFailure: Invalid Set-Cookie header: Error(22,NonEmptyList(EndOfString(22,90))) (file:1)
[error]   ! default to None (431 ms)
[error]    org.http4s.ParseFailure: Invalid Set-Cookie header: Error(22,NonEmptyList(EndOfString(22,49))) (file:1)
[error]   ! parse a set cookie with lowercase attributes (430 ms)
[error]    org.http4s.ParseFailure: Invalid Set-Cookie header: Error(22,NonEmptyList(EndOfString(22,90))) (file:1)
[error]   ! parse with a domain with a leading dot (430 ms)
[error]    org.http4s.ParseFailure: Invalid Set-Cookie header: Error(23,NonEmptyList(EndOfString(23,33))) (file:1)
[info]   + parse with an extension (453 ms)
[info]   + parse with two extensions (453 ms)
[error]   ! parse with an two extensions around a common attribute (430 ms)
[error]    org.http4s.ParseFailure: Invalid Set-Cookie header: Error(34,NonEmptyList(EndOfString(34,61))) (file:1)
`````

**Comment by rossabaker** [comment]
Sorry for butting in, but I'm excited to get this one merged, and I think you're in a timezone where you should be asleep! :smile:

**Comment by martijnhoekstra** [comment]
> Did you have to tweak this manually, or did the Scalafix do it all? Either way, after the scalafmt, this just worked. Tremendous work.

I did have to make manual tweaks -- unfortunately, overlapping tree replacements fail, so `Parser.rep1(foo.string1)` gets jumbled to `foo.string1.repstring`, and `Parser.oneOf1(List(foo.string1, bar.string1)).string` gets jumbled to `Parser.oneOf(List(foo.string1, bar.string1))stringstring0stringstring`, and those need to be manually clean up, and sometimes imports need to be fixed if you had `import cats.parse.Parser` but not `Parser1`, and you use both the companion of Parser and the type. The thing you still had to fix was probably a mistake in the manual cleanup.

**Comment by rossabaker** [comment]
That all makes sense.  Well, thank you for both the manual and automated labor!

**Pull request merged**
