### PR TITLE
Release v0.22.11

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]

**Comment by rossabaker** [comment]
This branch is broken as of #5993, but it's a path issue that smells more like #5991... which passed.  I'm confused.

**Comment by armanbilge** [comment]
Huh? The problem I see there is
```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.2/docs/sbt-site-javadoc.jar: forbidden: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.3.2/docs/sbt-site-javadoc.jar
```

**Comment by rossabaker** [comment]
All the series/0.22 builds have been failing on `StaticFileSuite` since #5993 was merged, even though it wasn't obvious on the PR itself.

**Comment by armanbilge** [comment]
Seems like this one passed? https://github.com/http4s/http4s/commit/bf27e51f6c18b57eda6360aabf32d9391a64289c

**Comment by rossabaker** [comment]
Oh, it was during today's GitHub outage.  We shouldn't be requesting from a third party in our test suite.

**Pull request merged**
