### PR TITLE
Support for additional attributes on Jetty backend

### PR DESCRIPTION
**Pull request by CremboC**
This allows to set arbitrary parameters on the Jetty backend. Ideally, it would be a strongly typed map i.e. `Map[JettyPropertyName, AnyRef]` or perhaps even `List[JettyProperty]`, but I think this is fine for starters.

### CODE REVIEW

**Comment by CremboC** [comment]
Sorry, when I said `JettyPropertyName` I meant something like the following:
```scala
sealed abstract class JettyServletContextProperty(name: String)
case object MaxFormContentSize extends JettyServletContextProperty("maxFormContentSize")
case object MaxFormKeys extends JettyServletContextProperty("maxFormKeys")
```
etc.

**Comment by CremboC** [comment]
Also, I am looking into adding a test to see that this actually works.. Unfortunately there are (at least) two places where you can `setAttribute(s)` and I'm looking into the difference between them. I believe tests will help figure out which is the one we want.

Alternatively, I may expose the specific property e.g. `setMaxFormContentSize` instead of attributes - perhaps that will be clearer...

**Comment by rossabaker** [comment]
The nature of these attributes is that they accrue over time.  To seal it, we'd need a list, and then to stay in sync with Jetty releases, we'd have binary compatibility pains.  I like the instinct toward avoiding String types, but I think it's the best we can reasonably do here.

**Comment by armanbilge** [comment]
If interested, this PR should be retargeted to https://github.com/http4s/http4s-jetty.

**Pull request closed without merging**
