### PR TITLE
Setup munit dependencies and make boopickle use munit

### PR DESCRIPTION
**Pull request by cquiroz**
This is a replay of #3852 on `series/0.21`

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks like a legit compilation error.  Maybe a cats-effect-3 thing lingering?

**Comment by cquiroz** [comment]
Yes, a fix is coming soon

**Comment by rossabaker** [comment]
I can't remember. What piece do we need to keep the entity codec tests?

**Comment by cquiroz** [comment]
We need a `discipline-effect` type of library. I'm working on one but still have some loose ends.
It should contain a `checkAllF(...): IO[Unit]` method to check properties running in an effect

**Comment by rossabaker** [comment]
This has been explained to me about four times, but I haven't seen the compilation failure with my own eyes, so it hasn't sunk in.

Do you think we should merge this before that library arrives, or should we sit on this?

**Comment by rossabaker** [comment]
We could always keep a vestigiial BoopickleSpec next to the BoopickleSuite and not lose any test coverage until the integrations catch up.

**Comment by cquiroz** [comment]
Hmm, I guess we should wait, otherwise there is the temptation to keep porting tests with commented checks.

**Comment by rossabaker** [comment]
:+1: I don't want to lose this, though.  I think it's a better place to be long term.

**Comment by cquiroz** [comment]
I guess que could keep both the Spec and Suite for a while. My interest on munit is that it should theoretically be moving faster in the dotty world

**Comment by cquiroz** [comment]
Ok I restored the `Spec` part testing the `Codec` laws

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
