### PR TITLE
Processes should render with chunked encoding by default.

### PR DESCRIPTION
**Pull request by rossabaker**
Processes have unknown length until they run, making chunked
transfer encoding a sensible default.  This causes chunks to
be flushed as soon as they are emitted, which is the
intuitive behavior for a "streaming" response.

### CODE REVIEW

**Comment by rossabaker** [comment]
I'm considering this one a bug, though I can be talked into waiting on 0.11.

**Comment by rossabaker** [comment]
Attn: @ceedubs

**Comment by ceedubs** [comment]
:+1: Looks good to me. Thanks!

I don't think I'll weigh in on whether this should wait for a new version. I think that's best handled by the contributors and people using http4s in production :)

**Comment by bryce-anderson** [comment]
:+1: I've no strong opinion one way or the other as to whether this deserves a bugfix release or not. On one hand, it is a bug. On the other, there is a very trivial workaround.

**Pull request merged**
