### PR TITLE
Make all case classes final where possible. Fixes #643

### LINKED ISSUE #643: Make all case classes final
Non-final case classes are a bug because extending a case class is not a meaningful concept. All case classes should be made final.
If https://issues.scala-lang.org/browse/SI-4440 applies to a situation, a sealed case class with a justifying comment is acceptable.

### PR DESCRIPTION
**Pull request by gwils**
When a case class is nested inside a class or trait, it can only be sealed.

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1:

What do people think about wart remover to prevent these from sneaking back in?

**Comment by gwils** [comment]
In my opinion that requires some experimentation. I've found a few of the warts give false positives, so we'd need to figure out the right subset of warts, and whether each should run at error or warning level. For example, I'm not sure whether wartremover is smart enough to determine when a case class should be sealed instead of final.
Before going to wart remover, I think there are some quick wins to be had by turning on extra warnings, and making warnings errors as per https://www.youtube.com/watch?v=Es_JH3_64ys

**Comment by rossabaker** [comment]
Yes, I feel bad about having non-fatal warnings.  I don't know how to portably set a reason phrase on a servlet response without a deprecated method.

**Comment by gwils** [comment]
Wartremover won't allow sealed case classes if they're nested. We could make an issue on wartremover asking for that behaviour.
Why do we have nested case classes in the first case? What do they buy us? We could make them all non-nested and then turn on wartremover.

**Comment by refried** [comment]
wartremover doesn't seem to support pattern matching with current compilers, so I'm wary for now.
https://github.com/puffnfresh/wartremover/issues/175

**Comment by rossabaker** [comment]
Bad warts can always be turned off, but that can be a whole separate subject.

Barring quick objections, I'd like to merge this.

**Comment by bryce-anderson** [comment]
LGTM 👍

**Comment by rossabaker** [comment]
@gwils mentioned possibly moving things out of top-level to finalize more case classes.  I'm open to that idea, but like wart remover, we won't let that stand in the way of this good progress.  Merged, and thanks!

**Pull request merged**
