### PR TITLE
Added the possibility to specify custom responses to MessageBodyFailures

### PR DESCRIPTION
**Pull request by etorreborre**
I don't know if the test code can be simplified but hopefully it shows what's the intention with this feature.

cc @rossabaker

### CODE REVIEW

**Comment by rossabaker** [comment]
Does `response` even need to be an `Option`, or could it just be the function whose default is the `getOrElse` condition of `toHttpResponse`?

**Comment by etorreborre** [comment]
I wondered the same and decided for `Option` to emphasise the "optionality" of that thing. On the other hand it's probably better to do what you suggest at least for performance reasons. I'll change that.

**Comment by etorreborre** [comment]
Actually, the most practical thing is to use an `Option` because in the case of `UnsupportedMediaTypeFailure` the default response depends on the `expected` set of `MediaRanges` in a non-trivial way.

**Comment by rossabaker** [comment]
Hmm. Does it become awkward to define a custom response to the unsupported media types without access to  the media range set?  Should that be a function with that as a parameter?

**Comment by etorreborre** [comment]
@rossabaker after trying several possibilities, I propose an alternative design. Just add, on each level of the hierarchy a `final case class GenericXXXFailure` (see my last commit). This way we still retain:

 - somewhat precise typing: is it a parsing failure, a body failure?
 - a sealed hierarchy
 - ad-hoc customisation when needed
 - reuse of existing code, see the test case where I build a `GenericMessageBodyFailure` based on the existing `InvalidMessageBodyFailure`

I am not sure if there is a way to achieve all these goals at once. I decided against the default parameters route because in the case of the `UnsupportedMediaTypeFailure` the function to pass was starting to look a bit ugly and with a different signature than the other cases.

**Comment by rossabaker** [comment]
I see three use cases for rendering:
1. Don't care what it looks like, except maybe a status code.
2. Wants to render app-specific errors based on an established hierarchy.
3. Wants decoder-specific errors that generate more sensible defaults for that decoder.

Use Case 3 is the problem.

What if we keep `MessageFailure` sealed, but simply make the case classes like `ParseFailure` non-final?

* There's always a reasonable `.toHttpResponse`. (Solves Use Case 1)
* We still have a sealed hierarchy in which we can destructure `message` and `details` so an app can recover with a custom response before the server calls `.toHttpResponse`. (Solves Use Case 2, Use Case 1 still works.)
* Decoders would have the freedom to create their own default responses by subclassing a case class.  That's something we usually avoid in Scala, but you'd have full access to the standard fields to construct your response. (Solves Use Case 3, Use Cases 1 and 2 still work.)

**Comment by etorreborre** [comment]
Is there something in particular you don't like in my last commit? The hierarchy is still here and no case classes were harmed. I don't like the idea of making case classes non final because this means that we can never attain a warning-free library state (now that warning becomes a feature). Also I am not sure that case classes are not going to be made final anyway in future Scala releases (I think I read a hint about this).

**Comment by rossabaker** [comment]
Oh, I didn't realize that case classes extended by non-case classes were on their way out.

In `GenericParsingFailure`, the `details` field is lost.  The intent of `details` is that it can carry information appropriate for an error log, but inappropriate for inclusion in the response.  The original pull request or the non-final case class approach allow customization of the `toHttpResponse` without losing the details.

This is similar to my last idea, but at least seals the case classes.  (If this is going away in a future Scala, it's also maybe not a good idea, but I'll throw it out there):

```scala
sealed abstract case class ParseFailure private (sanitized: String, details: String) {
  def toHttpResponse(version: HttpVersion): Task[Response]
}

object ParseFailure {
  def apply(sanitized: String, details: String) = 
    new ParseFailure(sanitized, details) {
      def toHttpResponse(version: HttpVersion) = 
        Response(Status.BadRequest, httpVersion).withBody(sanitized)
    }

  def apply(sanitized: String, details: String, responder: HttpVersion => Task[Response]) =
    new ParseFailure(sanitized, details) {
      def toHttpResponse(version: HttpVersion) = responder(version)
    }
}
```

**Comment by etorreborre** [comment]
I added back the `sanitized` and `details` fields on `GenericParsingFailure` (with the same message as `ParseFailure`). Note that I am actually only interested in `GenericDecodeFailure` because this is the type required by `EntityDecoders`. So we might just keep this one for now if you feel unsure about the others.

**Comment by rossabaker** [comment]
Moving conversation back from Gitter:

I think this PR and my proposal are very close now.  Yours has the advantage of avoiding the unusual `sealed abstract case class`, and mine has the advantage of not adding another layer to an already deep subclass hierarchy.  I like both ideas better than the current master.  Does anybody else have a strong argument for or against one approach?

**Comment by rossabaker** [comment]
From Gitter:

> I really tried other alternatives to avoid subclassing case classes by adding a new response member to the failures. The problem is that it breaks the case class behaviour in terms of apply/unapply/equality. So the only alternative I see now would be to not use case classes but final classes with a response member and code manually all the case class methods apply/unapply/equal/hashCode/copy. This also looks a bit crazy to me in terms of complexity (and error-prone).

My first idea handles apply/unapply/equal/hashCode, but not copy:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

sealed abstract case class ParseFailure (sanitized: String, details: String) {
  def toHttpResponse(version: HttpVersion): Task[Response]
}

object ParseFailure {
  def apply(sanitized: String, details: String) = 
    new ParseFailure(sanitized, details) {
      def toHttpResponse(version: HttpVersion) = 
        Response(Status.BadRequest, version).withBody(sanitized)
    }

  def apply(sanitized: String, details: String, responder: HttpVersion => Task[Response]) =
    new ParseFailure(sanitized, details) {
      def toHttpResponse(version: HttpVersion) = responder(version)
    }
}

// Exiting paste mode, now interpreting.

defined class ParseFailure
defined module ParseFailure

scala> ParseFailure("msg", "deets")
res25: ParseFailure = ParseFailure(msg,deets)

scala> ParseFailure("msg", "deets", v => Task.now(Response()))
res26: ParseFailure = ParseFailure(msg,deets)

scala> res25 == res26
res27: Boolean = true

scala> res25 match { case ParseFailure(msg, details) => details }
res28: String = deets

scala> res26 match { case ParseFailure(msg, details) => details }
res29: String = deets

scala> res25.copy(details = "more deets")
<console>:17: error: value copy is not a member of ParseFailure
              res25.copy(details = "more deets")
```

A second case class parameter list gives an ambiguous apply:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

case class ParseFailure private (sanitized: String, details: String)(toHttpResonse: HttpVersion => Task[Response])

object ParseFailure {
  def apply(sanitized: String, details: String) = 
    new ParseFailure(sanitized, details)({ version =>
      Response(Status.BadRequest, version).withBody(sanitized) 
    })

  def generic(sanitized: String, details: String)(toHttpResponse: HttpVersion => Task[Response]) =
    new ParseFailure(sanitized, details)(toHttpResponse)
}

// Exiting paste mode, now interpreting.

defined class ParseFailure
defined module ParseFailure

scala> ParseFailure("msg", "deets")
<console>:16: error: ambiguous reference to overloaded definition,
both method apply in object ParseFailure of type (sanitized: String, details: String)(toHttpResonse: org.http4s.HttpVersion => scalaz.concurrent.Task[org.http4s.Response])ParseFailure
and  method apply in object ParseFailure of type (sanitized: String, details: String)ParseFailure
match argument types (String,String)
              ParseFailure("msg", "deets")
```

I might finally be coming around to the idea of the deeper types, as hard as I tried to avoid them.  But I think we have now lost the ability to extract `ParseFailure` regardless of whether there is a custom responder.  Would it make sense to add an `unapply` to the abstract classes to preserve this?

**Comment by rossabaker** [comment]
I still wish we could have avoided introducing new types, but neither of us can make it work, and @etorreborre points out that this is a minimal change.  Let's unblock that use case, and if something prettier comes along later, we can always change it again.  Merging.,

**Pull request merged**
