### PR TITLE
Update all the urls to new http4s-dom site

### PR DESCRIPTION
**Pull request by armanbilge**
I case you missed it, it has a live example of http4s in the browser! 😁 
https://http4s.github.io/http4s-dom

### CODE REVIEW

**Comment by rossabaker** [comment]
Do you want it here, or do you want a subdomain on http4s.org?

**Comment by armanbilge** [comment]
Sure, a subdomain would be cool, but this is fine too.

**Comment by rossabaker** [comment]
I'm good with this until the subdomain is set up.  Is the breakage that other issue you fixed?

**Comment by armanbilge** [comment]
Yeah, this inherited a bad main but should be fixed now.

**Pull request merged**
