### PR TITLE
Change Charset decoder to use fs2

### PR DESCRIPTION
**Pull request by agustafson**

### CODE REVIEW

**Comment by agustafson** [comment]
Yeah I had the same thought. I'll add a failing test and change to use mapAccumulate.

**Comment by rossabaker** [comment]
Could be a good use case for a property test:
- Take arbitrary String
- Split into arbitrary chunks
- Decode to original String

Doing this with arbitrary charsets is tricky, because not all arbitrary strings work in arbitrary charsets.  But even if this just did UTF-8, it might raise confidence.

**Comment by agustafson** [comment]
Yeah good shout. I don't think there's a UTF-8 generator in scalacheck, but I had created one for just ascii: https://github.com/rickynils/scalacheck/pull/312
I'll look at creating a UTF-8 generator here and also submit it to scalacheck.

**Comment by rossabaker** [comment]
That revived spec looks right.  I'd say when that passes, we'll have a high degree of confidence.

**Pull request closed without merging**
