### PR TITLE
downgrade fs2 to 0.10.0-M10

### PR DESCRIPTION
**Pull request by wedens**
Downgrades fs2 to the latest version without the [translate bug](https://github.com/functional-streams-for-scala/fs2/issues/1070).

### CODE REVIEW

**Comment by aeons** [comment]
Needs scalafmt it looks like :)

**Comment by wedens** [comment]
I've fixed scalafmt business 🙂

**Comment by wedens** [comment]
We can wait and see what'll happen with https://github.com/functional-streams-for-scala/fs2/pull/1073. Let's hope it does fix the issue and we'll get a new milestone soon.

**Comment by ChristopherDavenport** [comment]
I believe this is the case. We will get a release up ASAP after the next fs2 release. Feel free to reopen if you think its necessary.

**Pull request closed without merging**
