### PR TITLE
Scala 3.0.0

### PR DESCRIPTION
**Pull request by rossabaker**
Broken on Scala 3, but so is the main branch.

Missing:
* [x] blaze (https://github.com/http4s/blaze/pull/531)
* [x] case-insensitive (https://github.com/typelevel/case-insensitive/pull/153)
* [x] vault (https://github.com/typelevel/vault/pull/234)
* [x] unique (https://github.com/typelevel/unique/pull/191)
* [x] log4s (https://github.com/Log4s/log4s/pull/76)
* [x] keypool (https://github.com/typelevel/keypool/pull/211)
* [x] jawn-fs2 (https://github.com/typelevel/jawn-fs2/pull/204)

### CODE REVIEW

**Comment by rossabaker** [comment]
Some nonsense about this:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala3-library_3.0.0:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/ross/.ivy2/local/org.scala-lang/scala3-library_3.0.0/3.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3.0.0/3.0.0/scala3-library_3.0.0-3.0.0.pom
[error]   not found: https://jcenter.bintray.com/org/scala-lang/scala3-library_3.0.0/3.0.0/scala3-library_3.0.0-3.0.0.pom
```

We're blocked on a final release without a Circe release.

**Comment by Kevin-Lee** [comment]
This `org.scala-lang/scala3-library_3.0.0/3.0.0` should be `org.scala-lang/scala3-library_3/3.0.0`. It might be because of some plugin used by http4s. 
I don't think you need `sbt-dotty` anymore. Could you try sbt `1.5.2` instead? Or let me see if I can help anything after work today.

**Comment by aeons** [comment]
PRs up for [case-insensitive](https://github.com/typelevel/case-insensitive/pull/153) and [vault](https://github.com/typelevel/vault/pull/233).

I hit the same issue where something pulls in an old version of `sbt-dotty` which makes resolution fail.

**Comment by aeons** [comment]
PR for [blaze](https://github.com/http4s/http4s/pull/4830) is up, but it's missing a log4s dependency.

**Comment by Kevin-Lee** [comment]
@aeons I think it will be released soon. 
- https://github.com/Log4s/log4s/pull/75
- https://github.com/Log4s/log4s/pull/76

**Comment by aeons** [comment]
Yes, I linked to that from the blaze PR :)

There might be an issue with the build pipeline though, since the RC Ross made yesterday is not on maven central.

**Comment by aeons** [comment]
The PR I made for `vault` was for the CE3 branch. Now there's one for the CE2 branch as well: https://github.com/typelevel/vault/pull/234

That depends on a release of `unique` though: https://github.com/typelevel/unique/pull/191

**Comment by aeons** [comment]
There should be PRs up for all dependencies now.

**Comment by aeons** [comment]
All that's missing now are releases of vault and blaze.

**Comment by Kevin-Lee** [comment]
I think vault is available now but I get this when I `sbt compile` on my local machine.
```
[error] Symbol 'type org.http4s.jawn.JawnInstances' is missing from the classpath.
[error] This symbol is required by 'package org.http4s.jawn.package'.
[error] Make sure that type JawnInstances is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of org.http4s.jawn.
[error] one error found
[error] stack trace is suppressed; run last blaze-core / update for the full output
[error] (jawn / Compile / compileIncremental) Compilation failed
[error] (blaze-core / update) sbt.librarymanagement.ResolveException: Error downloading org.http4s:blaze-http_2.13:0.15.0
```

**Comment by rossabaker** [comment]
jawn is weirdness from package object inheritance, and a clean should fix that.

I'll check on the blaze release.

**Comment by rossabaker** [comment]
https://github.com/http4s/blaze/issues/505 ate blaze despite an attempted fix.  I'm just publishing it manually from the tag.

**Comment by Kevin-Lee** [comment]
@rossabaker Thanks! Yeah I also just found that `blaze-http` `0.15.0` is not released.

**Comment by Kevin-Lee** [comment]
> Some nonsense about this:
> 
> ```
> [error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala3-library_3.0.0:3.0.0
> [error]   Not found
> [error]   Not found
> [error]   not found: /home/ross/.ivy2/local/org.scala-lang/scala3-library_3.0.0/3.0.0/ivys/ivy.xml
> [error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3.0.0/3.0.0/scala3-library_3.0.0-3.0.0.pom
> [error]   not found: https://jcenter.bintray.com/org/scala-lang/scala3-library_3.0.0/3.0.0/scala3-library_3.0.0-3.0.0.pom
> ```
> 
> We're blocked on a final release without a Circe release.

@rossabaker Just FYI, I think I found the reason why this happened.
When I do `show scalaBinaryVersion`, I get `3.0.0` but it should be `3`. I found one of the plugins used in http4s overrides it.
I think It's `dotty.tools.sbtplugin.DottyPlugin` used by `SpiewakPlugin`. I can see the [`DottyPlugin` was dropped](https://github.com/djspiewak/sbt-spiewak/pull/54) from `sbt-spiewak` but I don't think the new one was released yet.

**Comment by aeons** [comment]
Yeah, that's the issue. I created https://github.com/djspiewak/sbt-spiewak/issues/55

**Comment by aeons** [comment]
It now fails on the `unusedCompileDependenciesTest` with a lot of false positives.

```
[warn] scalatags >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "com.lihaoyi" % "scalatags" % "0.9.4"
[warn] boopickle >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "io.suzaku" % "boopickle" % "1.3.3"
[warn] twirl >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "com.typesafe.play" % "twirl-api" % "1.5.1"
[warn] play-json >>> The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "com.typesafe.play" % "play-json" % "2.10.0-RC2"
[error] (play-json / unusedCompileDependenciesTest) Failing the build because unused dependencies were found
[error] (twirl / unusedCompileDependenciesTest) Failing the build because unused dependencies were found
[error] (scalatags / unusedCompileDependenciesTest) Failing the build because unused dependencies were found
[error] (boopickle / unusedCompileDependenciesTest) Failing the build because unused dependencies were found
```

**Comment by Kevin-Lee** [comment]
It doesn't look like GitHub Actions is functioning (again 😔).

**Comment by aeons** [comment]
Yeah, I have tried canceling and restarting a couple of times.

**Comment by rossabaker** [comment]
Oh, the unused compile dependencies are the things we use withDottyCompat for so we can compile them until there's a proper release.  I'll change it to opt out on the Scala 3 build.  That check has saved us from bugs a few times, and I'd really like to keep it.

**Comment by aeons** [comment]
Yeah, it is alteret disabled on scala 3. The errors showed on 2.12 and 2.13.

**Comment by rossabaker** [comment]
Oh.  Well, nuts.  Hopefully it's only a temporary thing, then.

**Comment by aeons** [comment]
The build failures now are the moved blaze client stuff, so I guess this is good to go. 
@rossabaker

**Comment by Kevin-Lee** [comment]
@rossabaker I'm not sure if it's actually an issue but I got this when I tested this branch locally. #4848

**Pull request merged**
