### PR TITLE
Add sonatypeRelease to the publish script

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
I'd like to also be using sbt-release, but I haven't thought through the complexities in automatically bumping the version with the scalaz cross build suffix.

**Comment by bryce-anderson** [comment]
Does this change release _all_ the artifacts, eg all scalaz versions etc?

**Comment by rossabaker** [comment]
Yes, if they're already publishSigned.  I used this on 0.14.3(a).

**Comment by bryce-anderson** [comment]
Sounds good. 👍

**Pull request merged**
