### PR TITLE
Remove jetty scaffold

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks like I broke some things in jetty-client.

**Comment by aeons** [comment]
```
2021-05-28 16:27:40.912Z  warn [httpserver] sendResponseHeaders: rCode = 204: forcing contentLen = -1 
==> X org.http4s.jetty.client.JettyClientSuite.JettyClient Execute GET  0.049s java.io.EOFException: HttpConnectionOverHTTP@67cbd127::SocketChannelEndPoint@171afc34{l=/127.0.0.1:50616,r=localhost/127.0.0.1:36117,ISHUT,fill=-,flush=-,to=0/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@67cbd127(l:/127.0.0.1:50616 <-> r:localhost/127.0.0.1:36117,closed=false)=>HttpChannelOverHTTP@56e73ba8(exchange=HttpExchange@46d92453{req=HttpRequest[GET /simple HTTP/1.1]@628daedc[TERMINATED/null] res=HttpResponse[null 0 null]@22b615e5[PENDING/null]})[send=HttpSenderOverHTTP@4de35060(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@42971e33{s=START}],recv=HttpReceiverOverHTTP@4de3b3f3(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
```
Something with `Content-Length` of `204` responses in `com.sun.net.httpserver`?

**Comment by rossabaker** [comment]
I think that's unrelated, but it would be good to clean up.

**Comment by aeons** [comment]
Dunno why, but making each `$client execute GET` into a separate test made this one non-flaky, both locally, and in CI.

**Comment by rossabaker** [comment]
Well, that's puzzling.  It shouldn't affect connection reuse or parallelism.  We may be abusing the life cycle of that `HttpHandler`.  But let's see how it goes.

**Pull request merged**
