### PR TITLE
Added Ordering instance for ProtocolParameter trait

### PR DESCRIPTION
**Pull request by san-coding**
Contributing to Issue #5017 

Added `Ordering` instance to `ProtocolParameter` trait

### CODE REVIEW

**Comment by san-coding** [comment]
@isomarcte @rossabaker , thanks for the guidance and detailed explanations, I have added `Ordering` instance to `ProtocolParameter` trait  , can you review if whatever I have done is correct ?

**Comment by san-coding** [comment]
As expected Formatting checks have failed, @rossabaker could you help me out with the
 `sbt scalafmt` commit , thanks

**Comment by hamnis** [comment]
@san-coding try running `sbt scalafmtAll`

**Comment by san-coding** [comment]
> @san-coding try running `sbt scalafmtAll`

Hey @hamnis , I know that running `sbt scalafmtAll` would solve the issue, but i am using Mac with apple silicon M1 chip,  and `sbt`  is compatible only with intel machines, so I am unable to run it, maybe you could help me out here by running `sbt scalafmtAll` and committing to this PR

**Comment by san-coding** [comment]
Thanks @hamnis  , why is this CI check alone is failing ? @rossabaker @isomarcte @hamnis  
Continuous Integration / Build and Test (ubuntu-latest, 3.0.1, adopt@1.8, ciNodeJS) (pull_request) Failing after 16m — Build and Test (ubuntu-latest, 3.0.1, adopt@1.8, ciNodeJS)

**Comment by hamnis** [comment]
Probably some flakiness. I have seen it fail before.

**Comment by san-coding** [comment]
> Probably some flakiness. I have seen it fail before.

Can you explain what you mean by flakiness, I am new here

**Comment by hamnis** [comment]
A flaky test means that it fails sometimes, by which reason may be hard to find. That might be high load on CI server, or a host of other different reasons.
I cant see anything in this PR that should contribute to this particular test flakiness. Dont worry about this.

**Comment by san-coding** [comment]
> A flaky test means that it fails sometimes, by which reason may be hard to find. That might be high load on CI server, or a host of other different reasons.
> I cant see anything in this PR that should contribute to this particular test flakiness. Dont worry about this.

Oh Okay, thanks for pointing it out @hamnis

**Comment by san-coding** [comment]
@rossabaker @isomarcte , please review this, thanks

**Review by hamnis — APPROVED** [review]

**Review by isomarcte — APPROVED** [review]

**Comment by san-coding** [comment]
@hamnis can you once help me out with the `sbt scalafmtAll` commit

**Comment by san-coding** [comment]
Sorry for re - requesting review, haven't changed anything , have reverted the commit I made after this PR was approved, so need not review again since it has been approved, can be merged if everything is correct

**Comment by rossabaker** [comment]
I think this can be added in 0.22.  I'll try cherry picking.

**Comment by san-coding** [comment]
@isomarcte , yes it was indeed a flaky test, it passed this time 😄

**Comment by san-coding** [comment]
> I think this can be added in 0.22. I'll try cherry picking.

@rossabaker You mean cherry picking commits ? I think the whole PR can be merged because it has only 1 file that has been changed, the other commit which failed to pass CI checks has been reverted, so now everything works fine

**Comment by rossabaker** [comment]
When things are binary compatible, we like to start them on series/0.22, so people can use them sooner.  When a PR comes in and targets main and could have targeted series/0.22., I usually cherry-pick it back.  And then it ends up on main when I merge everything forward.  This way, it will be in the next 0.22, 0.23, and 1.0 release.

**Comment by san-coding** [comment]
Ohh okay @rossabaker , meanwhile I will add `Ordering` instances to other classes that extend `Ordered`

But in the case of HttpDate , how do I define `Ordering` instance
```
class HttpDate private (val epochSecond: Long) extends Renderable with Ordered[HttpDate] { /* elided */ }

object HttpDate {
    implicit val stdLibOrderingInstance: Ordering[HttpDate] = WHAT.toOrdering
}


```
Should It be `epochSecond.toOrdering`

**Comment by rossabaker** [comment]
Can you use the Cats instance?  `Order[HttpDate].toOrdering`?

**Comment by san-coding** [comment]
> Can you use the Cats instance? `Order[HttpDate].toOrdering`?

Ok I will do it , will create a new PR for `HttpDate`

**Comment by san-coding** [comment]
@rossabaker  PR for `HttpDate` should target which branch ?

**Comment by san-coding** [comment]
Sorry i opened the above PR by mistake

**Comment by san-coding** [comment]
> I think this can be added in 0.22. I'll try cherry picking.

Does this have tests ?

**Comment by rossabaker** [comment]
I don't think this one had tests.  It's easier to test Cats, because we can use those laws that you added.  I'm not sure that anybody has written laws for the standard `Ordering`.

**Comment by san-coding** [comment]
> I don't think this one had tests. It's easier to test Cats, because we can use those laws that you added. I'm not sure that anybody has written laws for the standard `Ordering`.

Ohh , okay should they be added ? any changes has to be made to this PR ?

**Pull request closed without merging**
