### PR TITLE
Add status 418 I'm a Teapot

### PR DESCRIPTION
**Pull request by bplommer**
Adds status `418 I'm a Teapot` in accordance with [RFC 2324](https://datatracker.ietf.org/doc/html/rfc2324#section-2.3.2)

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Relevant RFCS - 
https://datatracker.ietf.org/doc/html/rfc2324#section-2.3.2
https://datatracker.ietf.org/doc/html/rfc7168#section-2.3.3

May be scope creep, but may need appropriate media types to respond to to HTCPCP-TEA protocol.

**Comment by bplommer** [comment]
> May be scope creep, but may need appropriate media types to respond to to HTCPCP-TEA protocol.

Maybe this should go in a separate module? `http4s-teapot`?

**Comment by rossabaker** [comment]
Sadly the [standardization process](https://tools.ietf.org/id/draft-nottingham-thanks-larry-00.html) failed, but I'm not about to stand idly while the Python, Node, and Go folks get to use it.

> Maybe this should go in a separate module? http4s-teapot?

Surely `htcpcp4s`.

**Review by ChristopherDavenport — APPROVED** [review]

**Comment by rossabaker** [comment]
The serious reason to merge this is that some HTTP servers in the wild do return it, even when not controlling a coffee pot.  The other serious reason is that [Emacs has a proper HTCPCP client](http://emarsden.chez.com/downloads/coffee.el), and Emacs is better than whatever you all use.

**Comment by rossabaker** [comment]
Cherry-picked to 0.22.

**Pull request closed without merging**
