### PR TITLE
Make queue full exception specific

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Weird place for the model though. Do we instead want it in an errors or in the companion object?

**Comment by rossabaker** [comment]
`NoConnectionAllowedException` is already in the same place.  We could bikeshed that, but as with one, with the other.

**Comment by SystemFw** [comment]
Is this ready for merge, or should I bring some paint? :)

**Comment by rossabaker** [comment]
@keirlawson asked about 0.18 support.  I think we should cherry-pick rather than merge.

**Comment by rossabaker** [comment]
Cherry picked onto release-0.18.x, merged back to master.

**Pull request closed without merging**
