### PR TITLE
Upgrade to scalaz-stream-0.7a.

### LINKED ISSUE #237: Upgrade to scalaz-stream-0.7a
It's out.  Let's do it.

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #237.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Do you mind if I push a fix for the broken test?

**Comment by rossabaker** [comment]
Go for it. I haven't had a chance to look.

**Comment by bryce-anderson** [comment]
I think this is good to go, but someone should double check my two commits. Sorry there were two, but I had an epiphany and felt compeled to do a second commit.

**Comment by rossabaker** [comment]
Oops, that's what I get for not cleaning. :+1:

**Pull request merged**
