### PR TITLE
Add and Use Literally 

### LINKED ISSUE #4600: Use Literally
We'll be inheriting this soon from ip4s anyway, so there's no extra dependency liability, and it clean things up for us.

See https://github.com/Comcast/ip4s/pull/261 for an example.

### PR DESCRIPTION
**Pull request by kevinmeredith**
Closes #4600 

Picks off from https://github.com/http4s/http4s/pull/4616.

### CODE REVIEW

**Comment by kevinmeredith** [comment]
Please review, @rossabaker. Thanks

**Comment by kevinmeredith** [comment]
Hi @ChristopherDavenport and @mpilquist - could you please take a look? Thanks for your time

**Review by rossabaker — APPROVED** [review]
Looks good. Thanks!

**Comment by kevinmeredith** [comment]
Thanks, Ross!

**Pull request merged**
