### PR TITLE
Remove deprecated header forwards

### PR DESCRIPTION
**Pull request by bryce-anderson**
We shouldn't be needing these anymore.

### CODE REVIEW

**Comment by rossabaker** [comment]
The hope is nobody leaps from 0.5 to 0.7 without stopping over 0.6?  Probably true.  I guess it's an easy enough transition.

**Comment by bryce-anderson** [comment]
We are pre-alpha: I don't see any reason to keep deprecated stuff around for more than one release. 
Is this good to merge?

**Comment by rossabaker** [comment]
Yeah, I only did it this time because it was a drastic change.

**Comment by bryce-anderson** [comment]
It was a good idea: I agree that we should try and do that for dramatic changes if possible.

**Pull request merged**
