### PR TITLE
Remove laziness from arbitraries

### PR DESCRIPTION
**Pull request by rossabaker**
I turned on monitor watching in yourkit.  On my laptop, we blocked threads on `genStandardMethod` hundreds of times.  All of these lazy values could be locking test suites.

If we go this route, we have to be careful about the ordering of the values.  In a trait, scalac doesn't flag questionable forward references.

### CODE REVIEW

**Comment by rossabaker** [comment]
It's passed several times in a row on 0.16.0.  We did get one [strange build](https://travis-ci.org/http4s/http4s/jobs/236814190).  A few threads are blocked on line 81 of ArbitraryInstances, and I'm not clear why.

**Comment by rossabaker** [comment]
Every val needs to be initialized before anything that uses it, or we will get an NPE.  This is why a couple generators had to be moved down the file.  That's something we'll usually catch ourselves.

A user who overrides one of these generators will have a bad time.  This is an unlikely use case, but one that worked with lazy.  I guess we could make all the vals final.

```
scala> class Oops extends testing.ArbitraryInstances { override val genTchar = oneOf(Seq('a', 'b', 'c')) }
defined class Oops

scala> (new Oops).genToken.sample
java.lang.NullPointerException
  at org.scalacheck.Gen$.$anonfun$sequence$2(Gen.scala:429)
```

**Comment by ChristopherDavenport** [comment]
Barring outrage, this is bound to lead to more hassles if people do try to override. 

I'm in favor of finalizing.

**Comment by rossabaker** [comment]
Devil's advocate:

- If someone does it wrong, it's going to fail in tests.  Production code won't be using it.
- If someone has a particular itch, we don't prevent them from scratching it.  Early initializers still work:

```scala
scala> class Oops extends { override val genTchar = oneOf(Seq('a')) } with testing.ArbitraryInstances
res0: Option[String] = Some(aa)
```

**Pull request merged**
