### PR TITLE
Upgrade to fs2-2.2.1

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes some bincompat issues exposed in 2.2.0.

### CODE REVIEW

**Comment by hamnis** [comment]
Exception in thread "specs2-2" java.lang.NoSuchMethodError: fs2.Stream.free()Lfs2/internal/FreeC;
	at jawnfs2.package$.$anonfun$parseJson$6$adapted(package.scala:46)

**Comment by rossabaker** [comment]
jawn-fs2-1.0.0-RC1 is compiled against fs2-2.2.0.  Is fs2-2.2.1 not compatible with both?  I didn't follow along closely enough.

**Comment by rossabaker** [comment]
https://github.com/http4s/jawn-fs2/pull/91

**Comment by rossabaker** [comment]
The next build will fail, because I haven't released jawn-fs2 yet, and that laptop is downstairs.  But I'll do that soon, and then this should pass.

**Pull request merged**
