### PR TITLE
Added implicit (String, String) => Header

### PR DESCRIPTION
**Pull request by reactormonk**

### CODE REVIEW

**Comment by rossabaker** [comment]
Implicit conversions make me a little nervous unless it's to add postfix syntax.  Maybe an overload of `apply` to take a (String, String)` and/or an overload of `putHeaders` to enable a `putHeaders("X-One" -> "1", "X-Two" -> "2")` type of syntax?

**Comment by ritschwumm** [comment]
bad idea for two reasons
- implicit conversions generally lead to more trouble than its worth
- each header might be a pair of strings, but not every pair of strings is a header. what if the first string is empty?

**Comment by reactormonk** [comment]
> implicit conversions generally lead to more trouble than its worth
Some nice syntax from Play, but I see why you're reluctant.

> each header might be a pair of strings, but not every pair of strings is a header. what if the first string is empty?
I'm just calling `Header.apply`, which should do all that validation.

**Comment by rossabaker** [comment]
Closing due to Fear Of Implicits.  We can still consider the proposed overloads to achieve the same effect elsewhere.  Thanks!

**Pull request closed without merging**
