### PR TITLE
Add Support For JDK 9 and Bump Tomcat Version

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Java Version 9 is rolling out shortly so ensuring we are capable of moving forward with 0.17 makes sense. 

Tomcat version needed to be upgraded for version 9 support. However, I am open to other ideas if we want to avoid tomcat 9 for some reason.

Versioning was taken from sbt/sbt#2951 and continued coverage of scala support is at scala/scala-dev#139

### CODE REVIEW

**Comment by rossabaker** [comment]
Why does Java 9 not work with Tomcat 8? I can't find a reference.

**Comment by ChristopherDavenport** [comment]
Primarily because I believe I conflated it with another error erroneously. It errored when I built it originally, tried to revert to reproduce and everything worked.

 Is there a reason we havn't upgraded out of the superseded `8.0.43` to `8.5.13`?

**Comment by rossabaker** [comment]
Yes, #639, which I think is now resolvable without much effort.

**Comment by ChristopherDavenport** [comment]
Tomorrow morning I will revert the version commits and see if we can get it
running. Seems likely it will work since it passed on 9

**Comment by ChristopherDavenport** [comment]
Bumping to recent version of Tomcat `8.5.13` seems to have passed local unit tests and my travis setup.

Fixes #639

**Comment by rossabaker** [comment]
I think I'm going to change the project description to "It Works in My Travis".

```
java.lang.NumberFormatException: For input string: "14-RC1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:695)
	at java.base/java.lang.Integer.parseInt(Integer.java:813)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at com.earldouglas.xwp.ContainerPlugin$$anonfun$6.apply(ContainerPlugin.scala:150)
```

This looks like ContainerPlugin not being able to handle sbt release candidates, doesn't it?

**Comment by bfritz** [comment]
Random thoughts:
* I like the idea of testing JDK9.
* Do we intend to support 0.16.x on JDK9?  If so, should we target release-0.16.x ?
* Given that Travis is already finicky with http4s builds, it concerns me that the JDK9 build is so different from others.  E.g. runs in Ubuntu Trusty, not Precise, does not use `bin/travis`, requires sudo so will be in different Travis build environment.

I'm not against merging it, but if we do it might make sense to open an issue for reducing unintended variance in the Travis job matrix.

**Comment by bfritz** [comment]
One other thought...  Should the Tomcat upgrade be split out and possibly target 0.16 or 0.15?

**Comment by ChristopherDavenport** [comment]
Well the likely problem of _MY_ travis vs _PR_ travis is that I may have initially run a push without the build override would have cached our updated sbt. So I'm hoping that removing the `before_script` will restore order to the universe.

**Comment by rossabaker** [comment]
I think the Tomcat upgrade should be backported to 0.16.

I guess the JDK9 build on 0.16 would be prudent, but ugh, I hate adding more complexity.  I'm content sitting on it for a bit until we get some of these other issues sorted out, and maybe backporting this change later if we're nervous about it?

**Comment by ChristopherDavenport** [comment]
Ok Tomcat -> 0.16

Then we reopen and see if we can get to work after the next mergetrain.

**Pull request closed without merging**
