### PR TITLE
Breaking improvements to scala-xml

### PR DESCRIPTION
**Pull request by rossabaker**
* Reverts the more complicated implicit encoding of #4380.
* Introduce safer defaults from scala-xml-2.
* Render XML declaration with charset
* Set charset in Content-Type

### CODE REVIEW

**Comment by rossabaker** [comment]
9848eb2 could be backported.  It's a SHOULD, not a MUST.

**Comment by rossabaker** [comment]
I think 7705fde was bad.  CI started hanging.

**Review by isomarcte — APPROVED** [review]

**Review by yanns — APPROVED** [review]
not an expert, but the code is looking good and seems easier to reason with.

**Review by ChristopherDavenport — APPROVED** [review]

**Comment by ChristopherDavenport** [comment]
Should adjust description to match current status

**Comment by rossabaker** [comment]
Yeah, it would be nice if we'd better make the description match the code in general.  I gave this an update.

**Pull request merged**
