### PR TITLE
Silence some imports in the json documentation

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks like a good candidate to retarget to 0.18.x, but :+1: to the change.

**Comment by jcranky** [comment]
@rossabaker how does that work? are we merging 0.18.x into master then?

**Comment by ChristopherDavenport** [comment]
Yes we run a merge 🚋

**Comment by jcranky** [comment]
ah, ok - I'll re submit

**Pull request closed without merging**
