### PR TITLE
Remove war example

### PR DESCRIPTION
**Pull request by rossabaker**
1. It bitrotted
2. A working version is in now in http4s-servlet

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Bye bye!

**Comment by rossabaker** [comment]
Eek.  One build hung.

**Comment by armanbilge** [comment]
Seems it's not the first.
https://github.com/http4s/http4s/actions/runs/2086187444
https://github.com/http4s/http4s/actions/runs/2086187444

... looking back, first one seems to be
https://github.com/http4s/http4s/actions/runs/2081893375

This one might be on me, sorry. I wonder if adding some `lazy val`s caused some initialization locks somehow?

**Comment by rossabaker** [comment]
Maybe.  There's a description of a few things that can go wrong [here](https://docs.scala-lang.org/sips/improved-lazy-val-initialization.html.

**Comment by armanbilge** [comment]
Ok, gotcha.

https://gist.github.com/armanbilge/a1759c829bb579484a9e1542dc0443c1

**Pull request merged**
