### PR TITLE
Finagle client and server support

### PR DESCRIPTION
**Pull request by jcouyang**
love Http4s DSL so much.
but also I like to have some consistency of ops and monitoring setups on http4s service and our other finagle PRC service, so it is easier to maintain if everything running on the same kind of server.
this is a very first attempt, please any feedback is welcome

### CODE REVIEW

**Comment by jcouyang** [comment]
That sounds great!

I stared with a seperate repo already, since it is easier for me to write unit test and publish jar for testing

https://github.com/jcouyang/http4s-finagle

Would you like me to just transfer it to http4s org? @rossabaker

**Comment by rossabaker** [comment]
Excellent!  I just sent a couple PRs for the license and the code of conduct so it matches the rest of the org, and then we can get it transferred over.

**Comment by rossabaker** [comment]
Okay, I think the permissions are set up so you can transfer it, and remain an admin after the transfer.  If either of those are false, let us know, and we'll take another look.

**Comment by jcouyang** [comment]
got this error when transferring
image
still missing permission I guess @rossabaker

**Comment by rossabaker** [comment]
Sorry about that. I just tweaked it. Please try again.

**Comment by jcouyang** [comment]
thanks
transferred to https://github.com/http4s/http4s-finagle
closing this one

**Pull request closed without merging**
