### PR TITLE
Add ScalaDocs for Headers, with RFC links.

### PR DESCRIPTION
**Pull request by diesalbla**

### CODE REVIEW

**Comment by diesalbla** [comment]
@Daenyth Sorry... Scalafmt problems...

**Comment by diesalbla** [comment]
@rossabaker The build failed because of some tests failed: 

```
[info] Passed: Total 18, Failed 0, Errors 0, Passed 18, Pending 2
[error] Failed: Total 1641, Failed 1, Errors 0, Passed 1639, Skipped 1, Pending 2
[error] Failed tests:
[error] 	org.http4s.QueryParamCodecSpec
```

**Comment by Daenyth** [comment]
@rossabaker Is that a known flappy test?

**Comment by hamnis** [comment]
@Daenyth yes. this is fixed by https://github.com/http4s/http4s/pull/3691 which we should merge asap

**Comment by rossabaker** [comment]
Also backported to series/0.21. I left out the conflicts due to newly modeled headers on master. This gets most of it.

**Pull request merged**
