### PR TITLE
WIP - Investigate https://github.com/http4s/http4s/issues/3383

### PR DESCRIPTION
**Pull request by kevinmeredith**
I added two specs, one of which captures @kubukoz's https://github.com/http4s/http4s/issues/3383.

```scala
[info]   + should log the expected request and response w/ logBody = false (213 ms)
[error]   x should log the expected request and response w/ logBody = true (223 ms)
[error]    
[error]    + HTTP/1.1 GET /request Headers()
[error]    + HTTP/1.1 200 OK Headers(Content-Type: text/plain; charset=UTF-8, Content-Length: 16) (LoggerSpec.scala:124)
[error] org.http4s.client.middleware.LoggerSpec.$anonfun$new$48(LoggerSpec.scala:124)
[error] Missing (2)
[error] HTTP/1.1 GET /request Headers()
[error] HTTP/1.1 200 OK Headers(Content-Type: text/plain; charset=UTF-8, Content-Length: 16)
[error] 
```

### CODE REVIEW

**Comment by kevinmeredith** [comment]
After adding a few `println`'s and then commenting out all but the newly failing `should log the expected request and response w/ logBody = true` spec via https://github.com/http4s/http4s/pull/3454/commits/fb6c9df9efd2e24d420257b2497448f156e5ef99, the following returned 

```scala
sbt:client> testOnly *LoggerSpec*
>>>> HERE
>> prelude: HTTP/1.1 GET /request
> logBody: true , isText true
>>>> HERE
>> prelude: HTTP/1.1 200 OK
> logBody: true , isText true
[info] LoggerSpec
[info] Logger should
[error]   x should log the expected request and response w/ logBody = true (449 ms)
[error]    
[error]    + HTTP/1.1 GET /request Headers()
[error]    + HTTP/1.1 200 OK Headers(Content-Type: text/plain; charset=UTF-8, Content-Length: 16) (LoggerSpec.scala:124)
[error] org.http4s.client.middleware.LoggerSpec.$anonfun$new$4(LoggerSpec.scala:124)
[error] Missing (2)
[error] HTTP/1.1 GET /request Headers()
[error] HTTP/1.1 200 OK Headers(Content-Type: text/plain; charset=UTF-8, Content-Length: 16)
[error] 
[info] Total for specification LoggerSpec
[info] Finished in 478 ms
[info] 1 example, 1 failure, 0 error
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	org.http4s.client.middleware.LoggerSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed May 31, 2020 12:56:01 AM
```

My guess, at this point, is that somehow https://github.com/http4s/http4s/blob/v0.21.4/client/src/main/scala/org/http4s/client/middleware/Logger.scala#L71 isn't getting called, namely the `log`, but I do not have confidence in that hypothesis.

Does anything stick out to you, please, @rossabaker?

**Comment by kevinmeredith** [comment]
Chris Davenport explained to me that via https://gitter.im/http4s/http4s?at=5ed48f52ff7a920a72249178:

> It's attached to the stream which is never evaluated.
> message.body.compile.drain
> This happens in the backends.
> But since you are doing it yourself. To observe a body, you must evaluate a body.

Consequently, I'll close this one.

**Comment by tienleq** [comment]
Hi @kevinmeredith I'm having similar issue using AsyncHttpClient.
I see the suggestion to evaluate the body by ourselves. I just wonder how could you do it?

**Comment by kevinmeredith** [comment]
Hi @tienleq - I'm not sure. My guess is that "evaluate body" means to drain the `fs2.Stream`. However, can you please respond, @ChristopherDavenport? Thanks

**Pull request closed without merging**
