### PR TITLE
Upgrade to jawn-0.7.2 to fix Argonaut compatibility issue.

### LINKED ISSUE #157: Argonaut Json parser causes ClassCastException
I wrote 2 `EntityDecoder`, one using `ArgonautSupport.json` and one using `argonaut.Parse`. The latter is working but the first one generates the following error: java.lang.ClassCastException: scala.Some cannot be cast to argonaut.Json

```scala
def jsonEntityDecoder[A](implicit ev: DecodeJson[A]): EntityDecoder[A] =
    ArgonautSupport.json.map(json =>
      ev.decodeJson(json).fold(
        (message, history) => sys.error(s"Could not decode json $json, error: $message, cursor: $history"),
        identity
      )
    )

  def jsonEntityDecoder2[A](implicit ev: DecodeJson[A]): EntityDecoder[A] =
    EntityDecoder.decodeBy(MediaType.`application/json`){msg =>
      org.http4s.DecodeResult.apply(EntityDecoder.decodeString(msg).map{s =>
        Parse.parse(s).fold(
          m => ParseResult.fail(s"Cannot parse string $s into json, error: $m"),
          ParseResult.success
        ).flatMap(json =>
          ev.decodeJson(json).fold(
            (m, h) => ParseResult.fail(s"Cannot parse json $json, error: $m $h"),
            ParseResult.success
          )
        )
      })
    }
```

I am sure we can reproduce the error without DecodeJson but I didn't have the time to do so

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #157.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Looks good to me. Merge is Travis is cool.

**Comment by julien-truffaut** [comment]
we still have an incompatibility issue, `org.spire-math.argonaut-support` uses `argonaut-6.1-M5` but `org.http4s.argonaut` uses `argonaut-6.1-M4`.

We should probably drop the argonaut dependency and take it transitively or upgrade to `argonaut-6.1-M5`

**Comment by bryce-anderson** [comment]
Do we know when to expect an argonaut 6.1 final? It looks like the milestones are spread out with widely differing intervals but we may continue to have problems until something stable arrives. Its seems to have been in milestone status for over a year now. 
@julien-truffaut is right, getting it transitively is probably the best way to mitigate the issue at the moment.

**Comment by rossabaker** [comment]
Ugh, the M5 upgrade was only on master. I thought I was being safe with the unit test, but something else must not be compatible.

Yes, making it transitive should work.

**Pull request merged**
