### PR TITLE
Fix for #1281

### PR DESCRIPTION
**Pull request by NicolasRouquette**
In `org.http4s.util.threads`,`DefaultExecutionContext` depends on `DefaultPool` so both must be made lazy.

In `org.http4s.servlet.syntax`, changed `ServletContextOps.mountService` to include an `ExecutionContext` which defaults to the lazy `DefaultExecutionContext`.

### CODE REVIEW

**Comment by rossabaker** [comment]
Now that everything is based on ExecutionContext, should we even provide our own default, or should we just use the Scala global by default? 🤔

**Comment by NicolasRouquette** [comment]
I think it would be better to reuse the Scala `ExecutionContext.global` instead of creating a separate one. This issue is caused by the fact that `org.http4s.util.threads.DefaultExecutionContext` is an eager variable; which causes that context to be created even if it is not used. Note that Scala's `ExecutionContext.global` is a lazy def; so there is no penalty in using it as the default value of a function parameter.

**Comment by rossabaker** [comment]
I think I agree with the default execution context, but I'll argue the other side for completeness:
* It's a fork-join pool, and this is not fork-join optimized work.  Whether we can measure a difference in throughput here vs. a fixed thread pool, I'm not particularly sure.
* It's a daemon pool, and I'd like to discourage people from using daemon pools for serving requests.  A daemon pool abruptly stops instead of blocking shutdown until the executor is cleanly shutdown.  I don't think this is good for production.  This problem already exists in the current implementation, and I don't know how to solve it without starting a "special" pool that shuts down with the server/client.  We've done this before, and it was ugly.

**Comment by NicolasRouquette** [comment]
Here's what I ended up doing using this PR to get precise control of how pools, threads, etc... used:

```scala
  def apply(name: String, nbWorkers: Int, idleTimeout: Duration, maxTotalConnections: Int)
  : (Client, fs2.Strategy, Scheduler) = {
    val execService = Executors.newScheduledThreadPool(nbWorkers, Strategy.daemonThreadFactory(name))
    implicit val S = fs2.Strategy.fromExecutor(execService)
    implicit val sched: Scheduler = Scheduler.fromScheduledExecutorService(execService)
    val prov: AsynchronousChannelProvider = AsynchronousChannelProvider.provider()
    val gr = prov.openAsynchronousChannelGroup(execService, nbWorkers)

    val config =
      BlazeClientConfig
        .insecure
        .copy(idleTimeout, executionContext = ExecutionContext.fromExecutor(execService), group = Option(gr))
    val httpClient: Client = PooledHttp1Client(nbWorkers, config).copy(shutdown = Task.delay(execService.shutdown()))
    (httpClient, S, sched)
  }
```

I confirmed with the debugger that there are no default pools of any other kind created; which is what I really needed. I found that there is a subtle "default" behavior in that if we do not provide an `AsynchronousChannelGroup`, then one is created using the default thread pool!

**Comment by rossabaker** [comment]
I am leaning toward eliminating our default pool and moving toward defaulting to the global execution context.  Any strenuous objections?

**Comment by ChristopherDavenport** [comment]
I think that is a better solution overall.

**Comment by NicolasRouquette** [comment]
I've deleted the default pools & merged w/ master. 
Is this what you intended @rossabaker & @ChristopherDavenport?

**Comment by ChristopherDavenport** [comment]
Slightly worried about that merged with master commit. Doing stuff like that opens the door to regressions.

**Comment by NicolasRouquette** [comment]
Mea culpa. I should have merged upstream. 
Since I began this PR, there was another merge to master.

**Comment by NicolasRouquette** [comment]
@ChristopherDavenport Is this what you mean? 
https://github.com/http4s/http4s.g8/pull/20

As far as this PR is concerned, is it ready to be closed?

**Pull request merged**
