### PR TITLE
Scala 3.0.0-RC3 for 0.22.x

### PR DESCRIPTION
**Pull request by rossabaker**
This won't work without cats-parse, but includes the first RC3-only dependency.

### CODE REVIEW

**Comment by aeons** [comment]
`cats-parse` is here, but it looks like [blaze 0.15.0-M4](https://github.com/http4s/blaze/releases/tag/v0.15.0-M4) didn't make it to maven central.

**Comment by aeons** [comment]
Whoops, looks like I pushed the non-working blaze bump as well.

**Comment by rossabaker** [comment]
I've fallen into a hole.  Do we still want this PR?  There are a bunch of new bumps for 3.0.0 now.  I'm more focused on getting the last 0.21 out the door at the moment.

**Comment by hamnis** [comment]
I would say no, we should focus on getting 3.0.0 final deps.

**Comment by rossabaker** [comment]
Sorry, I wrote poorly.  Agree on forgetting about RC3.  Does this PR get us closer to 3.0.0 support, or should we start over?

I broke the series/0.22 branch in a merge last night because of a Cats version bump.  Maybe we should just start lining things up directly on that branch.

**Comment by rossabaker** [comment]
Yeah, these versions are all obsolete, I think.

**Pull request closed without merging**
