### PR TITLE
fix source links from 0.15.x scaladoc

### PR DESCRIPTION
**Pull request by bfritz**
Care will be needed when merging to 0.16.x and master.

Edit:  Would be nice if we could pull the correct tree from build metadata rather than hardcoding it.  Any sbt gurus know if that's possible?

### CODE REVIEW

**Comment by bfritz** [comment]
Travis, y u so [crazy](https://travis-ci.org/http4s/http4s/jobs/220288677#L1137)?

**Comment by bfritz** [comment]
The failed build is _really_ strange.  Apparently `bin/travis` was run twice.  Exit code was 0 [the first time](https://travis-ci.org/http4s/http4s/jobs/220288677#L1137) and 1 [the second](https://travis-ci.org/http4s/http4s/jobs/220288677#L1334).

**Comment by rossabaker** [comment]
There is a `TRAVIS_BUILD` environment variable, which I think would do the right thing in all builds that publish the docs.

It suddenly occurs to me that we shouldn't delete old release branches as long as we link like this.

**Comment by bfritz** [comment]
> There is a TRAVIS_BUILD environment variable...

`$TRAVIS_BRANCH` ?  Would be nice if a generic solution did not depend on Travis so local builds created accurate links.  But parsing `$TRAVIS_BRANCH` might be better than hardcoding it per-branch.

Guessing we could grab the branch with [sbt-git](https://github.com/sbt/sbt-git) (or by shelling out to the git cli).

**Comment by rossabaker** [comment]
Yes, I meant TRAVIS_BRANCH.  Fair point on the sbt-git, but that's much trickier, and depends on the branch name not being a topic branch, which will often be true locally.

There's also the `apiVersion` sbt key, but need to know when to translate that to master.  Could solve that problem by renaming the master branch to release-0.17.x (still leaving it as default in GitHub), but then how do we know to publish docs/src/hugo? 😵

**Comment by bfritz** [comment]
Going to hold off for now and see if I can find a solution that eliminates the branch differences.

**Comment by aeons** [comment]
I didn't even notice this PR, but this is superseded by #1156, right?

**Comment by bfritz** [comment]
@aeons Yes it is.  Thanks for catching that.

**Pull request closed without merging**
