### PR TITLE
Make jsonOf and jsonEncoderOf implicit

### LINKED ISSUE #660: Should jsonOf and jsonEncoderOf be implicit?
In all of our JSON support modules, `jsonOf` and `jsonEncoderOf`, which create an `EntityDecoder` or `EntityEncoder` from an implicit instance of each library's JSON codecs, are not implicit.  Users frequently expect defining a JSON codec for their case class is sufficient for an entity codec.

We historically have not made this implicit, because it's not a given that users want to code case classes as JSON.  But maybe we should: if the user supplied a way to encode it as JSON, without any other available encodings, then it's probably a JSON API.  And if there are multiple codecs for a case class in scope, it should fail due to ambiguous resolution.

Thoughts?

/cc @tskardal

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #660

### CODE REVIEW

**Comment by rossabaker** [comment]
This eliminates one of our biggest newbie questions.  It also makes pairs of imports like this extremely powerful.  The question is, too powerful?

```scala
import io.circe.generic.auto._
import org.http4s.circe.jsonOf
```

**Comment by rossabaker** [comment]
I think it's important that `jsonExtract` in json4s is not made implicit.  It's going to try even harder to derive a codec than circe or argonaut, to the point that they fail at runtime.  (See json4s' issue tracker and weep.)

**Comment by reactormonk** [comment]
https://travis-ci.org/http4s/http4s/jobs/155673659#L747

**Comment by rossabaker** [comment]
Drat.  I guess we need to make those lazy or defs in case the instances are mixed in.

**Comment by rossabaker** [comment]
Argonaut uses `EntityEncoder.stringEncoderOf.contramap`, whereas circe uses `EntityEncoder[String].contramap`.  This reveals a subtlety I didn't anticipate.

When `jsonEncoderOf` is implicit, `EntityEncoder[String]` picks up the JSON version:

```scala
scala> import org.http4s._, org.http4s.argonaut._
import org.http4s._
import org.http4s.argonaut._

scala> scala.reflect.runtime.universe.reify(EntityEncoder[String])
res1: reflect.runtime.universe.Expr[org.http4s.EntityEncoder[String]] = Expr[org.http4s.EntityEncoder[String]](EntityEncoder.apply[Predef.String](`package`.jsonEncoderOf(EncodeJson.StringEncodeJson)))
```

... unless we import from EntityEncoder specifically.  Then the plain one wins again:

```scala
scala> import org.http4s._, org.http4s.EntityEncoder._, org.http4s.argonaut._
import org.http4s._
import org.http4s.EntityEncoder._
import org.http4s.argonaut._

scala> scala.reflect.runtime.universe.reify(EntityEncoder[String])
res2: reflect.runtime.universe.Expr[org.http4s.EntityEncoder[String]] = Expr[org.http4s.EntityEncoder[String]](EntityEncoder.apply[Predef.String](EntityEncoder.stringEncoder(EntityEncoder.stringEncoder$default$1)))
```

😞

**Comment by reactormonk** [comment]
Maybe do some LowPriorityImplicit wrestling with nested traits?

**Comment by rossabaker** [comment]
Maybe.  I do fear what other subtleties we might be missing once we start juggling implicits like that.

I just do `Ok(foo.asJson)`, and am not unhappy with that, though I'm unhappy with the discoverability of it for new users.  That also doesn't address the decode side.

**Comment by rossabaker** [comment]
Does anybody want to argue for this still?  I'm pretty well convinced it's a bad idea.

I did notice as part of @reactormonk's work that we have a `decodeWith` but not an `expectWith` to get an explicit EntityDecoder into the same position as a type param on the implicit cases.  This seems worth some thought from the Consistency Police.

**Comment by reactormonk** [comment]
How about an overload instead? Or a good explanation on what's expect vs. decode?

**Comment by rossabaker** [comment]
I wanted an `expectWith` just today.

What do you mean by overload?  You mean an `expect` that takes the decoder first and the argument second?  It's already overloaded on the first argument.  If we overloaded with the decoder first, the second argument list would be ambiguous, or only support one type.

**Comment by rossabaker** [comment]
Good discussion from this, but consensus is it's a bad idea.  Closing.

**Pull request closed without merging**
