### PR TITLE
blaze client should add a User-Agent header

### PR DESCRIPTION
**Pull request by bryce-anderson**
What should we do about version numbers? I know we will forget to update if we start hard coding them. Maybe we should think about generating the library version during build time.

### CODE REVIEW

**Comment by rossabaker** [comment]
We do generate them. See BuildInfo.

**Comment by bryce-anderson** [comment]
Well, thats good news! The PR is updated to include the version. I think this is ready to go now.

**Comment by bryce-anderson** [comment]
I'm thinking its better to use a typed  ```User-Agent``` header as it is not truely free form. PR #245 adds the types and header parser. Once #245 is merged, this PR will be ammended.

**Comment by bryce-anderson** [comment]
This is ready for review.

**Pull request merged**
