### PR TITLE
Modified bin/travis to make site using scala 2.12

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
After #853 tut should be able to compile using 2.12. 

Which means this branch should compile and make the new docs and site off of 2.12

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Looks like the build is erroring on run calls in the tut documentation. Perhaps switching over to 2.12 may need to be linked with switching to unsafePerformSync in #829

**Comment by rossabaker** [comment]
Commented on #829, but I think we should do it.  Do you want to see this one through, or have someone pick it up from here?

**Comment by ChristopherDavenport** [comment]
I found that it was an Unauthorized that caused the error rather than the unsafePerformSync. So I'm willing to keep working on it but it looks like to may be web based.

**Comment by rossabaker** [comment]
Unauthorized or Forbidden? #817 is an irritant, and it happens right below that deprecation warning, so it's easy to get confused.

**Comment by ChristopherDavenport** [comment]
Looks good to me now. It was #817 that caused the erroneous failure. The random build failures are rather odd. We have another one in this run on a different version in a different spot.

**Comment by rossabaker** [comment]
There are three outstanding things that cause intermittent Travis failures:

* #817 
* #774 
* This one, which maybe we can address in #858.

I think we declare victory on this PR.

**Pull request merged**
