### PR TITLE
The Path extractor for Long now supports negative numbers

### PR DESCRIPTION
**Pull request by jedesah**
Was this working as intended and perhaps poorly documented or is this PR a bugfix?

### CODE REVIEW

**Comment by bryce-anderson** [comment]
I doubt the behavior was intentional and this looks correct. I'm always anxious about adding more allocations by using `Try` and `toOption` when a `try {} catch {}` will do but perhaps I'm alone in that concern: I've always had a propensity for premature optimization.

**Comment by jedesah** [comment]
@bryce-anderson I don't have any strong opinion. Obviously, the `Try` version is easier on the eyes, but since this code can potentially find itself in the hot path of a server perhaps it's best to leave the `try...catch`. Then again we were iterating over each character of the string and checking if it's a digit so I think this is going to be faster than it was regardless. Any idea for the reason behind that btw. I just deleted it because I couldn't come up with a good reason to do that and it doesn't break any expected behaviors (at least the ones captured by tests).

**Comment by jedesah** [comment]
Btw, I am going to attribute the loss in coverage to the nondeterministic nature of property based testing as I have a hard time seeing how this change could have negatively impacted coverage even after trying to decipher the `codecov` coverage diffs

**Comment by bryce-anderson** [comment]
Its true that `Try` is easier on the eyes and there is a chance all of it get inlined anyways so I'm not going to strongly object. Lets give this until tomorrow for objections but otherwise, I think its good to go. 👍

**Pull request merged**
