### PR TITLE
0.23 -> main

### PR DESCRIPTION
**Pull request by armanbilge**
```
# Conflicts:
#	.github/workflows/ci.yml
#	build.sbt
#	client/shared/src/main/scala/org/http4s/client/Client.scala
#	client/shared/src/main/scala/org/http4s/client/middleware/GZip.scala
#	client/shared/src/test/scala/org/http4s/client/ClientSuite.scala
#	ember-core/shared/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
#	ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
#	ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
#	ember-server/js-jvm/src/test/scala/org/http4s/ember/server/EmberUnixSocketSuite.scala
#	server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
#	tests/shared/src/test/scala/org/http4s/UriSpec.scala
```

### CODE REVIEW

**Comment by wjoel** [comment]
I haven't checked on 0.23 (my benchmarks use `Entity.strict`), but without https://github.com/http4s/http4s/pull/6374 this fails to pass the plaintext verification when I run the TFB benchmarks.

`Verifying test plaintext for http4s caused an exception: HTTPConnectionPool(host='tfb-server', port=8080): Read timed out.`

Results are better than on M39 with CE 3.5.0 and fs2 3.7.0, but results on M39 with those versions seem to be worse than in the past.

**Comment by armanbilge** [comment]
> but without #6374 this fails to pass the plaintext verification when I run the TFB benchmarks.

@wjoel sorry, can you clarify: do you mean it is broken / there is a bug without that PR?

**Comment by wjoel** [comment]
@armanbilge seems the issue wasn't that, I didn't have your [Encode trailers for chunked strict entities (?)](https://github.com/http4s/http4s/pull/7115/commits/e5eeb4ba13563b712f70eb5cfc609f4b4d119a78) fix when I ran the benchmarks. I was a bit too eager, this PR works as it is right now.

However, the results are very bad on plaintext when compared to 1.0.0-M39, but #6374 doesn't help (and indeed, the benchmarks aren't using HTTP/2).
1.0.0-M39 plaintext: https://www.techempower.com/benchmarks/#section=test&shareid=323cbb9f-d5ef-4a47-bf5c-4fea47a64838&test=plaintext
This PR: https://www.techempower.com/benchmarks/#section=test&shareid=5a0de0e3-c468-446c-aaab-169e8cd6a19e&test=plaintext

With 1024 concurrent connections, it goes from 245,078 req/s to 69,680 req/s. JSON results are slightly better, especially at higher levels of concurrency, but with 16 concurrent requests it goes from 128,851 req/s to 73,626 req/s. Should probably look into that, but not a blocker here, I guess.

To reproduce: get https://github.com/wjoel/FrameworkBenchmarks/tree/2023-05-potential-issue, run `cp -r ~/.ivy2/local/org.http4s ~/.ivy2/local/org.typelevel/ ~/.ivy2/local/co.fs2/ /path/to/FrameworkBenchmarks/frameworks/Scala/http4s/` followed by `./tfb --mode benchmark --type json plaintext --test http4s`

**Comment by wjoel** [comment]
Hmm. I must have made a mistake somewhere, I started bisecting, but now I get decent results on this PR: https://www.techempower.com/benchmarks/#section=test&shareid=c0c9fce1-b7a6-46c7-8f42-ba55fc14537f&test=plaintext

Sorry about the noise, lgtm.

**Comment by armanbilge** [comment]
Not at all, thanks for investigating!

**Review by danicheg — APPROVED** [review]
Quickly flipped through the changes, LGTM

**Pull request merged**
