### PR TITLE
Remove the key from idleQueue if it is empty after dequeue

### PR DESCRIPTION
**Pull request by tbrown1979**
Should fix https://github.com/http4s/http4s/issues/1920

### CODE REVIEW

**Comment by SystemFw** [comment]
Not really asking for this specific PR, but a few more comments explaining the design of the Manager (don't have to be detailed, even a general design comment at the top) would go a long way given that the code is slightly hairier than average http4s :)

**Comment by tbrown1979** [comment]
@rossabaker That's a great point. I can make that change. 

@SystemFw That would definitely be nice. Fwiw, once cats-effect 1.0 is released I can work on purifying the `PoolManager` which would make it a lot easier to reason about.

**Comment by tbrown1979** [comment]
@rossabaker Let me know if that looks okay to you.

**Comment by tbrown1979** [comment]
@rossabaker I look forward to seeing how I can improve things with the new cats-effect tools 😄

**Comment by SystemFw** [comment]
@tbrown1979 You can start working on it right now probably, cats-effect 1.0 is not out yet but I don't foresee big changes from now until the release. Feel free to ping me should you need  a hand with the new concurrency stuff there.

@rossabaker Maybe that's a sufficient knock on the door for a milestone?

**Comment by tbrown1979** [comment]
@ChristopherDavenport We still do remove an idle connection here. The [`getConnectionFromQueue`](https://github.com/http4s/http4s/pull/1922/files#diff-d2f4e3b3e2b0f3a001976f1e34fd7cb9R47) will `.dequeue` _iff_ the `Queue` for the given `key` is `.nonEmpty`, and then it returns us that connection. We'll then `.shutdown()` that connection. Let me know if that helps!

**Comment by tbrown1979** [comment]
Should I make the log I added an `error` instead of `warn`? It's something that really should never happen, and if it does it might be good to have it louder than `warn`?

**Comment by ChristopherDavenport** [comment]
Yet we have experience it does. So I am inclined towards the level it is at.

**Pull request merged**
