### PR TITLE
More comprehensive support of `Entity` model in `Jsonp` Middleware

### PR DESCRIPTION
**Pull request by danicheg**

### CODE REVIEW

**Comment by danicheg** [comment]
@http4s/core I know all of you are fed up with this kind of PRs, but I promise you, this one is the penultimate in a row. Also, this one is tiny enough and low-hanging enough to get it merged.

**Comment by valencik** [comment]
Hey @danicheg, I took a look at this a couple days ago, but realized I had no idea what jsonp is and we had no tests for this middleware 😬 

So I put together a tiny test suite: https://github.com/http4s/http4s/pull/6958
But, interestingly, it fails trying to use the rather large regex in the Jsonp middleware.

```
org.http4s.server.middleware.JsonpSuite.Wrap response when callback param matches and resp in JSON 0.05s java.util.regex.PatternSyntaxException: Illegal character range near index 345
```

Are you able to successfully use the Jsonp middleware in an app, or do you run into this failure too?

**Review by isomarcte — APPROVED** [review]

**Comment by armanbilge** [comment]
Unfortunately the discussion in https://github.com/http4s/http4s/issues/6959 proposes that we remove this altogether on `main` 😅

**Comment by danicheg** [comment]
No way, Arman. Don't you steal my contribution! 😆 
But, if the majority is in favor of that, I don't mind absolutely. I'm not a user of this middleware even.

**Comment by rossabaker** [comment]
If you want to pad your stats before the annual performance review, there's a Good First Issues board ... :laughing:

**Comment by danicheg** [comment]
Eh, if that only works...

**Comment by danicheg** [comment]
Well, until you guys have skidded a little, I merge this. Anyway happy to see this Middleware removed one day.

**Pull request merged**
