### PR TITLE
Alternative fix for ipv6

### PR DESCRIPTION
**Pull request by m-sp**

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
I find this one easier to understand.

**Comment by rossabaker** [comment]
`UriParserSpec` is now failing. I haven't investigated why yet.

**Comment by hamnis** [comment]
https://github.com/http4s/http4s/runs/1755280713#step:11:2051

**Comment by m-sp** [comment]
it was the generator after all. it generates an address which shortens only a single section... exactly what is forbidden in the Rfc3986ParserSpec

**Comment by rossabaker** [comment]
Nice find!  I'll bet that last commit is something we could fix in series/0.21, for whatever it's worth.  (We haven't done much to publicize our arbitraries for outside use.)

**Comment by rossabaker** [comment]
I'll look into cherry-picking that commit next time I'm back on series/0.21.

**Pull request merged**
