### PR TITLE
Start release notes for 0.16

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
We seem to be back to intermittent build failures. Argh.

**Comment by ChristopherDavenport** [comment]
The timeouts always cause a problem in some way. It seems to be CI architecture.
```
[error]   ! Not timeout on only marginally slow POST body (17 seconds, 504 ms)
[error]    java.util.concurrent.TimeoutException: Client idle timeout after 10 seconds. (ClientTimeoutStage.scala:40)
```

**Comment by rossabaker** [comment]
There is [this kind of nonsense](https://travis-ci.org/http4s/http4s/jobs/215346335#L3418) again:

```
"specs2.fixed.env893082443-24" #4479 prio=5 os_prio=0 tid=0x00007ff6e43da800 nid=0x1c8b waiting for monitor entry [0x00007ff327326000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.http4s.testing.ArbitraryInstances$$anonfun$arbitraryCharsetRange$1$$anonfun$apply$21.apply(ArbitraryInstances.scala:127)
	at org.http4s.testing.ArbitraryInstances$$anonfun$arbitraryCharsetRange$1$$anonfun$apply$21.apply(ArbitraryInstances.scala:126)
```

**Comment by rossabaker** [comment]
Certainly this didn't cause the problem. Going to open it as a separate issue.

**Pull request merged**
