### PR TITLE
Servlet 5.0 and friends

### PR DESCRIPTION
**Pull request by rossabaker**
Supersedes #4644.

### CODE REVIEW

**Comment by rossabaker** [comment]
If we do this before we split the repository, we'll need everyone compiling on JDK11, and have to exempt the Jetty modules from JDK8 in the build matrix.

**Comment by rossabaker** [comment]
And we use Jetty in tests, so the plot thickens some more.

**Comment by rossabaker** [comment]
We could use the `com.sun.net.httpserver` for tests.  We'll have to spin both Jetty modules off into their own repo, which is imminent anyway with the Great Schism.  I guess we're stuck on Servlet 3 in our 0.22/0.23 timeframe, but can start removing those Jetty test dependencies anytime.

**Comment by armanbilge** [comment]
Superseded by https://github.com/http4s/http4s-servlet.

**Pull request closed without merging**
