### PR TITLE
#828 - Add details when JSON decode failure occurs

### PR DESCRIPTION
**Pull request by subandroid**
change ParseFailure msg value to details instead of sanitized version

### CODE REVIEW

**Comment by rossabaker** [comment]
I think this will scratch your itch, but the definition in https://github.com/http4s/http4s/blob/master/core/src/main/scala/org/http4s/MessageFailure.scala would give both the sanitized and details.  I'm not at a computer, but I think that would drop right in.

I can release this evening.

**Comment by subandroid** [comment]
Sure. That looks better.

**Comment by rossabaker** [comment]
v0.12.6 is on its way to Maven Central with this fix.

v0.12.5 is a permanent monument to my failure to pull before publishing. Sadly, it's not the first. :flushed:

**Comment by subandroid** [comment]
Wonderful. Thank you my friend!

**Pull request merged**
