### PR TITLE
Promote avias and tsec

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by rossabaker** [comment]
How did we get a QValue of 0.6900000000000001?

```
[info] compare should
[error]   x be consistent with coding.compareToIgnoreCase for same quality (47 ms)
[error]    Falsified after 11 passed tests.
[error]    > ARG_0: ContentCoding(l, QValue(0.6900000000000001))
[error]    > ARG_1: ContentCoding(l, QValue(0.0))
[error]    > 690 is not less than 0 (ContentCodingSpec.scala:24)
[error] org.http4s.ContentCodingSpec.$anonfun$new$10(ContentCodingSpec.scala:24)
[error] org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
[error] org.scalacheck.Prop$.secure(Prop.scala:456)
[error] org.scalacheck.Prop$.result$1(Prop.scala:712)
[error] org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
[error] org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[error] org.scalacheck.Prop$.result$1(Prop.scala:713)
[error] org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
[error] org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
[error] org.scalacheck.PropFromFun.apply(Prop.scala:22)
[error] org.scalacheck.Test$.workerFun$1(Test.scala:294)
[error] org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
[error] org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
[error] org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[error] org.scalacheck.Test$.check(Test.scala:323)
[error] org.http4s.ContentCodingSpec.check(ContentCodingSpec.scala:9)
```

**Comment by jmcardon** [comment]
Is it cheating if I greenlight this? :smile:

**Comment by rossabaker** [comment]
Not if we capture the issue.

**Comment by rossabaker** [comment]
Oh, you meant self-promotion.  Nah, that's always okay!

**Pull request merged**
