### PR TITLE
Merges, mostly #4429

### PR DESCRIPTION
**Pull request by rossabaker**
Compiles, but broken tests.

### CODE REVIEW

**Comment by rossabaker** [comment]
Oh, hell.  Looks like they're broken on series/0.22, too.  That merge was easy.

**Comment by rossabaker** [comment]
Crap.

**Comment by rossabaker** [comment]
We're getting some `\r\r\n` in `hdr` coming out of this line:

```scala
                val (hdr, rem) = nh.splitAt(endOfheader + `\r\n`.size)
```

**Comment by RaasAhsan** [comment]
This hunk seemed to not make it through https://github.com/http4s/http4s/blob/series/0.21/ember-core/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala#L46-L51

**Pull request merged**
