### PR TITLE
Fold contrib into main repo; bring AWS

### PR DESCRIPTION
**Pull request by rossabaker**
Not committing to supporting all these modules in the long run (#136).  At this stage of the project, a monorepo keeps things working together, strains our resources less, and gets more visibility than scattered repos.  We'll revisit modules like this around 1.0 and find them a home.  Or not.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
@rossabaker: I know you didn't write this but there are some code style issues that I think should be addressed before we fold this into the main repo:

* There are some fields that look like they need not be public (`*DateFormat` for example) and a lot of methods that should probably also be private. 
* Methods are are public should have a defined return type IMO. (Maybe this is already the case?)

**Comment by rossabaker** [comment]
On further thought, AWS provides an SDK which makes signing raw requests rare, and there is a [nice Scala wrapper](https://github.com/seratch/AWScala) which is probably the way to go.  I appreciate the original contribution, but I now think this one may be scope crept too far.

**Comment by LeifW** [comment]
AWS SDK brings in a huge kitchen sink of ranged deps of conflicting versions... I might like having a simple "native" scala alternative available.

**Comment by rossabaker** [comment]
The only annoyance I've had with it is Apache HTTP Components.  Are there others?

**Comment by rossabaker** [comment]
For posterity's sake, my cleaned up version of the signer is 0e825d6.

**Pull request closed without merging**
