### PR TITLE
Fixed mdocs from blazeclient repackaging

### PR DESCRIPTION
**Pull request by krayoola**
Part of #2702, Missed changes from #4838 PR

### CODE REVIEW

**Comment by aeons** [comment]
Thanks
There are some errors in scalafix that need the same treatment. Could you do that here as well?

**Comment by krayoola** [comment]
@aeons Fixed scala fix. I do have another error related in `cors.md` seems it came from the last cherry picked changes, will try to fix that too.

**Comment by krayoola** [comment]
Should be fixed now.

**Comment by aeons** [comment]
Thanks!

**Pull request merged**
