### PR TITLE
Add status Methods Which Use `String` or `URI`

### PR DESCRIPTION
**Pull request by isomarcte**
These are similar to the `expect` methods which take the same arguments. They are particularly useful for test.

### CODE REVIEW

**Comment by isomarcte** [comment]
I don't think the travis failure is related to my change.

**Comment by rossabaker** [comment]
Thanks.  I agree on the CI and restarted Travis.

Whether we want to do this, or move in the opposite direction, is #2483.  We should agree on our strategy there, and then either approve or close this.

**Comment by rossabaker** [comment]
If we do these, then also `expectOption`, `expectOptionOr`, etc., right?  I guess I'm arguing for "all-or-none" rather than "more".

**Comment by rossabaker** [comment]
It's a lot easier to add methods than take them away, and we have a general aversion to overloads.  I think this is a symptom of friction in creating requests.  I'd like to think about how we can do better there.

I vote we think about this during 0.20, since 0.21 is likely just around the corner.

**Comment by isomarcte** [comment]
@rossabaker any status updates on this?

**Comment by rossabaker** [comment]
I hoped someone would come up with a simpler way of building requests that reduces the desire for overloads, but we haven't seen one yet.  I'm usually opposed to overloads, but I guess I'm a mild :+1: on this, since someone cared enough to add it, and nobody has cared enough to shout it down.

**Pull request merged**
