### PR TITLE
Fix coverage Report

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Comment by jcranky** [comment]
You can ignore this PR for now, I'm just experimenting around with #775

**Comment by rossabaker** [comment]
Ooh, thanks.  I've been staring at this one stupidly and not understanding why it broke.

**Comment by jcranky** [comment]
@rossabaker I'm just looking, no promises that I'll actually find anything XD

**Comment by jcranky** [comment]
@rossabaker look at that, does that means it worked? XD

**Comment by jcranky** [comment]
I'll fix the commit message so we can merge.

**Comment by jcranky** [comment]
I think this is ready :)

**Comment by rossabaker** [comment]
Yeah, you found the stupid thing I did.  Thanks!  :)

**Comment by rossabaker** [comment]
Going to cherry-pick onto 0.15.x so we get test coverage there.

**Comment by rossabaker** [comment]
Cherry-picked and merged to master.  Thanks!

**Comment by jcranky** [comment]
:+1:

**Pull request closed without merging**
