### PR TITLE
Use a unique io runtime in BlazeServerSuite

### LINKED ISSUE #4166: Give blaze-server its own executor in tests
With regard to https://github.com/http4s/http4s/pull/4161/files/7c30f316ccc0e696d7b2b60e1475465859452f3b#r554253034, we shouldn't be testing against default thread names, but against a dedicated thread pool with obviously different names, so what we're testing for is explicit and not subject to the names of shared resources.  It will express intent better and be more robust to refactoring.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #4166.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
I was imagining a fixture that would close the executors when done, but I think these are configured to wither to zero threads?

**Comment by vasilmkd** [comment]
I can work on this some more tomorrow.

**Comment by vasilmkd** [comment]
I used munit's `def afterAll(): Unit` to shut down the IO runtime. Is that satisfactory?

**Review by rossabaker — APPROVED** [review]
That's good enough for me.

**Pull request merged**
