### PR TITLE
Clean out deprecatia prior to 0.20

### PR DESCRIPTION
**Pull request by rossabaker**
Could be more aggressive still, but these are all two years old.

### CODE REVIEW

**Comment by hamnis** [comment]
Lovely, I have wanted to get rid of a few of these for a while now :)

**Comment by rossabaker** [comment]
If there are any that are claiming valuable real estate, we could squeeze those into 0.22, but I'm trying to minimize breaking changes.  And some from 0.20 era could almost certainly go now.  But we've had users upgrade from Way Back, and they've appreciated our deprecations.

I'll stop clinging to my deprecatia when we start getting better at scalafix. :smile:

**Comment by rossabaker** [comment]
Test failure recorded as #4899.  The other one looks like an infra flake.

**Review by aeons — APPROVED** [review]

**Comment by rossabaker** [comment]
Note: this is the first significant divergence between 0.23 and 1.0.

**Pull request merged**
