### PR TITLE
uri interpolator draft

### PR DESCRIPTION
**Pull request by m-sp**
a first draft how a smarter uri interpolator could look like for http4s using our parsers
currently only works in dotty

putting it out there because I'm not sure when I can come back an finish this

currently there seems to be a couple of bugs, it only supports absolute Uris and the interpolating could be better. but it is a start

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
Neat.  I'm glad to see this discussion underway.  If we figure out the semantics, I think we can figure out the crossbuild.  There are all sorts of angles to explore here:
* Should the scheme part accept a `String`, a `Scheme`, or both?
* If we put a `String` in a path, should we encode it into a path segment?  Should it accept a `Path`?
* Similar questions for queries and fragments.  And ip4s types in the hosts...

**Comment by m-sp** [comment]
> Neat. I'm glad to see this discussion underway. If we figure out the semantics, I think we can figure out the crossbuild. There are all sorts of angles to explore here:
> 
> * Should the scheme part accept a `String`, a `Scheme`, or both?
> * If we put a `String` in a path, should we encode it into a path segment?  Should it accept a `Path`?
> * Similar questions for queries and fragments.  And ip4s types in the hosts...

Yep there are a lot of things to explore, if we can restrict ourselves to the concrete types `Scheme`, `Path`, `Query`, etc. we could get away with a simpler implementation.
currently the interpolator tries to progress as far as possible and at each step checks if we now need to insert the interpolation part. but if we already know which parts we have as arguments we can leave those out during parser construction.

this whole scheme breaks down again if we want to support `uri"http://http4s.org/test?hello=${"world"}"`

**Comment by rossabaker** [comment]
Taking the stronger types makes a bit more sense to me, but maybe isn't as useful.  Particularly if we don't have interpolators for scheme, query, etc.

**Comment by armanbilge** [comment]
Triaging aggressively, apologies. This PR looks great and I hope the work/energy can be retargeted to cats-uri. Thanks!

- https://github.com/http4s/http4s/discussions/5930
- https://github.com/typelevel/cats-uri/issues/5

**Pull request closed without merging**
