### PR TITLE
Allown param names to have encoded reserved parameters

### PR DESCRIPTION
**Pull request by etorreborre**
I don't know if we should generalize this to other names like `PathExp`. I am being conservative with just what gets me out my current issue here.

cc @bryce-anderson @rossabaker

### CODE REVIEW

**Comment by rossabaker** [comment]
I think this could be retargeted for release-0.14.x and get it out there sooner.  We'd need to add a MiMa exception for the new method, but that's fine.

**Comment by etorreborre** [comment]
Do you have any idea why the build failed?

**Comment by rossabaker** [comment]
Yes.  tut runs a client, and sometimes that fails in Travis.  It's one of the intermittent irritations.  I restarted it.

**Comment by rossabaker** [comment]
I cherry-picked this onto release-0.14.x, along with the blaze upgrade.  When Travis signs off on that, I'll ship it as v0.14.8.

**Comment by rossabaker** [comment]
Released as v0.14.8, merged to master.

**Pull request closed without merging**
