### PR TITLE
Topic/cats client

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
This has some major problems with formatting still, and I need to clean up the imports but as others are submitting PR's because I am taking to long I am putting mine here so you can see what I've built in case we want to work on it. 

Pool Manager definitely requires quite a bit of work but it compiles and passes most tests but we still need to consolidate what we are looking to do with request types. 

Let me know what you think and I'll try to finish the cleaning that I haven't gotten around to. Sorry about the code mess I was planning on distilling and running new commits once I had figured out what the transformation steps were.

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
@aeons @rossabaker @peterbecich In reference to #787 I put my work into a more public location so especially if there is anything we can use from each other I would love to do so. Let me know what you all think. Look at overall files not individual commits because they were rather nasty trying to get compilation, and then tests passing. 

I probably have a few I have disabled as well but this should give the group a handle of the work I've done so far.

I'm down to 6 failing tests at the moment, 
* Retry spec
   * Not retrying posts
   * Not retry effectful bodies
* FollowRedirectSpec
   * Follow Proper Strategy
   * Strp payload headers when switching to GET
   * Not redirect more than 'maxRedirects' iterations
* Client Spec
   * mock client should fail to read body after dispose

**Comment by rossabaker** [comment]
So if I'm reading this correctly, @ChristopherDavenport rebased his work on top of @peterbecich's work, and this constitutes a best-of-both branches now?  Sorry for the confusion on duplicate work.  I appreciate both efforts, and am glad to see both contributing to getting us up and running.

**Comment by ChristopherDavenport** [comment]
That is what I did. Wanted to make sure he got credit for his hard work since I was going to use it. Working on a pipe solution for how to handle the interruptable in fromHttpService now as that is causing most of the other problems in the tests. Then it will really be down to ConnectionManager and how we want to change things.

**Comment by aeons** [comment]
I haven't got any more stuff than what is in this branch already :)

**Comment by ChristopherDavenport** [comment]
If anyone has any ideas on how to get the pool manager to compile I'd love some help. 

The implementation of Callback instead of a NextConnection in borrow we end up with Unit which is not useful for the purpose of creating a Task[NextConnection]. This is declared within Core so it is probably used in multiple locations. So any directions or ideas would be nice as this is an essential feature for blaze-client.

**Comment by rossabaker** [comment]
`callback(Right(NextConnection(connection, false)))` compiles.

I was very uncomfortable writing our own pooling implementation, but commons-pool doesn't handle asynchronicity well.  In the long run, it might be worth thinking about that again, especially if we add support for limiting connections per host.

**Comment by rossabaker** [comment]
This is already great progress.  I'm going to merge this and add my fix so we're not bitrotting.

**Comment by ChristopherDavenport** [comment]
Absolutely, sorry for the delay. I got distracted over the holidays, and then the corresponding work backup from coming back from the holdiays. I don't want to hold your progress up so I apologize.

**Comment by rossabaker** [comment]
No worries at all.  Appreciate all the help on it, and welcome any more as time permits!

**Pull request merged**
