### PR TITLE
3944 cats2.3 switch implicits import to syntax

### PR DESCRIPTION
**Pull request by amiguez**
This changes addresses the https://github.com/http4s/http4s/issues/3944 
Replace cats.implicits._ with cats.syntax.all._

FIX https://github.com/http4s/http4s/issues/3944

### CODE REVIEW

**Comment by amiguez** [comment]
As discussed I just have to check if the `cats.syntax.all._` are actually needed on the documentation https://github.com/http4s/http4s/pull/3964/commits/dcf7c30a34abf20a55879063a080d9deb5d748f0

**Comment by rossabaker** [comment]
I see this is opened against main.  It would be better if we rebased this onto series/0.21 to keep those two branches aligned as much as possible.  I can help if you're unsure how to do that, or just backport these commits myself.

Thanks for joining us today. It was great to virtually meet you, and we appreciate the PRs!

**Comment by amiguez** [comment]
Thank you @rossabaker  indeed I really enjoyed yesterday event. the PR is rebased now to series/0.21. I will need to continue on it today (still draft)

**Comment by rossabaker** [comment]
@amiguez Did you have more you want to change?  This looks ready to me.  And thanks for fixing the docs.  Those often get overlooked!

**Comment by amiguez** [comment]
> @amiguez Did you have more you want to change? This looks ready to me. And thanks for fixing the docs. Those often get overlooked!

Is good for me, I am removing the 'draft' flag. Thank you :+1:

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
