### PR TITLE
Update Plugins

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
xsbt-web-plugin, sbt-release, sbt-coursier, and sbt-jmh update to current version

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Should this instead target release-0.16? I know not all of these can be ported to 0.15.

**Comment by rossabaker** [comment]
I think everything could target 0.15. I don't think they bring upgrades to
anything but examples and load tests.

I vaguely recall the newest sbt-release leads to a lot of noise at startup
related to a background logger.  Might want to watch for that.

**Comment by bfritz** [comment]
+1 for re-targetting to `release-0.15.x`.  Consistency across branches helps reduce the variables when there are build problems, e.g. #1055.

**Comment by ChristopherDavenport** [comment]
Will retarget

**Pull request closed without merging**
