### PR TITLE
Add Changes for Java 9 Testing

### PR DESCRIPTION
**Pull request by ChristopherDavenport**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Well.. any ideas here?

**Comment by ChristopherDavenport** [comment]
Once merge train hits with 2.12.4 I'll rebase so we can start testing.

**Comment by ChristopherDavenport** [comment]
Relevant Issue - https://github.com/coursier/coursier/issues/674

**Comment by ChristopherDavenport** [comment]
Has coursier been handling this for us while we secretly have bad versioning?

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/travis/build/http4s/http4s/}load-test:
[error] org.scala-lang.modules:scala-xml _2.11, _2.12
[error] org.scala-lang.modules:scala-parser-combinators _2.11, _2.12
```

[Link](https://travis-ci.org/http4s/http4s/jobs/290721838#L1111)

**Comment by rossabaker** [comment]
It looks like the problem comes from load test.  We're on the latest version, and there's no issue tracker on that sbt plugin.  The solution is not obvious to me.

**Pull request merged**
