### PR TITLE
Topic/authorization

### PR DESCRIPTION
**Pull request by bryce-anderson**
This is a continuation of PR #258 submitted by @frehn. I think its good to go but needs a broader review.

Some possible points of interest:
* The action of this as a middleware is troubling because of the type signature of our ```HttpService```, namely ```Request => Task[Option[Response]]```. Namely, if you ```orElse``` another route behind a service that has been wrapped by the authentication middleware, you must still authenticate. If we change the signature back to ```Request => Task[Option[Response]]``` we can query if the route exists and then attempt authentication, otherwise move on.
* By using a ```LinkedHashMap``` cleanup operations should be pretty cheap so I wonder if it would be worth it to just do cleanup every time a nonce is created and or queried.

A big thanks to @frehn, he did the vast majority of the work here including the great documentation this PR enjoys.

### CODE REVIEW

**Comment by frehn** [comment]
Thank you for the kind words, @bryce-anderson.

Regarding your first point, consider the question of when a non-authenticated 404 error should be issued. In apache, for example, all subdirectories of a protected directory are protected as well - no authentication, no 404. This seems to be a reasonable use-case to avoid leaking of information about which URIs are defined. In the PR this is mirrored insofar as, as you observe, if `service = service1 orElse protectedService orElse service2`, where protectedService is obtained by Authentication, then only the URIs defined in service1 will be accessible without authentication. I agree that this behaviour is unintuitive - maybe Authentication should be implemented differently to avoid this composability issue altogether?

**Comment by rossabaker** [comment]
If `service` is composed through prefix mapping, then the unauthenticated URI space can fall through to `service2`.  This is only an issue when composing services to share a namespace, right?

**Comment by bryce-anderson** [comment]
No, not necessarily: blaze uses the url translation and then ```orElse```'s routes together for prefix mapping. Therefor, if your first service is ```mount(myservice,"/secure")```, the security will fall through when using the blaze backend, but would be successful with servlet.

**Comment by frehn** [comment]
Would it be sensible to have a `mountService(service: HttpService, prefix: String, auth: Authentication)` in `ServerBuilder` (moving the implementation of `Authentication.apply` to that method), and require that implementations of `ServerBuilder` only forward those requests to the service that match the prefix?

**Comment by bryce-anderson** [comment]
@frehn, that would be one solution if we want to change the way blaze mounts services which is doable. However, I think authorization is a prime example of a middleware so that doesn't feel like the right solution to me: other middleware might end up with a similar problem in the future.

    In my mind, I want to know if a service is indeed willing to handle the request before requiring authentication: that way we can know that this service that requires authentication isn't going to handle it, so just move on to the next one. The only way to query it is to run the full route and see if we received a response, which we will then discard should we need to perform authentication. This is not only a waste of resources but would be a security hole for side effecting routes such as a POST request.

    I can see a few ways to handle this.
1. go back to ```HttpService = Request => Option[Task[Response]]```. This allows us to query the service synchronously as to whether its going to handle the request. It still presents a potential security hole in that a route can still use the ```now``` constructor for ```Task```, performing all its side effects before we execute the ```Task```.

2. Define ```HttpService = Request => Task[Option[Task[Response]]]```. We can asynchronously query the service and deffer computing the result if we want. The signature is a complete nightmare: I'd like to not pick this option.

3. Move the authorization to the route level instead of the service level. I don't like this much either because in my minds eye security is most often a service level concern, but I could be wrong on this.

4. Make authorization a mounting concern as mentioned. This avoids all the security concerns and works immediately for servlet. Downsides: gives authorization special privilege (maybe thats not bad, security is pretty important) and requires some extra blaze (and future backends) work.

I'm personally most interested in options 1 then 4, but am interested in more people weighing in on this.

**Comment by frehn** [comment]
Regarding point 1, a variant of that might be to define `HttpService = PartialFunction[Request, Task[Response]]`; this might lessen the security hole potential by avoiding the construction of the `Task[Response]` object when checking for definedness via `service.isDefinedAt`.

**Comment by rossabaker** [comment]
We used to be a `PartialFunction[Request, Task[Response]]`.  We were able to clean up a lot of things with the current signature, but it did complicate other use cases.

A similar type to PartialFunction is `scalaz.NullResult`.  It's very nice in that it doesn't throw, but it lacks the syntactic literal support of `PartialFunction`.

I'm still a bit puzzled why it doesn't work in blaze.  I might need to put together an example.

**Comment by bryce-anderson** [comment]
@rossabaker, the problem shows itself when using the following pattern:
```scala
val wholeService = authenticate(serviceA) orElse serviceB
```
Even though you may have only wanted to secure ```serviceA```, ```serviceB``` is now behind the authentication wall because authentication for ```serviceA``` must happen even before its known if it will match the request. 
The problem is even more grim if using two different authentication strategies,

```scala
val wholeService = authenticate1(serviceA) orElse authenticate2(serviceB)
```
The authentication headers will collide and you will never actually be able to use ```serviceB```. This is actually where I first ran into the problem: I was trying to use a service composed of both simple and digest authorization for testing.

**Comment by rossabaker** [comment]
Okay, I now see the disconnect between my thinking and reality.  I was imagining that URI translation returned None if the prefix didn't match and delegated only if it did.  This is not so.  Drat.

**Comment by kaiserpelagic** [comment]
Just my two cents on authentication .... I agree that authentication should be middleware, it just feels right there. However, whenever I've done auth before I usually return an AuthenticatedUser along with the request, maybe not the best practice but it's been useful in the past. Having authentication as middleware would make this impossible unless there was a way to pass arbitrary data between services.  The way I currently construct my http4s services is to have an auth middleware and then fetch the user from the username (for basic auth) in the route if i need it.

**Comment by rossabaker** [comment]
The attributes on a request or response can be a way of out-of-band communication, but they do introduce a coupling between the attribute setter and the attribute getter.

It's also possible to play with functions that return tuples or case classes, as long as they're composed into the HttpService signature at the end.  That's a little more explicit, but also harder for a service to ignore what might be optional metadata.

**Comment by frehn** [comment]
The "optionality" could be expressed by giving two ways to construct authenticated services: the default one, not exposing the authentication metadata, with the same signature as in the current PR (`HttpService => HttpService`), and a second one with signature `Service[(Request, Metadata), Response] => HttpService`.

On the other hand, the attributes map in `Request` seems to be intended to be used to pass such metadata around. If that's true, I'd prefer to use this mechanism and keep the signatures as they are.

**Comment by frehn** [comment]
To see how this would look like, I implemented @rossabaker's first suggestion: to provide the authenticated user/realm via `Request.attributes`. Please find it here: https://github.com/frehn/http4s/commit/c68e2f34fc3751e95a8baee09932a9c4876f8024.

Note that this changes the signature of `getChallenge` to return `Task[Request \/ Challenge]` instead of `Task[Option[Challenge]]`, which I find quite nice.

**Comment by kaiserpelagic** [comment]
@frehn looks great. I think this is a good approach.

**Comment by rossabaker** [comment]
I like that, but the left is more conventionally the "bad" side.  Seems like `Challenge \/ Request` would be the more natural order?

**Comment by bryce-anderson** [comment]
@rossabaker, after the switch from ```Request \/ Challenge``` to ```Challenge \/ Request```, do you think this is ready to merge? We will still have the problem of authorization blocking downstream services.

**Comment by rossabaker** [comment]
I think it adds functionality over what we have.  I'm inclined to merge, and then we have continued soul searching to do on the order of the monads.

**Comment by bryce-anderson** [comment]
@frehn, do you want to change the order of the ```\/``` and submit another PR?

**Comment by frehn** [comment]
Sure!

**Pull request merged**
