### PR TITLE
Optimize mutable iterations while encoding data

### PR DESCRIPTION
**Pull request by ayushhooda**
Filename: package.scala
Action Items:
1. Logic to remove mutable iteration for encoding the hexadecimal data.

### CODE REVIEW

**Comment by ayushhooda** [comment]
Use of tail recursion won't compromise on performance issue but also avoid mutations

**Comment by ayushhooda** [comment]
@rossabaker Thanks for the appreciation. The benchmark results are motivating. But the build seems to be failing by addition of your file.

**Comment by rossabaker** [comment]
It's one of those intermittent blaze failures that only happens on Travis CI that we haven't gotten to the bottom of yet. :frowning:

**Comment by ayushhooda** [comment]
Ohh Now it seems to have passed all checks.

**Comment by ayushhooda** [comment]
@rossabaker Are we good to go with this patch?

**Comment by rossabaker** [comment]
We usually wait for a second reviewer to sign off, and then it's ready.

**Comment by ayushhooda** [comment]
Sounds good. @aeons @cquiroz @diesalbla please have a look.

**Comment by ayushhooda** [comment]
Thanks @cquiroz.
I guess, now we're good to go @rossabaker.
What do you suggest?

**Comment by rossabaker** [comment]
If you have an urgent need for the extra performance, I can cherry-pick this back to series/0.20.  There's also a bugfix PR open, so we'll be doing a maintenance release soon.  If it's just nice to have in the long run, it'll be released in the 0.21 series, and can be tried now with 0.21.0-SNAPSHOT.

**Pull request merged**
