### PR TITLE
Rectify `Client#fromHttpApp`

### PR DESCRIPTION
**Pull request by danicheg**

### CODE REVIEW

**Comment by armanbilge** [comment]
Did I screw up the merge? Very sorry 😢

**Comment by danicheg** [comment]
Truth be told, it's me who approved your PR 😄 
Also, we didn't release it, so no problem at all.

**Comment by armanbilge** [comment]
> we didn't release it

😶‍🌫️ don't say the "release" word for `main` branch ...

**Review by armanbilge — APPROVED** [review]
Thank you. Sad reminder that merges are going to get harder and harder 😢

**Comment by danicheg** [comment]
> Sad reminder that merges are going to get harder and harder

I was recently thinking of how it's hard could be to migrate from 0.23 to 1.0 for projects that hugely rely on http4s if there are no http4s contributors in the team. Certainly, it's not like CE 2 -> 3 migration but still.

**Pull request merged**
