### PR TITLE
Add IntelliJ code style configuration

### PR DESCRIPTION
**Pull request by aeons**
This adds the IntelliJ project configuration to use Twitter style imports.

### CODE REVIEW

**Comment by rossabaker** [comment]
:+1: 

Should we reformat the project in this PR, or do it separately after this big wave of middleware PRs is merged.

**Comment by aeons** [comment]
I'll merge the middleware PRs, fix conflicts in changelog, rebase this one on master and reformat everything.

**Comment by aeons** [comment]
My IJ install has fubared itself. Is anyone able to test whether this works on a clean import?

**Comment by tomwadeson** [comment]
@aeons: Yep, this worked for me on a fresh project import into IntelliJ

**Comment by aeons** [comment]
Cool, merging then.

**Pull request merged**
