### PR TITLE
Update to circe 0.14.2

### PR DESCRIPTION
**Pull request by armanbilge**
And a cherry on top!

### CODE REVIEW

**Comment by armanbilge** [comment]
Oh no, it needs Scala 3.1 :(

**Comment by armanbilge** [comment]
Is this a failure to be concerned about 🤔 
```
==> X org.http4s.circe.CirceSensitiveDataEntityDecoderSpec.should not include the JSON when failing to decode due to wrong data type of JSON key's value  0.008s munit.ComparisonFailException: /home/runner/work/http4s/http4s/circe/src/test/scala/org/http4s/circe/CirceSensitiveDataEntityDecoderSpec.scala:59
58:          assertEquals(details, "Could not decode JSON: <REDACTED>")
59:          assertEquals(cause.getMessage, "String: DownField(ssn)")
60:        case other => fail(other.toString)
values are not the same
=> Obtained
Got value '123456789' with wrong type, expecting string: DownField(ssn)
=> Diff (- obtained, + expected)
-Got value '123456789' with wrong type, expecting string: DownField(ssn)
```

**Comment by rossabaker** [comment]
Failure is probably this: https://github.com/circe/circe/pull/1617.  That was called out as a semantic change when they were debating calling the next release 0.14 vs. 0.15.

It would be weird to do a rugpull on Scala 3.0 users on the last release of the series.  They can bump to 0.14.2 themselves.

**Comment by armanbilge** [comment]
Right, I was just concerned if the error is leaking information it should. Agree that we should not bump to 3.1.

**Comment by rossabaker** [comment]
It's fine as long as no request information is in the sanitized field.  It can be in details.

**Pull request closed without merging**
