### PR TITLE
Merge Series/0.23 to main

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Review by danicheg — APPROVED** [review]

**Comment by bplommer** [comment]
Lots of tests failing with `BindException`.

**Comment by bplommer** [comment]
Too many tests failing with `BindException` for it to be a flake. But none of the new changes here look like they would cause that. I feel like @armanbilge might have an idea about this?

**Comment by armanbilge** [comment]
Huh, that's odd that so many failed. Also I can't tell for sure but are all the client suites running at the same time for some reason? It seems like the JVM scaffold server is always binding to the same port, so if multiple suites using it start in parallel it runs into trouble. Let me see if I can chase it down.

**Comment by danicheg** [comment]
This seems to be for all `series/0.23` branches too #5896, #5897

**Comment by armanbilge** [comment]
No, the JVM scaffold seems to be using port 0. So then I don't know what's going on anymore 😕 

https://github.com/http4s/http4s/blob/e1062470658a302d7dc5680672f6787e4ee34a39/client/jvm/src/test/scala/org/http4s/client/scaffold/ServerScaffold.scala#L65

**Comment by bplommer** [comment]
Possibly just GHA playing up?

**Comment by armanbilge** [comment]
I have a fix incoming.

**Comment by bplommer** [comment]
I'll try to get back to this in the next couple of days but other people should feel free to take over

**Comment by danicheg** [comment]
I could give it a try if you don't mind. I'm just battling for the 'merge-ninja' achievement 😆

**Comment by bplommer** [comment]
Go for it 😄

**Comment by bplommer** [comment]
Superseded by #5925

**Pull request closed without merging**
