### PR TITLE
Added new WS API which allows receiving Ping messages from the client

### PR DESCRIPTION
**Pull request by khrupalyk**
Possible fix for [Provide ability to receive WebSocket Ping/Pong frames](https://github.com/http4s/http4s/issues/3129)`

### CODE REVIEW

**Comment by rossabaker** [comment]
Thanks.  Don't we probably want to be able to receive `Pong` frames, too?

**Comment by khrupalyk** [comment]
Probably yes, we should.

**Comment by khrupalyk** [comment]
@rossabaker Updated PR.

**Comment by rossabaker** [comment]
Binary breaking, but not source breaking and should not be semantically breaking.

**Pull request merged**
